### ISSUE TITLE
phyluce_assembly_get_trinity_coverage spades issue

### ISSUE THREAD

**Issue by mcfaddenlab** [faircloth-lab/phyluce#102]
hi brant,

i am trying to calculate contig coverage on spades assemblies using the updated phyluce_assembly_get_trinity_coverage. I am getting an error (in the attached file). maybe its a naming issue, but this script is working fine for trinity assemblies.

cheers,
andrea

**Comment by mcfaddenlab** [comment]
not sure what happened to attachment...here is the error
phyluce_assembly_get_trinity_coverage --assemblies spades-assemblies --cores 52 --assemblo-config assembly_cov2.conf --assembler spades --log-path log
2018-04-12 13:55:15,152 - phyluce_assembly_get_trinity_coverage - INFO - ========= Starting phyluce_assembly_get_trinity_coverage ========
2018-04-12 13:55:15,152 - phyluce_assembly_get_trinity_coverage - INFO - Version: 1.5.0
2018-04-12 13:55:15,153 - phyluce_assembly_get_trinity_coverage - INFO - Argument --assembler: spades
2018-04-12 13:55:15,153 - phyluce_assembly_get_trinity_coverage - INFO - Argument --assemblies: /data/mcfadden/aquattrini/DATA/UCESeqs/Peterun/spades-assemblies
2018-04-12 13:55:15,153 - phyluce_assembly_get_trinity_coverage - INFO - Argument --assemblo_config: /data/mcfadden/aquattrini/DATA/UCESeqs/Peterun/assembly_cov2.conf
2018-04-12 13:55:15,153 - phyluce_assembly_get_trinity_coverage - INFO - Argument --bwa_mem: False
2018-04-12 13:55:15,154 - phyluce_assembly_get_trinity_coverage - INFO - Argument --clean: False
2018-04-12 13:55:15,154 - phyluce_assembly_get_trinity_coverage - INFO - Argument --cores: 52
2018-04-12 13:55:15,154 - phyluce_assembly_get_trinity_coverage - INFO - Argument --log_path: /data/mcfadden/aquattrini/DATA/UCESeqs/Peterun/log
2018-04-12 13:55:15,154 - phyluce_assembly_get_trinity_coverage - INFO - Argument --subfolder: 
2018-04-12 13:55:15,154 - phyluce_assembly_get_trinity_coverage - INFO - Argument --trim: False
2018-04-12 13:55:15,155 - phyluce_assembly_get_trinity_coverage - INFO - Argument --verbosity: INFO
2018-04-12 13:55:15,155 - phyluce_assembly_get_trinity_coverage - INFO - Getting input filenames
2018-04-12 13:55:15,162 - phyluce_assembly_get_trinity_coverage - INFO - ----------------------- Processing Coral1 -----------------------
2018-04-12 13:55:15,162 - phyluce_assembly_get_trinity_coverage - INFO - Finding fastq/fasta files
2018-04-12 13:55:15,166 - phyluce_assembly_get_trinity_coverage - INFO - File type is fastq
2018-04-12 13:55:15,168 - phyluce_assembly_get_trinity_coverage - INFO - Running bwa indexing against /data/mcfadden/aquattrini/DATA/UCESeqs/Peterun/spades-assemblies/Coral1_spades/contigs.fasta
2018-04-12 13:55:19,050 - phyluce_assembly_get_trinity_coverage - INFO - Indexing fasta for Coral1
2018-04-12 13:55:19,117 - phyluce_assembly_get_trinity_coverage - INFO - Creating FASTA dict for Coral1
2018-04-12 13:55:19,351 - phyluce_assembly_get_trinity_coverage - INFO - Creating read index file for Coral1-READ1.fastq.gz
2018-04-12 13:55:30,599 - phyluce_assembly_get_trinity_coverage - INFO - Creating read index file for Coral1-READ2.fastq.gz
2018-04-12 13:55:41,676 - phyluce_assembly_get_trinity_coverage - INFO - Building BAM for Coral1
2018-04-12 13:57:03,101 - phyluce_assembly_get_trinity_coverage - INFO - Cleaning BAM for Coral1
2018-04-12 13:57:58,897 - phyluce_assembly_get_trinity_coverage - INFO - Adding RG header to BAM for Coral1
2018-04-12 13:58:56,366 - phyluce_assembly_get_trinity_coverage - INFO - Creating read index file for Coral1-READ-singleton.fastq.gz
2018-04-12 13:58:57,041 - phyluce_assembly_get_trinity_coverage - INFO - Building BAM for Coral1
2018-04-12 13:58:58,445 - phyluce_assembly_get_trinity_coverage - INFO - Cleaning BAM for Coral1
2018-04-12 13:59:01,004 - phyluce_assembly_get_trinity_coverage - INFO - Adding RG header to BAM for Coral1
2018-04-12 13:59:03,940 - phyluce_assembly_get_trinity_coverage - INFO - Merging BAMs for Coral1
2018-04-12 13:59:41,743 - phyluce_assembly_get_trinity_coverage - INFO - Marking read duplicates from BAM for Coral1
2018-04-12 14:01:23,319 - phyluce_assembly_get_trinity_coverage - INFO - Indexing BAM for Coral1
2018-04-12 14:01:25,670 - phyluce_assembly_get_trinity_coverage - INFO - Computing coverage with GATK for Coral1
2018-04-12 14:09:58,220 - phyluce_assembly_get_trinity_coverage - INFO - Screening contigs for coverage
Traceback (most recent call last):
  File "/data/mcfadden/aquattrini/PROGRAMS/anaconda2/bin/phyluce_assembly_get_trinity_coverage", line 215, in <module>
    main()
  File "/data/mcfadden/aquattrini/PROGRAMS/anaconda2/bin/phyluce_assembly_get_trinity_coverage", line 205, in main
    overall_contigs = gatk.get_untrimmed_coverage_from_output(log, sample, assembly_pth, coverage, args.assembler)
  File "/data/mcfadden/aquattrini/PROGRAMS/anaconda2/lib/python2.7/site-packages/phyluce/gatk.py", line 210, in get_untrimmed_coverage_from_output
    regex = re.compile("({}.*):(\d+)".format(get_user_param("headers", "spades")))
  File "/data/mcfadden/aquattrini/PROGRAMS/anaconda2/lib/python2.7/site-packages/phyluce/pth.py", line 42, in get_user_param
    return config.get(section, param)
  File "/data/mcfadden/aquattrini/PROGRAMS/anaconda2/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'spades' in section: 'headers'

**Comment by brantfaircloth** [comment]
You need a section in your `phyluce.conf` or `~/.phyluce.conf` that contains the "spades" line below:

```
[headers]
trinity:comp\d+_c\d+_seq\d+|c\d+_g\d+_i\d+|TR\d+\|c\d+_g\d+_i\d+|TRINITY_DN\d+_c\d+_g\d+_i\d+
velvet:node_\d+
spades:NODE_\d+_length_\d+_cov_\d+.\d+
abyss:\d+
```

I just fixed this in a42cf226eef4421b0bd3589d84355fc520e04f08.

**Comment by mcfaddenlab** [comment]
ok. that fixed that problem. here is a new error:

/data/mcfadden/aquattrini/PROGRAMS/anaconda2/bin/phyluce_assembly_get_trinity_coverage --assemblies spades-assemblies --cores 52 --assemblo-config assembly_cov2.conf --assembler spades --log-path log
2018-04-18 09:26:46,501 - phyluce_assembly_get_trinity_coverage - INFO - ========= Starting phyluce_assembly_get_trinity_coverage ========
2018-04-18 09:26:46,501 - phyluce_assembly_get_trinity_coverage - INFO - Version: 1.5.0
2018-04-18 09:26:46,501 - phyluce_assembly_get_trinity_coverage - INFO - Argument --assembler: spades
2018-04-18 09:26:46,501 - phyluce_assembly_get_trinity_coverage - INFO - Argument --assemblies: /data/mcfadden/aquattrini/DATA/UCESeqs/Peterun/spades-assemblies
2018-04-18 09:26:46,502 - phyluce_assembly_get_trinity_coverage - INFO - Argument --assemblo_config: /data/mcfadden/aquattrini/DATA/UCESeqs/Peterun/assembly_cov2.conf
2018-04-18 09:26:46,502 - phyluce_assembly_get_trinity_coverage - INFO - Argument --bwa_mem: False
2018-04-18 09:26:46,502 - phyluce_assembly_get_trinity_coverage - INFO - Argument --clean: False
2018-04-18 09:26:46,502 - phyluce_assembly_get_trinity_coverage - INFO - Argument --cores: 52
2018-04-18 09:26:46,502 - phyluce_assembly_get_trinity_coverage - INFO - Argument --log_path: /data/mcfadden/aquattrini/DATA/UCESeqs/Peterun/log
2018-04-18 09:26:46,503 - phyluce_assembly_get_trinity_coverage - INFO - Argument --subfolder: 
2018-04-18 09:26:46,503 - phyluce_assembly_get_trinity_coverage - INFO - Argument --trim: False
2018-04-18 09:26:46,503 - phyluce_assembly_get_trinity_coverage - INFO - Argument --verbosity: INFO
2018-04-18 09:26:46,503 - phyluce_assembly_get_trinity_coverage - INFO - Getting input filenames
2018-04-18 09:26:46,510 - phyluce_assembly_get_trinity_coverage - INFO - ----------------------- Processing Coral1 -----------------------
2018-04-18 09:26:46,510 - phyluce_assembly_get_trinity_coverage - INFO - Finding fastq/fasta files
2018-04-18 09:26:46,516 - phyluce_assembly_get_trinity_coverage - INFO - File type is fastq
2018-04-18 09:26:46,517 - phyluce_assembly_get_trinity_coverage - INFO - Running bwa indexing against /data/mcfadden/aquattrini/DATA/UCESeqs/Peterun/spades-assemblies/Coral1_spades/contigs.fasta
2018-04-18 09:26:50,852 - phyluce_assembly_get_trinity_coverage - INFO - Indexing fasta for Coral1
2018-04-18 09:26:50,922 - phyluce_assembly_get_trinity_coverage - INFO - Creating FASTA dict for Coral1
2018-04-18 09:26:51,152 - phyluce_assembly_get_trinity_coverage - INFO - Creating read index file for Coral1-READ1.fastq.gz
2018-04-18 09:27:01,988 - phyluce_assembly_get_trinity_coverage - INFO - Creating read index file for Coral1-READ2.fastq.gz
2018-04-18 09:27:13,326 - phyluce_assembly_get_trinity_coverage - INFO - Building BAM for Coral1
2018-04-18 09:28:32,805 - phyluce_assembly_get_trinity_coverage - INFO - Cleaning BAM for Coral1
2018-04-18 09:29:22,289 - phyluce_assembly_get_trinity_coverage - INFO - Adding RG header to BAM for Coral1
2018-04-18 09:30:21,049 - phyluce_assembly_get_trinity_coverage - INFO - Creating read index file for Coral1-READ-singleton.fastq.gz
2018-04-18 09:30:21,712 - phyluce_assembly_get_trinity_coverage - INFO - Building BAM for Coral1
2018-04-18 09:30:23,029 - phyluce_assembly_get_trinity_coverage - INFO - Cleaning BAM for Coral1
2018-04-18 09:30:25,233 - phyluce_assembly_get_trinity_coverage - INFO - Adding RG header to BAM for Coral1
2018-04-18 09:30:28,024 - phyluce_assembly_get_trinity_coverage - INFO - Merging BAMs for Coral1
2018-04-18 09:31:05,203 - phyluce_assembly_get_trinity_coverage - INFO - Marking read duplicates from BAM for Coral1
2018-04-18 09:32:42,098 - phyluce_assembly_get_trinity_coverage - INFO - Indexing BAM for Coral1
2018-04-18 09:32:44,251 - phyluce_assembly_get_trinity_coverage - INFO - Computing coverage with GATK for Coral1
2018-04-18 09:42:59,626 - phyluce_assembly_get_trinity_coverage - INFO - Screening contigs for coverage
Traceback (most recent call last):
  File "/data/mcfadden/aquattrini/PROGRAMS/anaconda2/bin/phyluce_assembly_get_trinity_coverage", line 215, in <module>
    main()
  File "/data/mcfadden/aquattrini/PROGRAMS/anaconda2/bin/phyluce_assembly_get_trinity_coverage", line 205, in main
    overall_contigs = gatk.get_untrimmed_coverage_from_output(log, sample, assembly_pth, coverage, args.assembler)
  File "/data/mcfadden/aquattrini/PROGRAMS/anaconda2/lib/python2.7/site-packages/phyluce/gatk.py", line 232, in get_untrimmed_coverage_from_output
    match_name, pos = search.groups()
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by brantfaircloth** [comment]
Looks like the regular expression that is provided as part of the spades line you added to `~/.phyluce.conf` may not match the output from the version of spades you used.

**Comment by mcfaddenlab** [comment]
i used spades 3.10 (not part of phyluce).  I think the reg exp matches the header?
header:
>NODE_1_length_3029_cov_22.0266

here is the end of my phyluce.conf

#----------------
#    Advanced
#----------------

[headers]
trinity:comp\d+_c\d+_seq\d+|c\d+_g\d+_i\d+|TR\d+\|c\d+_g\d+_i\d+
velvet:node_\d+
spades:NODE_\d+_length_\d+_cov_\d+.\d+
abyss:\d+

**Comment by mcfaddenlab** [comment]
I used spades 3.10 (not part of phyluce). I think the reg exp matches the header?
header:

NODE_1_length_3029_cov_22.0266

here is the end of my phyluce.conf

 used spades 3.10 (not part of phyluce). I think the reg exp matches the header?
header:

NODE_1_length_3029_cov_22.0266
here is the end of my phyluce.conf

#----------------
#    Advanced
#----------------

[headers]
trinity:comp\d+_c\d+_seq\d+|c\d+_g\d+_i\d+|TR\d+\|c\d+_g\d+_i\d+
velvet:node_\d+
spades:NODE_\d+_length_\d+_cov_\d+.\d+
abyss:\d+

**Comment by mcfaddenlab** [comment]
i think the header matches the reg expression in the phyluce.conf file
NODE_1_length_3029_cov_22

NODE_\d+_length_\d+_cov_\d+.\d+

I did run spades 3.10 on my dataset

**Comment by mcfaddenlab** [comment]
i think the header matches the reg expression in the phyluce.conf file
NODE_1_length_3029_cov_22

**Comment by brantfaircloth** [comment]
If there are not values after `cov_22`, then the regular expression should be:

`spades:NODE_\d+_length_\d+_cov_\d+`

**Comment by brantfaircloth** [comment]
I'm not sure and do not have time to debug.  Perhaps try something like:

```
NODE_\d+_length_\d+_cov_\d+.\d+
```

Other than that, you can can look in the file that the program is attempting to read to see what the contig headers look like (this should be in the `-coverage` files that are created).  You can also run the program with debugging turned on:
```
python /data/mcfadden/aquattrini/PROGRAMS/anaconda2/bin/phyluce_assembly_get_trinity_coverage -m pdb <other params>
```
Which will stop at the error.  Then you can poke around where the error is happening.  For instance, you might run the line above, let it die, then run:
```
print ls
```
where the debugger stops.  That's the output that should be useful to diagnose the issue.

**Comment by mcfaddenlab** [comment]
roger. thanks for the help. i will plug away at it...

**Comment by mcfaddenlab** [comment]
so! i found the issue~ there were two different types of header names in the SPADES contigs.fasta files. I added a second reg exp line to the [headers] section in the phyluce.conf file

headers are BOTH like this:
NODE_1_length_3029_cov_22
or 
NODE_1_length_3029_cov_22.45256
