### ISSUE TITLE
Possible issues with miniconda: phyluce_ commands don't seem to work.

### ISSUE THREAD

**Issue by drwhitehouse** [faircloth-lab/phyluce#109]
I've been trying to build phyluce into a singularity container and I am using Centos6 and using Miniconda2.
I've been also trying to automate the tutorial:

http://phyluce.readthedocs.io/en/latest/tutorial-one.html#

In order to validate my build. I think everything seems to work (fairly) well up to and including the step where illumiprocessor cleans the read data.

As soon as I use the first phyluce command in the quality control step, things begin going wrong:

```
Singularity phyluce.simg:/tmp/test_phyluce/uce-tutorial/clean-fastq> ls
alligator_mississippiensis  anolis_carolinensis  gallus_gallus  mus_musculus
Singularity phyluce.simg:/tmp/test_phyluce/uce-tutorial/clean-fastq> for i in *; do phyluce_assembly_get_fastq_lengths --input $i/split-adapter-quality-trimmed/ --csv; done                                      
Traceback (most recent call last):
  File "/usr/local/miniconda2/bin/phyluce_assembly_get_fastq_lengths", line 20, in <module>
    from phyluce.helpers import is_dir, FullPaths
  File "/usr/local/miniconda2/lib/python2.7/site-packages/phyluce/__init__.py", line 16, in <module>
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/local/miniconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/miniconda2/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/local/miniconda2/bin/phyluce_assembly_get_fastq_lengths", line 20, in <module>
    from phyluce.helpers import is_dir, FullPaths
  File "/usr/local/miniconda2/lib/python2.7/site-packages/phyluce/__init__.py", line 16, in <module>
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/local/miniconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/miniconda2/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/local/miniconda2/bin/phyluce_assembly_get_fastq_lengths", line 20, in <module>
    from phyluce.helpers import is_dir, FullPaths
  File "/usr/local/miniconda2/lib/python2.7/site-packages/phyluce/__init__.py", line 16, in <module>
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/local/miniconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/miniconda2/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/local/miniconda2/bin/phyluce_assembly_get_fastq_lengths", line 20, in <module>
    from phyluce.helpers import is_dir, FullPaths
  File "/usr/local/miniconda2/lib/python2.7/site-packages/phyluce/__init__.py", line 16, in <module>
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/local/miniconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/miniconda2/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
If you can provide any advice I would be grateful.

**Comment by brantfaircloth** [comment]
is `git` installed in the container?  that may be the issue.

**Comment by drwhitehouse** [comment]
It is not. I am assuming therefore that it is required and will give that a try.

**Comment by brantfaircloth** [comment]
It is required, at the moment.  phyluce is meant to fail silently when git is not installed, but that sometimes does not happen (as you've seen).  The problem should be fixed in an updated build of phyluce that i'll hopefully get up on bioconda soon.

**Comment by drwhitehouse** [comment]
Thanks for coming back to me so quickly. I'll do some testing and let you know how I get on.
