### ISSUE TITLE
Trinity 2013 fails in the latest phyluce version (IOError: Neither Trinity.fasta nor trinity.log were found in output.)

### ISSUE THREAD

**Issue by nnbuainain** [faircloth-lab/phyluce#119]
Hi, 

Has anyone been able to run old Trinity versions after this new phyluce update?
In the previous phyluce version I got that working by changing the path to an old Trinity version (Trinity r2013-02-25)  in the phyluce.conf file, changing "--max_memory" to "--JM" in lines 142, 160,209 and 225 in phyluce_assembly_assemblo_trinity and at last changing the java path in the Trinity.pl file (old version) to java jdk 1.7.80 version and not the latest. That used to work fine here. 

But now after the latest upgrade it stopped working. I get the error below in my terminal and my Trinity.log file is empty.

2018-08-08 08:55:12,640 - phyluce_assembly_assemblo_trinity - WARNING - Did not clean all fastq/fasta files from /home/croizat/Documents/Nelson/UCEArremon/testeapagar/FMNH_430070_Arr_cas_cas_trinity
2018-08-08 08:55:12,640 - phyluce_assembly_assemblo_trinity - INFO - Removing extraneous Trinity files
Traceback (most recent call last):
  File "/home/croizat/anaconda2/envs/phyluce/bin/phyluce_assembly_assemblo_trinity", line 362, in <module>
    main()
  File "/home/croizat/anaconda2/envs/phyluce/bin/phyluce_assembly_assemblo_trinity", line 341, in main
    cleanup_trinity_assembly_folder(output, log)
  File "/home/croizat/anaconda2/envs/phyluce/bin/phyluce_assembly_assemblo_trinity", line 283, in cleanup_trinity_assembly_folder
    raise IOError("Neither Trinity.fasta nor trinity.log were found in output.")
IOError: Neither Trinity.fasta nor trinity.log were found in output.

I then retrieved the original latest files mentioned before and I got the same error in the terminal but with the following error in the Trinity.log file.

Error, do not understand options: --max_memory 8G

Does anyone have a solution for that? 

Thanks!!
Nelson

**Comment by brantfaircloth** [comment]
The old version of Trinity is no longer supported (and given problems, in general, with getting Trinity installed and built on different platforms, I may drop it altogether - it's a nightmare).  The easiest fix is to use an older version of phyluce with the version of Trinity you want, and then use the newer version of phyluce for everything else. This is reasonably easy to do by creating different `conda` environments for the versions of phyluce you want and switching between them.

**Comment by nnbuainain** [comment]
Dear Brant,

Thank you for your quick answer. I understand, I can only imagine the nightmare it is. There is always something going wrong with it. 

Anyways, thanks for the solution. That should work fine here.

Best

**Comment by brantfaircloth** [comment]
Cool.  Let me know if you run into any problems with that approach.  Basically, any version of phyluce **before** v1.6.2 should be good.  you should be able to get that with something like:

```
conda env create -n phyluce1.6.1 phyluce=1.6.1
```

Then, run `source activate phyluce1.6.1` to use that environment (`source deactivate` to stop using it).

**Comment by nnbuainain** [comment]
Alright, It worked. 

The only version before 1.6.2 that was available was 1.5.0 so I Installed the version 1.6.5 with:

conda create --name phyluce1.6.5 phyluce=1.6.5
(conda env create..... didn't work for me)

and then applied the changes in phyluce.conf and phyluce_assembly_assemblo_trinity that I mentioned before. 

Good and fast solution. Might be a good idea for similar version problems like this. 

Thank you so much

**Comment by mchj74** [comment]
ubuntu 16.04. I am using the data from tutorial.

**Comment by mchj74** [comment]
Linux. I am using the data from the tutorial on Ruby which is a large memory multi-processor

**Comment by brantfaircloth** [comment]
can you provide the output from the trinity.log file that is in the directory created for the assembly that failed?  that would be helpful.  also, have you tried any of the other assemblers?

**Comment by mchj74** [comment]
yes, I tried both ABySS and Velvet. The error is :("There are not
appropriate files in {}".format(dir)) and the Trinity log file is attached.

**Comment by brantfaircloth** [comment]
I don’t see a link to trinity.log (or it’s content).

**Comment by mchj74** [comment]
2019-01-07 11:22:42,306 - phyluce_assembly_assemblo_trinity - INFO - Argument --cores: 640
2019-01-07 11:22:42,306 - phyluce_assembly_assemblo_trinity - INFO - Argument --dir: None
2019-01-07 11:22:42,306 - phyluce_assembly_assemblo_trinity - INFO - Argument --log_path: /datastore/cha737/uce-tutorial/log
2019-01-07 11:22:42,306 - phyluce_assembly_assemblo_trinity - INFO - Argument --min_kmer_coverage: 2
2019-01-07 11:22:42,306 - phyluce_assembly_assemblo_trinity - INFO - Argument --output: /datastore/cha737/uce-tutorial/trinity-assemblies
2019-01-07 11:22:42,306 - phyluce_assembly_assemblo_trinity - INFO - Argument --subfolder: .
2019-01-07 11:22:42,306 - phyluce_assembly_assemblo_trinity - INFO - Argument --verbosity: INFO
2019-01-07 11:22:42,306 - phyluce_assembly_assemblo_trinity - INFO - Getting input filenames and creating output directories
2019-01-07 11:22:42,314 - phyluce_assembly_assemblo_trinity - INFO - ------------- Processing alligator_mississippiensis -------------
2019-01-07 11:22:42,314 - phyluce_assembly_assemblo_trinity - INFO - Finding fastq/fasta files
2019-01-07 11:22:42,317 - phyluce_assembly_assemblo_trinity - INFO - File type is fastq
2019-01-07 11:22:42,318 - phyluce_assembly_assemblo_trinity - INFO - Copying raw read data to /datastore/cha737/uce-tutorial/trinity-assemblies/alligator_mississippiensis_trinity
2019-01-07 11:22:42,920 - phyluce_assembly_assemblo_trinity - INFO - Combining singleton reads with R1 data
2019-01-07 11:22:42,956 - phyluce_assembly_assemblo_trinity - INFO - Running Trinity.pl for PE data
2019-01-07 11:22:54,427 - phyluce_assembly_assemblo_trinity - WARNING - Did not clean all fastq/fasta files from /datastore/cha737/uce-tutorial/trinity-assemblies/alligator_mississippiensis_trinity
2019-01-07 11:22:54,427 - phyluce_assembly_assemblo_trinity - INFO - Removing extraneous Trinity files
2019-01-07 13:04:39,215 - phyluce_assembly_assemblo_trinity - INFO - =========== Starting phyluce_assembly_assemblo_trinity ==========
2019-01-07 13:04:39,216 - phyluce_assembly_assemblo_trinity - INFO - Version: git fatal: Not a git repository: '/home/cha737/anaconda2/envs/phyluce/lib/python2.7/site-packages/.git'
2019-01-07 13:04:39,216 - phyluce_assembly_assemblo_trinity - INFO - Argument --clean: True
2019-01-07 13:04:39,216 - phyluce_assembly_assemblo_trinity - INFO - Argument --config: /datastore/cha737/uce-tutorial/assembly.conf
2019-01-07 13:04:39,216 - phyluce_assembly_assemblo_trinity - INFO - Argument --cores: 640
2019-01-07 13:04:39,216 - phyluce_assembly_assemblo_trinity - INFO - Argument --dir: None
2019-01-07 13:04:39,216 - phyluce_assembly_assemblo_trinity - INFO - Argument --log_path: /datastore/cha737/uce-tutorial/log
2019-01-07 13:04:39,216 - phyluce_assembly_assemblo_trinity - INFO - Argument --min_kmer_coverage: 2
2019-01-07 13:04:39,217 - phyluce_assembly_assemblo_trinity - INFO - Argument --output: /datastore/cha737/uce-tutorial/trinity-assemblies
2019-01-07 13:04:39,217 - phyluce_assembly_assemblo_trinity - INFO - Argument --subfolder: .
2019-01-07 13:04:39,217 - phyluce_assembly_assemblo_trinity - INFO - Argument --verbosity: INFO
2019-01-07 13:04:39,217 - phyluce_assembly_assemblo_trinity - INFO - Getting input filenames and creating output directories
2019-01-07 13:04:39,218 - phyluce_assembly_assemblo_trinity - INFO - ------------- Processing alligator_mississippiensis -------------
2019-01-07 13:05:38,967 - phyluce_assembly_assemblo_trinity - INFO - =========== Starting phyluce_assembly_assemblo_trinity ==========
2019-01-07 13:05:38,967 - phyluce_assembly_assemblo_trinity - INFO - Version: git fatal: Not a git repository: '/home/cha737/anaconda2/envs/phyluce/lib/python2.7/site-packages/.git'
2019-01-07 13:05:38,968 - phyluce_assembly_assemblo_trinity - INFO - Argument --clean: True
2019-01-07 13:05:38,968 - phyluce_assembly_assemblo_trinity - INFO - Argument --config: /datastore/cha737/uce-tutorial/assembly.conf
2019-01-07 13:05:38,968 - phyluce_assembly_assemblo_trinity - INFO - Argument --cores: 640
2019-01-07 13:05:38,968 - phyluce_assembly_assemblo_trinity - INFO - Argument --dir: None
2019-01-07 13:05:38,968 - phyluce_assembly_assemblo_trinity - INFO - Argument --log_path: /datastore/cha737/uce-tutorial/log
2019-01-07 13:05:38,968 - phyluce_assembly_assemblo_trinity - INFO - Argument --min_kmer_coverage: 2
2019-01-07 13:05:38,968 - phyluce_assembly_assemblo_trinity - INFO - Argument --output: /datastore/cha737/uce-tutorial/trinity-assemblies
2019-01-07 13:05:38,968 - phyluce_assembly_assemblo_trinity - INFO - Argument --subfolder: .
2019-01-07 13:05:38,968 - phyluce_assembly_assemblo_trinity - INFO - Argument --verbosity: INFO
2019-01-07 13:05:38,968 - phyluce_assembly_assemblo_trinity - INFO - Getting input filenames and creating output directories
2019-01-07 13:05:38,970 - phyluce_assembly_assemblo_trinity - INFO - ------------- Processing alligator_mississippiensis -------------
2019-01-07 13:05:38,977 - phyluce_assembly_assemblo_trinity - INFO - Finding fastq/fasta files
2019-01-07 13:05:38,980 - phyluce_assembly_assemblo_trinity - INFO - File type is fastq
2019-01-07 13:05:38,980 - phyluce_assembly_assemblo_trinity - INFO - Copying raw read data to /datastore/cha737/uce-tutorial/trinity-assemblies/alligator_mississippiensis_trinity
2019-01-07 13:05:39,489 - phyluce_assembly_assemblo_trinity - INFO - Combining singleton reads with R1 data
2019-01-07 13:05:39,516 - phyluce_assembly_assemblo_trinity - INFO - Running Trinity.pl for PE data
2019-01-07 13:05:49,952 - phyluce_assembly_assemblo_trinity - WARNING - Did not clean all fastq/fasta files from /datastore/cha737/uce-tutorial/trinity-assemblies/alligator_mississippiensis_trinity
2019-01-07 13:05:49,952 - phyluce_assembly_assemblo_trinity - INFO - Removing extraneous Trinity files
2019-01-09 15:12:37,323 - phyluce_assembly_assemblo_trinity - INFO - =========== Starting phyluce_assembly_assemblo_trinity ==========
2019-01-09 15:12:37,437 - phyluce_assembly_assemblo_trinity - INFO - Version: git fatal: Not a git repository: '/home/cha737/anaconda2/envs/phyluce/lib/python2.7/site-packages/.git'
2019-01-09 15:12:37,437 - phyluce_assembly_assemblo_trinity - INFO - Argument --clean: True
2019-01-09 15:12:37,437 - phyluce_assembly_assemblo_trinity - INFO - Argument --config: /datastore/cha737/uce-tutorial/assembly.conf
2019-01-09 15:12:37,437 - phyluce_assembly_assemblo_trinity - INFO - Argument --cores: 640
2019-01-09 15:12:37,437 - phyluce_assembly_assemblo_trinity - INFO - Argument --dir: None
2019-01-09 15:12:37,437 - phyluce_assembly_assemblo_trinity - INFO - Argument --log_path: /datastore/cha737/uce-tutorial/log
2019-01-09 15:12:37,437 - phyluce_assembly_assemblo_trinity - INFO - Argument --min_kmer_coverage: 2
2019-01-09 15:12:37,438 - phyluce_assembly_assemblo_trinity - INFO - Argument --output: /datastore/cha737/uce-tutorial/trinity-assemblies
2019-01-09 15:12:37,438 - phyluce_assembly_assemblo_trinity - INFO - Argument --subfolder: .
2019-01-09 15:12:37,438 - phyluce_assembly_assemblo_trinity - INFO - Argument --verbosity: INFO
2019-01-09 15:12:37,438 - phyluce_assembly_assemblo_trinity - INFO - Getting input filenames and creating output directories
2019-01-09 15:12:37,510 - phyluce_assembly_assemblo_trinity - INFO - ------------- Processing alligator_mississippiensis -------------
2019-01-09 15:12:37,513 - phyluce_assembly_assemblo_trinity - INFO - Finding fastq/fasta files
2019-01-09 15:12:37,516 - phyluce_assembly_assemblo_trinity - INFO - File type is fastq
2019-01-09 15:12:37,517 - phyluce_assembly_assemblo_trinity - INFO - Copying raw read data to /datastore/cha737/uce-tutorial/trinity-assemblies/alligator_mississippiensis_trinity
2019-01-09 15:12:38,459 - phyluce_assembly_assemblo_trinity - INFO - Combining singleton reads with R1 data
2019-01-09 15:12:38,502 - phyluce_assembly_assemblo_trinity - INFO - Running Trinity.pl for PE data
2019-01-09 15:14:20,465 - phyluce_assembly_assemblo_trinity - WARNING - Did not clean all fastq/fasta files from /datastore/cha737/uce-tutorial/trinity-assemblies/alligator_mississippiensis_trinity
2019-01-09 15:14:20,466 - phyluce_assembly_assemblo_trinity - INFO - Removing extraneous Trinity files
"phyluce_assembly_assemblo_trinity.log" 346L, 41427C

**Comment by mchj74** [comment]
Is it not the content of trinity.log?

**Comment by cakacz** [comment]
I'm having a somewhat similar problem. I had a set of 14 assemblies to run on a supercomputer (I specified 64gb memory, so I don't think it's a memory issue). Two complete with the warning about not cleaning all files before the entire thing ended on the IOError for the third assembly. I have updated the jellyfish version and the trinity.log shows the entire process completing on the second run (one that listed the warning about not cleaning all the files). I have outputs that appear to be contigs and cannot figure out what went wrong or how to fix it. I did try to find an earlier version of phyluce, but nothing earlier than 1.6.2 is available.

**Comment by cakacz** [comment]
When I checked the trinity.log for the failed run, it said this.

Trinity version: v2.1.1
-ERROR: couldn't run the network check to confirm latest Trinity software version.

Thursday, April 18, 2019: 18:36:40      CMD: java -Xmx64m -XX:ParallelGCThreads=2 -jar /mnt/homeapps/home/aubcxk/anaconda2/envs/phyluce/opt/trinity-2.1.1/util/support_scripts/ExitTester.jar 0
Thursday, April 18, 2019: 18:36:40      CMD: java -Xmx64m -XX:ParallelGCThreads=2 -jar /mnt/homeapps/home/aubcxk/anaconda2/envs/phyluce/opt/trinity-2.1.1/util/support_scripts/ExitTester.jar 1
Thursday, April 18, 2019: 18:36:40      CMD: mkdir -p /mnt/homeapps/home/aubcxk/pilot-trinity-assemblies_2/Barley_Schizaphis_grammium_trinity/chrysalis


----------------------------------------------------------------------------------
-------------- Trinity Phase 1: Clustering of RNA-Seq Reads  ---------------------
----------------------------------------------------------------------------------

Converting input files. (in parallel)Thursday, April 18, 2019: 18:36:40 CMD: gunzip -c /mnt/homeapps/home/aubcxk/pilot-trinity-assemblies_2/Barley_Schizaphis_grammium_trinity/Barley_Schizaphis_grammium-READ1.fastq.gz | fastool --illumina-trinity --to-fasta >> left.fa 2> /mnt/homeapps/home/aubcxk/pilot-trinity-assemblies_2/Barley_Schizaphis_grammium_trinity/Barley_Schizaphis_grammium-READ1.fastq.gz.readcount 
Thursday, April 18, 2019: 18:36:40      CMD: gunzip -c /mnt/homeapps/home/aubcxk/pilot-trinity-assemblies_2/Barley_Schizaphis_grammium_trinity/Barley_Schizaphis_grammium-READ2.fastq.gz | fastool --illumina-trinity --to-fasta >> right.fa 2> /mnt/homeapps/home/aubcxk/pilot-trinity-assemblies_2/Barley_Schizaphis_grammium_trinity/Barley_Schizaphis_grammium-READ2.fastq.gz.readcount 

gzip: stdout: Broken pipe
-conversion of 3526836 from FQ to FA format succeeded.
Thread 1 terminated abnormally: Error, counts of reads in FQ: 3643393 (as per gunzip -c /mnt/homeapps/home/aubcxk/pilot-trinity-assemblies_2/Barley_Schizaphis_grammium_trinity/Barley_Schizaphis_grammium-READ1.fastq.gz | wc -l) doesn't match fastool's report of FA records: 3628785  at /home/aubcxk/anaconda2/envs/phyluce/bin/Trinity line 3060 thread 1.
        main::ensure_complete_FQtoFA_conversion("gunzip -c /mnt/homeapps/home/aubcxk/pilot-trinity-assemblies_"..., "/mnt/homeapps/home/aubcxk/pilot-trinity-assemblies_2/Barley_S"...) called at /home/aubcxk/anaconda2/envs/phyluce/bin/Trinity line 2099 thread 1
        main::prep_seqs(ARRAY(0x5632ed3cbe38), "fq", "left", undef) called at /home/aubcxk/anaconda2/envs/phyluce/bin/Trinity line 1310 thread 1
        eval {...} called at /home/aubcxk/anaconda2/envs/phyluce/bin/Trinity line 1310 thread 1
Trinity run failed. Must investigate error above.

**Comment by caioraposo** [comment]
Same as the guy above, after getting the error, my **trinity.log** looks like:

```
Trinity version: v2.1.1
** NOTE: Latest version of Trinity is Trinity-v2.8.4, and can be obtained at:
	https://github.com/trinityrnaseq/trinityrnaseq/releases

Thursday, May 9, 2019: 13:17:06	CMD: java -Xmx64m -XX:ParallelGCThreads=2 -jar /home/caio/miniconda3/envs/phyluce/opt/trinity-2.1.1/util/support_scripts/ExitTester.jar 0
Thursday, May 9, 2019: 13:17:06	CMD: java -Xmx64m -XX:ParallelGCThreads=2 -jar /home/caio/miniconda3/envs/phyluce/opt/trinity-2.1.1/util/support_scripts/ExitTester.jar 1
Thursday, May 9, 2019: 13:17:06	CMD: mkdir -p /home/caio/Desktop/Phyluce/uce_tutorial/trinity-assemblies/alligator_mississippiensis_trinity/chrysalis


----------------------------------------------------------------------------------
-------------- Trinity Phase 1: Clustering of RNA-Seq Reads  ---------------------
----------------------------------------------------------------------------------

Converting input files. (in parallel)Thursday, May 9, 2019: 13:17:06	CMD: gunzip -c /home/caio/Desktop/Phyluce/uce_tutorial/trinity-assemblies/alligator_mississippiensis_trinity/alligator_mississippiensis-READ1.fastq.gz | fastool --illumina-trinity --to-fasta >> left.fa 2> /home/caio/Desktop/Phyluce/uce_tutorial/trinity-assemblies/alligator_mississippiensis_trinity/alligator_mississippiensis-READ1.fastq.gz.readcount 
Thursday, May 9, 2019: 13:17:06	CMD: gunzip -c /home/caio/Desktop/Phyluce/uce_tutorial/trinity-assemblies/alligator_mississippiensis_trinity/alligator_mississippiensis-READ2.fastq.gz | fastool --illumina-trinity --to-fasta >> right.fa 2> /home/caio/Desktop/Phyluce/uce_tutorial/trinity-assemblies/alligator_mississippiensis_trinity/alligator_mississippiensis-READ2.fastq.gz.readcount 

gzip: stdout: Broken pipe
Thread 1 terminated abnormally: Error, counts of reads in FQ: 1705959 (as per gunzip -c /home/caio/Desktop/Phyluce/uce_tutorial/trinity-assemblies/alligator_mississippiensis_trinity/alligator_mississippiensis-READ1.fastq.gz | wc -l) doesn't match fastool's report of FA records: 1575420  at /home/caio/miniconda3/envs/phyluce/bin/Trinity line 3060 thread 1.
	main::ensure_complete_FQtoFA_conversion("gunzip -c /home/caio/Desktop/Phyluce/uce_tutorial/trinity-ass"..., "/home/caio/Desktop/Phyluce/uce_tutorial/trinity-assemblies/al"...) called at /home/caio/miniconda3/envs/phyluce/bin/Trinity line 2099 thread 1
	main::prep_seqs(ARRAY(0x55710ecd5140), "fq", "left", undef) called at /home/caio/miniconda3/envs/phyluce/bin/Trinity line 1310 thread 1
	eval {...} called at /home/caio/miniconda3/envs/phyluce/bin/Trinity line 1310 thread 1
-conversion of 1573403 from FQ to FA format succeeded.
Trinity run failed. Must investigate error above.
```

**Comment by akasmita** [comment]
Hi Dr Brant. 
I am also facing the same issue as 

File "/home/naman/anaconda2/envs/phyluce1.6.5/bin/phyluce_assembly_assemblo_trinity", line 362, in <module>
    main()
  File "/home/naman/anaconda2/envs/phyluce1.6.5/bin/phyluce_assembly_assemblo_trinity", line 341, in main
    cleanup_trinity_assembly_folder(output, log)
  File "/home/naman/anaconda2/envs/phyluce1.6.5/bin/phyluce_assembly_assemblo_trinity", line 283, in cleanup_trinity_assembly_folder
    raise IOError("Neither Trinity.fasta nor trinity.log were found in output.")
IOError: Neither Trinity.fasta nor trinity.log were found in output.

I tried installing earlier version 1.6.1 and 1.5.0 as you advised in this thread but getting an error as 

"Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - phyluce=1.6.1

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page."

I am trying to follow your tutorial with tutorial dataset only. Please advice. 
Thank you.

**Comment by akasmita** [comment]
> Hi Dr Brant.
> I am also facing the same issue as
> 
> File "/home/naman/anaconda2/envs/phyluce1.6.5/bin/phyluce_assembly_assemblo_trinity", line 362, in
> main()
> File "/home/naman/anaconda2/envs/phyluce1.6.5/bin/phyluce_assembly_assemblo_trinity", line 341, in main
> cleanup_trinity_assembly_folder(output, log)
> File "/home/naman/anaconda2/envs/phyluce1.6.5/bin/phyluce_assembly_assemblo_trinity", line 283, in cleanup_trinity_assembly_folder
> raise IOError("Neither Trinity.fasta nor trinity.log were found in output.")
> IOError: Neither Trinity.fasta nor trinity.log were found in output.
> 
> I tried installing earlier version 1.6.1 and 1.5.0 as you advised in this thread but getting an error as
> 
> "Solving environment: failed
> 
> PackagesNotFoundError: The following packages are not available from current channels:
> 
> * phyluce=1.6.1
> 
> Current channels:
> 
> * https://conda.anaconda.org/conda-forge/linux-64
> * https://conda.anaconda.org/conda-forge/noarch
> * https://conda.anaconda.org/bioconda/linux-64
> * https://conda.anaconda.org/bioconda/noarch
> * https://repo.anaconda.com/pkgs/main/linux-64
> * https://repo.anaconda.com/pkgs/main/noarch
> * https://repo.anaconda.com/pkgs/r/linux-64
> * https://repo.anaconda.com/pkgs/r/noarch
> 
> To search for alternate channels that may provide the conda package you're
> looking for, navigate to
> 
> ```
> https://anaconda.org
> ```
> 
> and use the search bar at the top of the page."
> 
> I am trying to follow your tutorial with tutorial dataset only. Please advice.
> Thank you.

Added the binstar.org/faircloth-lab/linux-64, still the same error.

**Comment by brantfaircloth** [comment]
It looks like you have an old installation of phyluce.  please remove that old environment and follow the instructions to setup a new phyluce environment (https://phyluce.readthedocs.io/en/latest/installation.html).

**Comment by akasmita** [comment]
> It looks like you have an old installation of phyluce. please remove that old environment and follow the instructions to setup a new phyluce environment (https://phyluce.readthedocs.io/en/latest/installation.html).

Appreciate the quick reply, sir. Initially, I did install in the same way as its mentioned in the  Tutorial, still, I removed the envs and recreated now, results are the same. It's Phyluce 1.6.8. 

After Trinity failed, I try to assemble using Abyss, which also gave an error but velvet worked.

**Comment by brantfaircloth** [comment]
All of the assembly approaches are working in the software tests on linux and mac os, so I'm not sure what the issue could be.  Have you tried spades?  It's the assembler i would recommend over all others.

**Comment by akasmita** [comment]
Thank you sir, I could run the assembly using SPAdes and Velvet. But got another error in the next step which is 
2020-05-01 05:50:51,759 - phyluce_assembly_match_contigs_to_probes - CRITICAL - Database already exists
2020-05-01 05:50:51,760 - phyluce_assembly_match_contigs_to_probes - CRITICAL - Cannot create database
Traceback (most recent call last):
  File "/home/naman/anaconda2/envs/phyluce/bin/phyluce_assembly_match_contigs_to_probes", line 342, in <module>
    main()
  File "/home/naman/anaconda2/envs/phyluce/bin/phyluce_assembly_match_contigs_to_probes", line 256, in main
    uces
  File "/home/naman/anaconda2/envs/phyluce/bin/phyluce_assembly_match_contigs_to_probes", line 130, in create_probe_database
    raise sqlite3.OperationalError("Cannot create database")
sqlite3.OperationalError: Cannot create database

I went through three threads which troubleshoot them, but no luck. I am running these on the HPC Cluster, with Linux and anaconda2. Does that has any influence.?
