### ISSUE TITLE
Assembly (velvet/abyss) not being able to detect fastq.gz?

### ISSUE THREAD

**Issue by ymilesz** [faircloth-lab/phyluce#125]
I am running the tutorial on our cluster, and at the assembly step I am getting the following error:

Traceback (most recent call last):
  File "/apps/phyluce/20180727/bin/phyluce_assembly_assemblo_velvet", line 259, in <module>
    main()
  File "/apps/phyluce/20180727/bin/phyluce_assembly_assemblo_velvet", line 240, in main
    reads = get_input_files(dir, args.subfolder, log)
  File "/apps/phyluce/20180727/lib/python2.7/site-packages/phyluce/raw_reads.py", line 92, in get_input_files
    raise IOError("There are not appropriate files in {}".format(dir))
IOError: There are not appropriate files in /ufrc/lucky/yuanmeng.zhang/uce-tutorial/clean-fastq/alligator_mississippiensis/split-adapter-quality-trimmed

Even though I have singleton.fastq.gz, READ1.fastq.gz, and READ2.fastq.gz in the split-adapter-quality-trimmed folder. I tried using both velvet and abyss and I get the same results.

**Comment by ymilesz** [comment]
Ah okay so not creating subfolder was the key. Seems to be working now.
