### ISSUE TITLE
sre_constants.error: nothing to repeat

### ISSUE THREAD

**Issue by ahs29506** [faircloth-lab/phyluce#134]
Hi Dr. Faircloth,

I do not know what happened, all of a sudden the illumiprocessor stopped working and I received this error message. Here below is the entire output, also my conda list illumiprocessor shows the 2.0.8 version below you can see it says 2.0.6 when the program runs.

illumiprocessor --input raw2/ --output clean-fastq --config illumiprocessor.conf --trimmomatic /home/charles/anaconda2/envs/illumiprocessor/jar/trimmomatic.jar --r1-pattern *_R1 --r2-pattern *_R2
2018-11-06 23:00:56,398 - illumiprocessor - INFO - ==================== Starting illumiprocessor ===================
2018-11-06 23:00:56,399 - illumiprocessor - INFO - Version: 2.0.6
2018-11-06 23:00:56,399 - illumiprocessor - INFO - Argument --config: illumiprocessor.conf
2018-11-06 23:00:56,399 - illumiprocessor - INFO - Argument --cores: 1
2018-11-06 23:00:56,400 - illumiprocessor - INFO - Argument --input: /home/charles/Dropbox/Actual/raw2
2018-11-06 23:00:56,400 - illumiprocessor - INFO - Argument --log_path: None
2018-11-06 23:00:56,400 - illumiprocessor - INFO - Argument --min_len: 40
2018-11-06 23:00:56,401 - illumiprocessor - INFO - Argument --no_merge: False
2018-11-06 23:00:56,401 - illumiprocessor - INFO - Argument --output: /home/charles/Dropbox/Actual/clean-fastq
2018-11-06 23:00:56,401 - illumiprocessor - INFO - Argument --phred: phred33
2018-11-06 23:00:56,401 - illumiprocessor - INFO - Argument --r1_pattern: *_R1
2018-11-06 23:00:56,401 - illumiprocessor - INFO - Argument --r2_pattern: *_R2
2018-11-06 23:00:56,402 - illumiprocessor - INFO - Argument --se: False
2018-11-06 23:00:56,402 - illumiprocessor - INFO - Argument --trimmomatic: /home/charles/anaconda2/envs/illumiprocessor/jar/trimmomatic.jar
2018-11-06 23:00:56,403 - illumiprocessor - INFO - Argument --verbosity: INFO
Traceback (most recent call last):
  File "/home/charles/anaconda2/envs/illumiprocessor/bin/illumiprocessor", line 17, in <module>
    sys.exit(main())
  File "/home/charles/anaconda2/envs/illumiprocessor/lib/python2.7/site-packages/illumiprocessor/cli/main.py", line 131, in main
    main(args)
  File "/home/charles/anaconda2/envs/illumiprocessor/lib/python2.7/site-packages/illumiprocessor/main.py", line 34, in main
    reads.append(core.SequenceData(args, conf, start_name, end_name))
  File "/home/charles/anaconda2/envs/illumiprocessor/lib/python2.7/site-packages/illumiprocessor/core.py", line 86, in __init__
    self._get_read_data()
  File "/home/charles/anaconda2/envs/illumiprocessor/lib/python2.7/site-packages/illumiprocessor/core.py", line 97, in _get_read_data
    if re.search(self.r1_pattern.format(self.start_name), name):
  File "/home/charles/anaconda2/envs/illumiprocessor/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
  File "/home/charles/anaconda2/envs/illumiprocessor/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: nothing to repeat

**Comment by brantfaircloth** [comment]
It looks like the regular expression pattern that you are passing is not correct (you need to pass a valid regular expression to match your R1 and R2 file names).

**Comment by ahs29506** [comment]
Hi Dr.Faircloth,

Thank you very much for the assistance, I figured out the problem. The problem is that I did not put '.' in front of * in the --r1-pattern *_R1 --r2-pattern *_R2 line. When changed to --r1-pattern ._R1 --r2-pattern .*_R2 things work just fine.
