### ISSUE TITLE
jellyfish: not found

### ISSUE THREAD

**Issue by lucper** [faircloth-lab/phyluce#137]
Hello, I have installed Phyluce from Bioconda and when I run `phyluce_assembly_assemblo_trinity` I receive the following error, probably due to the Trinity installation. Is there any previous configuration I need to set?

```
Traceback (most recent call last):
  File "/home/lucas/miniconda3/envs/phyluce/bin/phyluce_assembly_assemblo_trinity", line 362, in <module>
    main()
  File "/home/lucas/miniconda3/envs/phyluce/bin/phyluce_assembly_assemblo_trinity", line 341, in main
    cleanup_trinity_assembly_folder(output, log)
  File "/home/lucas/miniconda3/envs/phyluce/bin/phyluce_assembly_assemblo_trinity", line 283, in cleanup_trinity_assembly_folder
    raise IOError("Neither Trinity.fasta nor trinity.log were found in output.")
IOError: Neither Trinity.fasta nor trinity.log were found in output.
```

Here is the content from **trinity.log**, the Jellyfish module seems to be not installed or not being found.

```
Trinity version: v2.1.1
** NOTE: Latest version of Trinity is Trinity-v2.8.4, and can be obtained at:
	https://github.com/trinityrnaseq/trinityrnaseq/releases

Monday, November 12, 2018: 12:51:34	CMD: java -Xmx64m -XX:ParallelGCThreads=2 -jar /home/lucas/miniconda3/envs/phyluce/opt/trinity-2.1.1/util/support_scripts/ExitTester.jar 0
Monday, November 12, 2018: 12:51:34	CMD: java -Xmx64m -XX:ParallelGCThreads=2 -jar /home/lucas/miniconda3/envs/phyluce/opt/trinity-2.1.1/util/support_scripts/ExitTester.jar 1
Monday, November 12, 2018: 12:51:34	CMD: mkdir -p /home/lucas/Documents/uceasy/data/trinity_assemblies/sample2_trinity/chrysalis


----------------------------------------------------------------------------------
-------------- Trinity Phase 1: Clustering of RNA-Seq Reads  ---------------------
----------------------------------------------------------------------------------

Converting input files. (in parallel)Monday, November 12, 2018: 12:51:35	CMD: gunzip -c /home/lucas/Documents/uceasy/data/trinity_assemblies/sample2_trinity/sample2-READ1.fastq.gz | fastool --illumina-trinity --to-fasta >> left.fa 2> /home/lucas/Documents/uceasy/data/trinity_assemblies/sample2_trinity/sample2-READ1.fastq.gz.readcount 
Monday, November 12, 2018: 12:51:35	CMD: gunzip -c /home/lucas/Documents/uceasy/data/trinity_assemblies/sample2_trinity/sample2-READ2.fastq.gz | fastool --illumina-trinity --to-fasta >> right.fa 2> /home/lucas/Documents/uceasy/data/trinity_assemblies/sample2_trinity/sample2-READ2.fastq.gz.readcount 
-conversion of 1984 from FQ to FA format succeeded.
-conversion of 1995 from FQ to FA format succeeded.
Monday, November 12, 2018: 12:51:35	CMD: touch left.fa.ok right.fa.ok
Monday, November 12, 2018: 12:51:35	CMD: cat left.fa right.fa > both.fa
Monday, November 12, 2018: 12:51:35	CMD: touch both.fa.ok
-------------------------------------------
----------- Jellyfish  --------------------
-- (building a k-mer catalog from reads) --
-------------------------------------------

* Running CMD: jellyfish count -t 2 -m 25 -s 1226985198  --canonical  both.fa
sh: 1: jellyfish: not found
Trinity run failed. Must investigate error above.
```

**Comment by lucper** [comment]
Thank you! Everything has worked fine until now!
