### ISSUE TITLE
Add missing data designators

### ISSUE THREAD

**Issue by ahs29506** [faircloth-lab/phyluce#139]
Hi Dr.Faircloth,
I ran into some problems while trying to add missing data designators. 
> Traceback (most recent call last):
  File "/home/charles/anaconda2/envs/phyluce/bin/phyluce_align_add_missing_data_designators", line 245, in <module>
    main()
  File "/home/charles/anaconda2/envs/phyluce/bin/phyluce_align_add_missing_data_designators", line 230, in main
    results = pool.map(add_designators, work)
  File "/home/charles/anaconda2/envs/phyluce/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/charles/anaconda2/envs/phyluce/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
ValueError: list.remove(x): x not in list

Here below are my input files, I switched the data type so I can put them on here.

.conf
[dataset_2.txt](https://github.com/faircloth-lab/phyluce/files/2574083/dataset_2.txt)
.incomplete
[dataset2.txt](https://github.com/faircloth-lab/phyluce/files/2574085/dataset2.txt)

**Comment by brantfaircloth** [comment]
you should simply be able to skip this step.

**Comment by ahs29506** [comment]
Do I go straight to concatenate for RAxML?
