### ISSUE TITLE
phyluce_align_get_smilogram_from_alignments

### ISSUE THREAD

**Issue by mcfaddenlab** [faircloth-lab/phyluce#144]
hi brant,

trying to run the smilogram script, and getting this error. any idea how to fix it? thanks!

phyluce_align_get_smilogram_from_alignments --alignments mafft-nexus-edge-trimmed --output smilogram --input-format nexus --cores 12 --smilogram
Traceback (most recent call last):
  File "/data/mcfadden/aquattrini/PROGRAMS/anaconda2/bin/phyluce_align_get_smilogram_from_alignments", line 377, in <module>
    main()
  File "/data/mcfadden/aquattrini/PROGRAMS/anaconda2/bin/phyluce_align_get_smilogram_from_alignments", line 248, in main
    work = [(args, f) for f in get_files(args.input, args.input_format)]
AttributeError: 'Namespace' object has no attribute 'input

**Comment by mcfaddenlab** [comment]
I realized that i had an old version of the script~ i updated and all is ok.
