### ISSUE TITLE
phyluce_snp_bwa_multiple_align issue

### ISSUE THREAD

**Issue by mprebus** [faircloth-lab/phyluce#150]
I'm attempting to work through the UCE phasing protocol, but I've run into an error with the ConfigParser:

2019-03-05 12:51:23,387 - phyluce_snp_bwa_multiple_align - INFO - ============ Starting phyluce_snp_bwa_multiple_align ============
2019-03-05 12:51:23,387 - phyluce_snp_bwa_multiple_align - INFO - Version: git fatal: Not a git repository: '/home/mborowiec/phyluce-master/.git'
2019-03-05 12:51:23,387 - phyluce_snp_bwa_multiple_align - INFO - Argument --config: /home/mborowiec/Matt/temno-salvini-group/phasing.conf
2019-03-05 12:51:23,388 - phyluce_snp_bwa_multiple_align - INFO - Argument --cores: 9
2019-03-05 12:51:23,388 - phyluce_snp_bwa_multiple_align - INFO - Argument --log_path: /home/mborowiec/Matt/temno-salvini-group
2019-03-05 12:51:23,388 - phyluce_snp_bwa_multiple_align - INFO - Argument --mem: True
2019-03-05 12:51:23,388 - phyluce_snp_bwa_multiple_align - INFO - Argument --no_remove_duplicates: False
2019-03-05 12:51:23,388 - phyluce_snp_bwa_multiple_align - INFO - Argument --output: /home/mborowiec/Matt/temno-salvini-group/multialign-bams
2019-03-05 12:51:23,388 - phyluce_snp_bwa_multiple_align - INFO - Argument --subfolder: 
2019-03-05 12:51:23,389 - phyluce_snp_bwa_multiple_align - INFO - Argument --verbosity: INFO
2019-03-05 12:51:23,389 - phyluce_snp_bwa_multiple_align - INFO - ============ Starting phyluce_snp_bwa_multiple_align ============
2019-03-05 12:51:23,391 - phyluce_snp_bwa_multiple_align - INFO - Getting input filenames and creating output directories
2019-03-05 12:51:23,391 - phyluce_snp_bwa_multiple_align - INFO - Need to create BWA index file for reference
2019-03-05 12:51:23,391 - phyluce_snp_bwa_multiple_align - INFO - Running bwa indexing against /home/mborowiec/Matt/temno-salvini-group/salvini_group-incomplete/mafft-nexus-edge-trimmed-exploded/Temnothorax_aztecus_BZ_P192.fasta
Traceback (most recent call last):
  File "/home/mborowiec/phyluce-master/bin/snps/phyluce_snp_bwa_multiple_align", line 193, in <module>
    main()
  File "/home/mborowiec/phyluce-master/bin/snps/phyluce_snp_bwa_multiple_align", line 136, in main
    references_individuals = get_input_data(log, conf, args.output)
  File "/home/mborowiec/phyluce-master/bin/snps/phyluce_snp_bwa_multiple_align", line 109, in get_input_data
    bwa.create_index_files(log, reference[1])
  File "/home/mborowiec/phyluce-master/phyluce/bwa.py", line 27, in create_index_files
    cmd = [get_user_path("binaries", "bwa"), "index", reference]
  File "/home/mborowiec/phyluce-master/phyluce/pth.py", line 29, in get_user_path
    pth = config.get(program, binary)
  File "/home/mborowiec/anaconda2/envs/Py27/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'binaries'

**Comment by brantfaircloth** [comment]
Looks like this is an old git repository.  Please install phyluce using conda as described in the manual - that should fix this issue.

**Comment by mprebus** [comment]
Thanks! This fixed the issue.
