### ISSUE TITLE
lastz fails

### ISSUE THREAD

**Issue by mchj74** [faircloth-lab/phyluce#152]
Hi Brant. I am trying to use phyluce_assembly_match_contigs_to_probes  but it gives the following error: 

phyluce_assembly_match_contigs_to_probes --contigs Trinity-fasta-files/ --probes hymenoptera-v2-ANT-SPECIFIC-uce-baits.fasta.txt --output uce-search-results --log-path log

2019-03-29 17:13:22,810 - phyluce_assembly_match_contigs_to_probes - INFO - ======= Starting phyluce_assembly_match_contigs_to_probes =======
2019-03-29 17:13:22,810 - phyluce_assembly_match_contigs_to_probes - INFO - Version: 1.5.0
2019-03-29 17:13:22,810 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --contigs: /flush3/cha737/testing/Trinity-fasta-files
2019-03-29 17:13:22,810 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --dupefile: None
2019-03-29 17:13:22,810 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --keep_duplicates: None
2019-03-29 17:13:22,810 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --log_path: /flush3/cha737/testing/log
2019-03-29 17:13:22,811 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --min_coverage: 80
2019-03-29 17:13:22,811 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --min_identity: 80
2019-03-29 17:13:22,811 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --output: /flush3/cha737/testing/uce-search-results
2019-03-29 17:13:22,811 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --probes: /flush3/cha737/testing/hymenoptera-v2-ANT-SPECIFIC-uce-baits.fasta.txt
2019-03-29 17:13:22,811 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --regex: ^(uce-\d+)(?:_p\d+.*)
2019-03-29 17:13:22,811 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --verbosity: INFO
2019-03-29 17:13:23,042 - phyluce_assembly_match_contigs_to_probes - INFO - Creating the UCE-match database
2019-03-29 17:13:23,091 - phyluce_assembly_match_contigs_to_probes - INFO - Processing contig data
2019-03-29 17:13:23,091 - phyluce_assembly_match_contigs_to_probes - INFO - -----------------------------------------------------------------
Traceback (most recent call last):
  File "/apps/phyluce/1.6.0/bin/phyluce_assembly_match_contigs_to_probes", line 342, in <module>
    main()
  File "/apps/phyluce/1.6.0/bin/phyluce_assembly_match_contigs_to_probes", line 291, in main
    contig_name = get_contig_name(lz.name1)
  File "/apps/phyluce/1.6.0/bin/phyluce_assembly_match_contigs_to_probes", line 229, in get_contig_name
    return match.groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'

It creates the output directory with two files in it, it creates the .trinity.lastz file for the first sample but apparently it gets stuck at some point (do not know where) when trying to match headers. 
Can you help to fix that issue?
tnx

**Comment by brantfaircloth** [comment]
howdy. what were these assemblies from?  and, can you send me the fasta header of 1 or 2? likely that whatever program just updated headers and phyluce needs to know about that.

**Comment by mchj74** [comment]
howdy.they are from a directory called Trinity-fasta-files 
yes, here they are:
>TRINITY_DN347_c0_g1_i1 len=213 path=[191:0-212] [-1, 191, -2]
>TRINITY_DN327_c0_g1_i1 len=351 path=[329:0-350] [-1, 329, -2]
could you help to fix its problem?

**Comment by brantfaircloth** [comment]
Can you make sure in `$HOME/.phyluce.conf` you have:
```
[headers]
trinity:comp\d+_c\d+_seq\d+|c\d+_g\d+_i\d+|TR\d+\|c\d+_g\d+_i\d+|TRINITY_DN\d+_c\d+_g\d+_i\d+
velvet:node_\d+
abyss:node_\d+
idba:contig-\d+_\d+
spades:NODE_\d+_length_\d+_cov_\d+.\d+
```
This is what currently comes w/ phyluce by default and should be working against the headers that you sent (see last part of the `trinity` entry, above).  If you have something else in the '[header]' section of this file, just delete what's there and enter the above.

**Comment by mchj74** [comment]
Yes, that fixed the problem!

**Comment by mchj74** [comment]
Thank you.
