### ISSUE TITLE
phyluce_align_seqcap_align returns error

### ISSUE THREAD

**Issue by mchj74** [faircloth-lab/phyluce#156]
Hi Brant,

In taxon-set/all, I run  phyluce_align_seqcap_align --fasta all-taxa-incomplete.fasta --output mafft-nexus-edge-trimmed --taxa 10 --aligner mafft --cores 12 --incomplete-matrix --log-path log

and it returns the following:
2019-04-08 17:32:42,050 - phyluce_align_seqcap_align - WARNING - DROPPED locus uce-11994. Too few taxa (N < 3).
2019-04-08 17:32:42,063 - phyluce_align_seqcap_align - INFO - Aligning with MAFFT
2019-04-08 17:32:42,065 - phyluce_align_seqcap_align - INFO - Alignment begins.'X' indicates dropped alignments (these are reported after alignment)
Traceback (most recent call last):
  File "/apps/phyluce/1.6.0/bin/phyluce_align_seqcap_align", line 255, in <module>
    main(args)
  File "/apps/phyluce/1.6.0/bin/phyluce_align_seqcap_align", line 232, in main
    alignments = pool.map(align, params)
  File "/apps/python/2.7.13/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/apps/python/2.7.13/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
OSError: [Errno 2] No such file or directory

and here is a few lines of log file:
2019-04-08 17:11:20,722 - phyluce_align_seqcap_align - WARNING - DROPPED locus uce-11995. Too few taxa (N < 3).
2019-04-08 17:11:20,722 - phyluce_align_seqcap_align - WARNING - DROPPED locus uce-11994. Too few taxa (N < 3).
2019-04-08 17:11:20,737 - phyluce_align_seqcap_align - INFO - Aligning with MAFFT
2019-04-08 17:11:20,738 - phyluce_align_seqcap_align - INFO - Alignment begins.'X' indicates dropped alignments (these are reported after alignment)

can you help how to fix this issue?
Thanks

**Comment by brantfaircloth** [comment]
Is it dropping all of the loci because they all have fewer than 3 tips?  It's not clear to me from the above how many lines are in the log file and/or how many loci you are attempting to input to `phyluce_align_seqcap_align`.  Trimming could also be causing an issue - you could try to pass the `--no-trim` flag and see what happens, as well.

**Comment by mchj74** [comment]
Hi Brant,

Sorry for slow reply.
Yes, I think so. It says too few taxa N<3
I tried to pass the --no-trim flag, it is not fixed.
log file line number is 3892 Do I need to send the log file as well?
and from "all-taxa-incomplete.fasta" file, I think I am trying to input 2163 loci into phyluce_align_seqcap_align.

could you give me hint how to move forward at this point?

Thank you,
Mahin
