### ISSUE TITLE
phyluce_assembly_match_contigs_to_probes gives error AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by claudiavaga** [faircloth-lab/phyluce#171]
Hi everyone,

I am trying to use the command phyluce_assembly_match_contigs_to_probes but I am getting this error:

2019-10-02 16:22:35,792 - phyluce_assembly_match_contigs_to_probes - INFO - ======= Starting phyluce_assembly_match_contigs_to_probes =======
2019-10-02 16:22:35,793 - phyluce_assembly_match_contigs_to_probes - INFO - Version: git fatal: not a git repository: '/home/claudiavaga/miniconda2/envs/phyluce/lib/python2.7/site-packages/.git'
2019-10-02 16:22:35,793 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --contigs: /home/claudiavaga/capture/assemblies/IGS050
2019-10-02 16:22:35,794 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --dupefile: None
2019-10-02 16:22:35,795 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --keep_duplicates: None
2019-10-02 16:22:35,795 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --log_path: None
2019-10-02 16:22:35,795 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --min_coverage: 80
2019-10-02 16:22:35,796 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --min_identity: 80
2019-10-02 16:22:35,796 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --output: /home/claudiavaga/capture/uce-search-results-IGS050
2019-10-02 16:22:35,797 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --probes: /home/claudiavaga/capture/baits_designed_filtered.fas
2019-10-02 16:22:35,797 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --regex: ^(uce-\d+)(?:_p\d+.*)
2019-10-02 16:22:35,797 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --verbosity: INFO
Traceback (most recent call last):
  File "/home/claudiavaga/miniconda2/envs/phyluce/bin/phyluce_assembly_match_contigs_to_probes", line 342, in <module>
    main()
  File "/home/claudiavaga/miniconda2/envs/phyluce/bin/phyluce_assembly_match_contigs_to_probes", line 245, in main
    uces = set(new_get_probe_name(seq.id, regex) for seq in SeqIO.parse(open(args.probes, 'rU'), 'fasta'))
  File "/home/claudiavaga/miniconda2/envs/phyluce/bin/phyluce_assembly_match_contigs_to_probes", line 245, in <genexpr>
    uces = set(new_get_probe_name(seq.id, regex) for seq in SeqIO.parse(open(args.probes, 'rU'), 'fasta'))
  File "/home/claudiavaga/miniconda2/envs/phyluce/bin/phyluce_assembly_match_contigs_to_probes", line 234, in new_get_probe_name
    return match.groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
[baits_designed.txt](https://github.com/faircloth-lab/phyluce/files/3682998/baits_designed.txt)

I am attaching the probes set that I am trying to use since it seems like the problem are the probes.
Someone know what is going on?

Thank you!
Claudia

**Comment by brantfaircloth** [comment]
The baits you are using do not follow the naming scheme that is expected by phyluce.  you can modify the naming scheme using the options for `phyluce_assembly_match_contigs_to_probes` or rename your baits to follow the expected naming scheme (e.g. see https://github.com/faircloth-lab/uce-probe-sets/blob/master/uce-5k-probe-set/uce-5k-probes.fasta).

**Comment by claudiavaga** [comment]
Thank you Brant for your fast answer! I will try that.
