### ISSUE TITLE
phyluce_assembly_get_match_counts 

### ISSUE THREAD

**Issue by lixiaoyi-12** [faircloth-lab/phyluce#174]
I'm a new learning of phyluce, and when I run the phyluce_assembly_get_match_counts script, there's an error shows 
TypeError: object of type 'NoneType' has no len()
I'm quite confused of the problem. Is it because there's something wrong with my configuration file? Cause I just type the taxa's name and the name of their fasta file in it.
Hope to receive a suggestion.

**Comment by lixiaoyi-12** [comment]
The whole description of the bug is:
Traceback (most recent call last):
  File "/usr/local/Anaconda2_5.3/bin/phyluce_assembly_get_match_counts", line 351, in <module>
    main()
  File "/usr/local/Anaconda2_5.3/bin/phyluce_assembly_get_match_counts", line 329, in main
    len(organisms),
TypeError: object of type 'NoneType' has no len()
