### ISSUE TITLE
phyluce_assembly_get_trinity_coverage gatk issue

### ISSUE THREAD

**Issue by mprebus** [faircloth-lab/phyluce#179]
I have been getting the following error when trying to run the phyluce_assembly_get_trinity_coverage script:

2019-12-10 11:01:00,484 - phyluce_assembly_get_trinity_coverage - INFO - ========= Starting phyluce_assembly_get_trinity_coverage ========
2019-12-10 11:01:00,484 - phyluce_assembly_get_trinity_coverage - INFO - Version: git fatal: Not a git repository: '/home/mborowiec/phyluce-master/.git'
2019-12-10 11:01:00,484 - phyluce_assembly_get_trinity_coverage - INFO - Argument --assembler: trinity
2019-12-10 11:01:00,484 - phyluce_assembly_get_trinity_coverage - INFO - Argument --assemblies: /home/mborowiec/Matt/16173R/trinity-assembly
2019-12-10 11:01:00,484 - phyluce_assembly_get_trinity_coverage - INFO - Argument --assemblo_config: /home/mborowiec/Matt/16173R/trinity.conf
2019-12-10 11:01:00,484 - phyluce_assembly_get_trinity_coverage - INFO - Argument --bwa_mem: False
2019-12-10 11:01:00,484 - phyluce_assembly_get_trinity_coverage - INFO - Argument --clean: False
2019-12-10 11:01:00,484 - phyluce_assembly_get_trinity_coverage - INFO - Argument --cores: 9
2019-12-10 11:01:00,484 - phyluce_assembly_get_trinity_coverage - INFO - Argument --log_path: /home/mborowiec/Matt/16173R
2019-12-10 11:01:00,485 - phyluce_assembly_get_trinity_coverage - INFO - Argument --subfolder: raw-reads
2019-12-10 11:01:00,485 - phyluce_assembly_get_trinity_coverage - INFO - Argument --trim: False
2019-12-10 11:01:00,485 - phyluce_assembly_get_trinity_coverage - INFO - Argument --verbosity: INFO
2019-12-10 11:01:00,485 - phyluce_assembly_get_trinity_coverage - INFO - Getting input filenames
2019-12-10 11:01:00,487 - phyluce_assembly_get_trinity_coverage - INFO - ---------- Processing Leptothorax_wilsoni_P378_trinity ----------
2019-12-10 11:01:00,487 - phyluce_assembly_get_trinity_coverage - INFO - Finding fastq/fasta files
2019-12-10 11:01:00,489 - phyluce_assembly_get_trinity_coverage - INFO - File type is fastq
2019-12-10 11:01:00,490 - phyluce_assembly_get_trinity_coverage - INFO - Running bwa indexing against /home/mborowiec/Matt/16173R/trinity-assembly/Leptothorax_wilsoni_P378_trinity/contigs.fasta
2019-12-10 11:01:04,568 - phyluce_assembly_get_trinity_coverage - INFO - Indexing fasta for Leptothorax_wilsoni_P378_trinity
2019-12-10 11:01:04,693 - phyluce_assembly_get_trinity_coverage - INFO - Creating FASTA dict for Leptothorax_wilsoni_P378_trinity
2019-12-10 11:01:05,465 - phyluce_assembly_get_trinity_coverage - INFO - Creating read index file for Leptothorax_wilsoni_P378-READ1.fastq.gz
2019-12-10 11:01:20,633 - phyluce_assembly_get_trinity_coverage - INFO - Creating read index file for Leptothorax_wilsoni_P378-READ2.fastq.gz
2019-12-10 11:01:37,741 - phyluce_assembly_get_trinity_coverage - INFO - Building BAM for Leptothorax_wilsoni_P378_trinity
2019-12-10 11:02:12,203 - phyluce_assembly_get_trinity_coverage - INFO - Cleaning BAM for Leptothorax_wilsoni_P378_trinity
2019-12-10 11:02:31,722 - phyluce_assembly_get_trinity_coverage - INFO - Adding RG header to BAM for Leptothorax_wilsoni_P378_trinity
2019-12-10 11:03:09,891 - phyluce_assembly_get_trinity_coverage - INFO - Marking read duplicates from BAM for Leptothorax_wilsoni_P378_trinity
2019-12-10 11:03:40,379 - phyluce_assembly_get_trinity_coverage - INFO - Indexing BAM for Leptothorax_wilsoni_P378_trinity
2019-12-10 11:03:42,107 - phyluce_assembly_get_trinity_coverage - INFO - Computing coverage with GATK for Leptothorax_wilsoni_P378_trinity
2019-12-10 11:03:42,867 - phyluce_assembly_get_trinity_coverage - INFO - Screening contigs for coverage
Traceback (most recent call last):
  File "/home/mborowiec/anaconda2/envs/phyluce/bin/phyluce_assembly_get_trinity_coverage", line 238, in <module>
    main()
  File "/home/mborowiec/anaconda2/envs/phyluce/bin/phyluce_assembly_get_trinity_coverage", line 228, in main
    overall_contigs = gatk.get_untrimmed_coverage_from_output(log, sample, assembly_pth, coverage, args.assembler)
  File "/home/mborowiec/phyluce-master/phyluce/gatk.py", line 216, in get_untrimmed_coverage_from_output
    with open(coverage, 'rU') as infile:
IOError: [Errno 2] No such file or directory: '/home/mborowiec/Matt/16173R/trinity-assembly/Leptothorax_wilsoni_P378_trinity/Leptothorax_wilsoni_P378_trinity-coverage'

The GATK-coverage-out.log file contains the following:

##### ERROR stack trace 
java.lang.ExceptionInInitializerError
	at org.broadinstitute.sting.gatk.GenomeAnalysisEngine.<init>(GenomeAnalysisEngine.java:160)
	at org.broadinstitute.sting.gatk.CommandLineExecutable.<init>(CommandLineExecutable.java:53)
	at org.broadinstitute.sting.gatk.CommandLineGATK.<init>(CommandLineGATK.java:54)
	at org.broadinstitute.sting.gatk.CommandLineGATK.main(CommandLineGATK.java:90)
Caused by: java.lang.NullPointerException
	at org.reflections.Reflections.scan(Reflections.java:220)
	at org.reflections.Reflections.scan(Reflections.java:166)
	at org.reflections.Reflections.<init>(Reflections.java:94)
	at org.broadinstitute.sting.utils.classloader.PluginManager.<clinit>(PluginManager.java:77)
	... 4 more
##### ERROR ------------------------------------------------------------------------------------------

**Comment by brantfaircloth** [comment]
have you checked compatibility between java and this version of GATK by any chance?  The error appears to be in GATK and not in phyluce...

**Comment by mprebus** [comment]
I was able to resolve this issue by using GATK v3.8 with java 8. Thanks very much!
