### ISSUE TITLE
format_nexus_files_for_raxml.py failing during output write

### ISSUE THREAD

**Issue by JosieReinhardt** [faircloth-lab/phyluce#18]
Getting the following error when running format_nexus_files_for_raxml.py on a directory of nexus alignments:

> format_nexus_files_for_raxml.py --alignments ./trim/ --output ./woooo 
2014-10-06 12:23:21,907 - format_nexus_files_for_raxml - INFO - ============= Starting format_nexus_files_for_raxml =============
2014-10-06 12:23:21,908 - format_nexus_files_for_raxml - INFO - Version: 2.0.0
2014-10-06 12:23:21,908 - format_nexus_files_for_raxml - INFO - Argument --alignments: /N/dc2/scratch/joserein/orthograph/allfly/test/all/trim
2014-10-06 12:23:21,908 - format_nexus_files_for_raxml - INFO - Argument --charsets: False
2014-10-06 12:23:21,908 - format_nexus_files_for_raxml - INFO - Argument --log_path: None
2014-10-06 12:23:21,909 - format_nexus_files_for_raxml - INFO - Argument --nexus: False
2014-10-06 12:23:21,909 - format_nexus_files_for_raxml - INFO - Argument --output: /mypath/woooo
2014-10-06 12:23:21,909 - format_nexus_files_for_raxml - INFO - Argument --verbosity: INFO
2014-10-06 12:23:21,909 - format_nexus_files_for_raxml - INFO - Reading input alignments in NEXUS format
2014-10-06 12:23:21,910 - format_nexus_files_for_raxml - INFO - Concatenating files
2014-10-06 12:23:21,910 - format_nexus_files_for_raxml - INFO - Writing concatenated PHYLIP alignment to /mypath/woooo/trim.phylip
Traceback (most recent call last):
  File "~/anaconda/bin/format_nexus_files_for_raxml.py", line 108, in <module>
    main()
  File "~/anaconda/bin/format_nexus_files_for_raxml.py", line 93, in main
    concatenated.export_phylip(concat_file)
AttributeError: 'NoneType' object has no attribute 'export_phylip'

Thoughts?

**Comment by brantfaircloth** [comment]
HI Josie, 

not sure what caused this problem.  I have just updated to code (pretty substantially), so I am hoping this fixed your issue.  You can upgrade the code (if you installed using conda) with:

    conda update phyluce

And if this does get it, try:

    conda remove phylue
    conda install phyluce

**Comment by JosieReinhardt** [comment]
thanks!  Almost forgot about this but it may still be helpful, I appreciate
it.
