### ISSUE TITLE
phyluce_snp_screen_phased_alignments error sequence not the same length?

### ISSUE THREAD

**Issue by ymilesz** [faircloth-lab/phyluce#187]
Hi Brant,

  I've successfully completed the phasing UCE tutorial II, and now I want to pull out just SNPs from the phased reads, which I assume uses phyluce_snp_screen_phased_alignments?

  However I am getting this error from the tutorial dataset:

[yuanmeng.zhang@login1 all]$ phyluce_snp_screen_phased_alignments --alignments ./multialign-bams-phased-reads/fastas --input-format fasta --output-format phylip --random --output SNP

2020-02-23 01:55:15,429 - phyluce_snp_screen_phased_alignments - INFO - ========= Starting phyluce_snp_screen_phased_alignments =========
2020-02-23 01:55:15,429 - phyluce_snp_screen_phased_alignments - INFO - Version: git fatal: Not a git repository: '/apps/phyluce/20191015/lib/python2.7/site-packages/.git'
2020-02-23 01:55:15,429 - phyluce_snp_screen_phased_alignments - INFO - Argument --alignments: /ufrc/lucky/yuanmeng.zhang/tutorial/taxon-sets/all/multialign-bams-phased-reads
2020-02-23 01:55:15,429 - phyluce_snp_screen_phased_alignments - INFO - Argument --cores: 1
2020-02-23 01:55:15,430 - phyluce_snp_screen_phased_alignments - INFO - Argument --include_missing: False
2020-02-23 01:55:15,430 - phyluce_snp_screen_phased_alignments - INFO - Argument --input_format: fasta
2020-02-23 01:55:15,430 - phyluce_snp_screen_phased_alignments - INFO - Argument --log_path: None
2020-02-23 01:55:15,430 - phyluce_snp_screen_phased_alignments - INFO - Argument --numerical_encoding: False
2020-02-23 01:55:15,430 - phyluce_snp_screen_phased_alignments - INFO - Argument --output: /ufrc/lucky/yuanmeng.zhang/tutorial/taxon-sets/all/SNP
2020-02-23 01:55:15,430 - phyluce_snp_screen_phased_alignments - INFO - Argument --output_format: phylip
2020-02-23 01:55:15,430 - phyluce_snp_screen_phased_alignments - INFO - Argument --random: True
2020-02-23 01:55:15,430 - phyluce_snp_screen_phased_alignments - INFO - Argument --verbosity: INFO
2020-02-23 01:55:15,430 - phyluce_snp_screen_phased_alignments - INFO - Getting alignment files
2020-02-23 01:55:15,432 - phyluce_snp_screen_phased_alignments - INFO - Creating phased, SNP-only alignments using 1 cores
ProcessingTraceback (most recent call last):
  File "/apps/phyluce/20191015/bin/phyluce_snp_screen_phased_alignments", line 221, in <module>
    main()
  File "/apps/phyluce/20191015/bin/phyluce_snp_screen_phased_alignments", line 209, in main
    results = map(worker, work)
  File "/apps/phyluce/20191015/bin/phyluce_snp_screen_phased_alignments", line 119, in worker
    align = AlignIO.read(aln, args.input_format)
  File "/apps/phyluce/20191015/lib/python2.7/site-packages/Bio/AlignIO/__init__.py", line 447, in read
    first = next(iterator)
  File "/apps/phyluce/20191015/lib/python2.7/site-packages/Bio/AlignIO/__init__.py", line 394, in parse
    for a in i:
  File "/apps/phyluce/20191015/lib/python2.7/site-packages/Bio/AlignIO/__init__.py", line 292, in _SeqIO_to_alignment_iterator
    yield MultipleSeqAlignment(records, alphabet)
  File "/apps/phyluce/20191015/lib/python2.7/site-packages/Bio/Align/__init__.py", line 169, in __init__
    self.extend(records)
  File "/apps/phyluce/20191015/lib/python2.7/site-packages/Bio/Align/__init__.py", line 530, in extend
    self._append(rec, expected_length)
  File "/apps/phyluce/20191015/lib/python2.7/site-packages/Bio/Align/__init__.py", line 593, in _append
    raise ValueError("Sequences must all be the same length")
ValueError: Sequences must all be the same length

 The log file isn't showing any errors, so I am not sure what's going on.

Thanks,

Miles

**Comment by ymilesz** [comment]
Oh I think it is a missing designator error
