### ISSUE TITLE
phyluce_assembly_get_match_counts 

### ISSUE THREAD

**Issue by probstrodolfo** [faircloth-lab/phyluce#191]
Hi Dr. Faircloth,
I've been getting the same error message (please see below) when trying to run "phyluce_assembly_get_match_counts". I tried to go around this by setting up a git repository in my wd, with no success. Then I did the same (git init) for the repository accused in the error and I am not sure what is the issue here. Could it be any issue with my HEAD file? Any idea what is causing this? I appreciate any feedback.
Thanks,
Rodolfo 

(phyluce) bus-094542:uce-analysis rprobst$ phyluce_assembly_get_match_counts     --locus-db //Users/rprobst/Desktop/uce-analysis/lastz-80-80/probe.matches.sqlite     --taxon-list-config datasets.conf     --taxon-group 'myrmelachista1'     --output /Users/rprobst/Desktop/uce-analysis/taxon-set1/dataset1.conf
2020-05-01 07:19:13,009 - phyluce_assembly_get_match_counts - INFO - =========== Starting phyluce_assembly_get_match_counts ==========
2020-05-01 07:19:13,009 - phyluce_assembly_get_match_counts - INFO - Version: git fatal: not a git repository: '/Users/rprobst/anaconda2/envs/phyluce/lib/python2.7/site-packages/.git'
2020-05-01 07:19:13,009 - phyluce_assembly_get_match_counts - INFO - Argument --extend_locus_db: None
2020-05-01 07:19:13,009 - phyluce_assembly_get_match_counts - INFO - Argument --incomplete_matrix: False
2020-05-01 07:19:13,010 - phyluce_assembly_get_match_counts - INFO - Argument --keep_counts: False
2020-05-01 07:19:13,010 - phyluce_assembly_get_match_counts - INFO - Argument --locus_db: //Users/rprobst/Desktop/uce-analysis/lastz-80-80/probe.matches.sqlite
2020-05-01 07:19:13,010 - phyluce_assembly_get_match_counts - INFO - Argument --log_path: None
2020-05-01 07:19:13,010 - phyluce_assembly_get_match_counts - INFO - Argument --optimize: False
2020-05-01 07:19:13,010 - phyluce_assembly_get_match_counts - INFO - Argument --output: /Users/rprobst/Desktop/uce-analysis/taxon-set1/dataset1.conf
2020-05-01 07:19:13,010 - phyluce_assembly_get_match_counts - INFO - Argument --random: False
2020-05-01 07:19:13,010 - phyluce_assembly_get_match_counts - INFO - Argument --sample_size: 10
2020-05-01 07:19:13,010 - phyluce_assembly_get_match_counts - INFO - Argument --samples: 10
2020-05-01 07:19:13,010 - phyluce_assembly_get_match_counts - INFO - Argument --silent: False
2020-05-01 07:19:13,011 - phyluce_assembly_get_match_counts - INFO - Argument --taxon_group: myrmelachista1
2020-05-01 07:19:13,011 - phyluce_assembly_get_match_counts - INFO - Argument --taxon_list_config: /Users/rprobst/Desktop/uce-analysis/datasets.conf
2020-05-01 07:19:13,011 - phyluce_assembly_get_match_counts - INFO - Argument --verbosity: INFO
Traceback (most recent call last):
  File "/Users/rprobst/anaconda2/envs/phyluce/bin/phyluce_assembly_get_match_counts", line 351, in <module>
    main()
  File "/Users/rprobst/anaconda2/envs/phyluce/bin/phyluce_assembly_get_match_counts", line 329, in main
    len(organisms),
TypeError: object of type 'NoneType' has no len()

**Comment by probstrodolfo** [comment]
Problem solved. Apparently I can't use 'datasets.conf' as a file name. Replacing it by 'samples.conf' worked.
