### ISSUE TITLE
TypeError in phyluce_assembly_get_fastas_from_match_counts

### ISSUE THREAD

**Issue by akasmita** [faircloth-lab/phyluce#195]
Hello Dr Faircloth, I am getting the following error while running phyluce_assembly_get_fastas_from_match_counts 

MacBook-Pro-3:taxon-sets birdlab$ phyluce_assembly_get_fastas_from_match_counts --contigs /Users/birdlab/Desktop/Vinay/owlet_uce/contigs/ --locus-db /Users/birdlab/Desktop/Vinay/owlet_uce/mapped_uce/probe.matches.sqlite --match-count-output all-taxa-incomplete.conf --output all-taxa-incomplete.fasta --incomplete-matrix all-taxa-incomplete.incomplete --log-path log
2020-06-03 23:59:16,060 - phyluce_assembly_get_fastas_from_match_counts - INFO - ===== Starting phyluce_assembly_get_fastas_from_match_counts ====
2020-06-03 23:59:16,060 - phyluce_assembly_get_fastas_from_match_counts - INFO - Version: git fatal: not a git repository: '/Users/birdlab/opt/anaconda2/envs/phyluce/lib/python2.7/site-packages/.git'
2020-06-03 23:59:16,060 - phyluce_assembly_get_fastas_from_match_counts - INFO - Argument --contigs: /Users/birdlab/Desktop/Vinay/owlet_uce/contigs
2020-06-03 23:59:16,060 - phyluce_assembly_get_fastas_from_match_counts - INFO - Argument --extend_locus_contigs: None
2020-06-03 23:59:16,060 - phyluce_assembly_get_fastas_from_match_counts - INFO - Argument --extend_locus_db: None
2020-06-03 23:59:16,061 - phyluce_assembly_get_fastas_from_match_counts - INFO - Argument --incomplete_matrix: /Users/birdlab/Desktop/Vinay/owlet_uce/taxon-sets/all-taxa-incomplete.incomplete
2020-06-03 23:59:16,061 - phyluce_assembly_get_fastas_from_match_counts - INFO - Argument --locus_db: /Users/birdlab/Desktop/Vinay/owlet_uce/mapped_uce/probe.matches.sqlite
2020-06-03 23:59:16,061 - phyluce_assembly_get_fastas_from_match_counts - INFO - Argument --log_path: /Users/birdlab/Desktop/Vinay/owlet_uce/taxon-sets/log
2020-06-03 23:59:16,061 - phyluce_assembly_get_fastas_from_match_counts - INFO - Argument --match_count_output: /Users/birdlab/Desktop/Vinay/owlet_uce/taxon-sets/all-taxa-incomplete.conf
2020-06-03 23:59:16,061 - phyluce_assembly_get_fastas_from_match_counts - INFO - Argument --output: /Users/birdlab/Desktop/Vinay/owlet_uce/taxon-sets/all-taxa-incomplete.fasta
2020-06-03 23:59:16,061 - phyluce_assembly_get_fastas_from_match_counts - INFO - Argument --verbosity: INFO
Traceback (most recent call last):
  File "/Users/birdlab/opt/anaconda2/envs/phyluce/bin/phyluce_assembly_get_fastas_from_match_counts", line 263, in <module>
    main()
  File "/Users/birdlab/opt/anaconda2/envs/phyluce/bin/phyluce_assembly_get_fastas_from_match_counts", line 183, in main
    len(organisms),
TypeError: object of type 'NoneType' has no len()

What should I do to overcome this.? 
Thank you very much.

**Comment by brantfaircloth** [comment]
Sounds like there is something wrong with the format of your configuration file `all-taxa-incomplete.conf`.

**Comment by akasmita** [comment]
> Sounds like there is something wrong with the format of your configuration file `all-taxa-incomplete.conf`.

Thanks for the quick reply: 
Here's the log from the previous step: 

2020-06-03 23:19:11,445 - phyluce_assembly_get_match_counts - INFO - =========== Starting phyluce_assembly_get_match_counts ==========
2020-06-03 23:19:11,446 - phyluce_assembly_get_match_counts - INFO - Version: git fatal: not a git repository: '/Users/birdlab/opt/anaconda2/envs/phyluce/lib/python2.7/site-packages/.git'
2020-06-03 23:19:11,446 - phyluce_assembly_get_match_counts - INFO - Argument --extend_locus_db: None
2020-06-03 23:19:11,446 - phyluce_assembly_get_match_counts - INFO - Argument --incomplete_matrix: True
2020-06-03 23:19:11,446 - phyluce_assembly_get_match_counts - INFO - Argument --keep_counts: False
2020-06-03 23:19:11,446 - phyluce_assembly_get_match_counts - INFO - Argument --locus_db: /Users/birdlab/Desktop/Vinay/owlet_uce/mapped_uce/probe.matches.sqlite
2020-06-03 23:19:11,446 - phyluce_assembly_get_match_counts - INFO - Argument --log_path: None
2020-06-03 23:19:11,446 - phyluce_assembly_get_match_counts - INFO - Argument --optimize: False
2020-06-03 23:19:11,446 - phyluce_assembly_get_match_counts - INFO - Argument --output: /Users/birdlab/Desktop/Vinay/owlet_uce/taxon-sets/all/all-taxa-incomplete.conf
2020-06-03 23:19:11,446 - phyluce_assembly_get_match_counts - INFO - Argument --random: False
2020-06-03 23:19:11,446 - phyluce_assembly_get_match_counts - INFO - Argument --sample_size: 10
2020-06-03 23:19:11,446 - phyluce_assembly_get_match_counts - INFO - Argument --samples: 10
2020-06-03 23:19:11,446 - phyluce_assembly_get_match_counts - INFO - Argument --silent: False
2020-06-03 23:19:11,446 - phyluce_assembly_get_match_counts - INFO - Argument --taxon_group: all
2020-06-03 23:19:11,446 - phyluce_assembly_get_match_counts - INFO - Argument --taxon_list_config: /Users/birdlab/Desktop/Vinay/owlet_uce/taxon-set.conf
2020-06-03 23:19:11,447 - phyluce_assembly_get_match_counts - INFO - Argument --verbosity: INFO
2020-06-03 23:19:11,447 - phyluce_assembly_get_match_counts - INFO - There are 50 taxa in the taxon-group '[all]' in the config file taxon-set.conf
2020-06-03 23:19:11,448 - phyluce_assembly_get_match_counts - INFO - Getting UCE names from database
2020-06-03 23:19:11,452 - phyluce_assembly_get_match_counts - INFO - There are 5041 total UCE loci in the database
2020-06-03 23:20:54,795 - phyluce_assembly_get_match_counts - INFO - =========== Starting phyluce_assembly_get_match_counts ==========
2020-06-03 23:20:54,795 - phyluce_assembly_get_match_counts - INFO - Version: git fatal: not a git repository: '/Users/birdlab/opt/anaconda2/envs/phyluce/lib/python2.7/site-packages/.git'
2020-06-03 23:20:54,795 - phyluce_assembly_get_match_counts - INFO - Argument --extend_locus_db: None
2020-06-03 23:20:54,795 - phyluce_assembly_get_match_counts - INFO - Argument --incomplete_matrix: True
2020-06-03 23:20:54,795 - phyluce_assembly_get_match_counts - INFO - Argument --keep_counts: False
2020-06-03 23:20:54,795 - phyluce_assembly_get_match_counts - INFO - Argument --locus_db: /Users/birdlab/Desktop/Vinay/owlet_uce/mapped_uce/probe.matches.sqlite
2020-06-03 23:20:54,795 - phyluce_assembly_get_match_counts - INFO - Argument --log_path: None
2020-06-03 23:20:54,795 - phyluce_assembly_get_match_counts - INFO - Argument --optimize: False
2020-06-03 23:20:54,795 - phyluce_assembly_get_match_counts - INFO - Argument --output: /Users/birdlab/Desktop/Vinay/owlet_uce/taxon-sets/all/all-taxa-incomplete.conf
2020-06-03 23:20:54,795 - phyluce_assembly_get_match_counts - INFO - Argument --random: False
2020-06-03 23:20:54,795 - phyluce_assembly_get_match_counts - INFO - Argument --sample_size: 10
2020-06-03 23:20:54,796 - phyluce_assembly_get_match_counts - INFO - Argument --samples: 10
2020-06-03 23:20:54,796 - phyluce_assembly_get_match_counts - INFO - Argument --silent: False
2020-06-03 23:20:54,796 - phyluce_assembly_get_match_counts - INFO - Argument --taxon_group: all
2020-06-03 23:20:54,796 - phyluce_assembly_get_match_counts - INFO - Argument --taxon_list_config: /Users/birdlab/Desktop/Vinay/owlet_uce/taxon-set.conf
2020-06-03 23:20:54,796 - phyluce_assembly_get_match_counts - INFO - Argument --verbosity: INFO
2020-06-03 23:20:54,797 - phyluce_assembly_get_match_counts - INFO - There are 50 taxa in the taxon-group '[all]' in the config file taxon-set.conf
2020-06-03 23:20:54,797 - phyluce_assembly_get_match_counts - INFO - Getting UCE names from database
2020-06-03 23:20:54,801 - phyluce_assembly_get_match_counts - INFO - There are 5041 total UCE loci in the database
2020-06-03 23:20:55,886 - phyluce_assembly_get_match_counts - INFO - Getting UCE matches by organism to generate a INCOMPLETE matrix
2020-06-03 23:20:55,917 - phyluce_assembly_get_match_counts - INFO - There are 5032 UCE loci in an INCOMPLETE matrix
2020-06-03 23:20:55,926 - phyluce_assembly_get_match_counts - INFO - Writing the taxa and loci in the data matrix to /Users/birdlab/Desktop/Vinay/owlet_uce/taxon-sets/all/all-taxa-incomplete.conf
2020-06-03 23:20:55,929 - phyluce_assembly_get_match_counts - INFO - ========== Completed phyluce_assembly_get_match_counts ==========

Not understanding where am I going wrong.!

Thank you.

**Comment by brantfaircloth** [comment]
I don't know, but this is not an issue with the software, as far as I can tell.

Make sure that the path to the config file for the next step is correct (e.g. `/Users/birdlab/Desktop/Vinay/owlet_uce/taxon-sets/all/all-taxa-incomplete.conf`)

**Comment by akasmita** [comment]
> I don't know, but this is not an issue with the software, as far as I can tell.
> 
> Make sure that the path to the config file for the next step is correct (e.g. `/Users/birdlab/Desktop/Vinay/owlet_uce/taxon-sets/all/all-taxa-incomplete.conf`)

Okay. Thank you for your assistance.
