### ISSUE TITLE
phyluce_snp_bwa_multiple_align error

### ISSUE THREAD

**Issue by idanaughton** [faircloth-lab/phyluce#205]
Hello and thank you for making phyluce available!

I am getting the following error when I try to run phyluce_snp_bwa_multiple_align on a folder of fasta files (using illumiprocessor output as references):

2020-11-04 13:15:36,128 - phyluce_snp_bwa_multiple_align - INFO - ----------------------- Processing INZ845 -----------------------
2020-11-04 13:15:36,131 - phyluce_snp_bwa_multiple_align - INFO - Finding fastq/fasta files
2020-11-04 13:15:36,138 - phyluce_snp_bwa_multiple_align - INFO - File type is fastq
2020-11-04 13:15:36,143 - phyluce_snp_bwa_multiple_align - INFO - Building BAM for INZ845
2020-11-04 13:18:22,161 - phyluce_snp_bwa_multiple_align - INFO - Cleaning BAM for INZ845
Traceback (most recent call last):
  File "/home/idanaughton/.conda/envs/phyluce/bin/phyluce_snp_bwa_multiple_align", line 193, in <module>
    main()
  File "/home/idanaughton/.conda/envs/phyluce/bin/phyluce_snp_bwa_multiple_align", line 158, in main
    bam = picard.clean_up_bam(log, sample, sample_dir, bam, "pe")
  File "/home/idanaughton/.conda/envs/phyluce/lib/python2.7/site-packages/phyluce/picard.py", line 54, in clean_up_bam
    proc = subprocess.Popen(cmd, stdout=picard_out, stderr=subprocess.STDOUT)
  File "/home/idanaughton/.conda/envs/phyluce/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/idanaughton/.conda/envs/phyluce/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I have been running this code successfully on different datasets for the past couple months, and this is the first time I have received this error. I have also tried re-running phyluce_snp_bwa_multiple_align on folders of fastas that I have previously run the code on successfully, and those return the same error now. 

I've tried updating phyluce/conda (while keeping python 2.7) and other dependencies. Any ideas on what the problem may be? Thank you so much!

**Comment by brantfaircloth** [comment]
It may be samtools.  There's a weird error that keeps popping up - try to activate the phyluce environment and simply run `samtools`.  If that dies, you need to force reinstall samtools with something like:
```
<activate environment>
conda install --force-reinstall samtools
```

**Comment by idanaughton** [comment]
Thanks for your reply here. I was unable to get samtools to run also. I ended up creating a new environment and reinstalling phyluce, and fixed the problem (or got around it, at least) this way.

Thank you so much, again!
