### ISSUE TITLE
Illumiprocessor - naming issue

### ISSUE THREAD

**Issue by MaxTBC** [faircloth-lab/phyluce#208]
This has been discussed previously and I've read those posts, but am still having the following error:

```
2020-11-19 12:36:17,403 - illumiprocessor - INFO - ==================== Starting illumiprocessor ===================
2020-11-19 12:36:17,404 - illumiprocessor - INFO - Version: 2.0.9
2020-11-19 12:36:17,404 - illumiprocessor - INFO - Argument --config: illumiprocessor_HS.conf
2020-11-19 12:36:17,404 - illumiprocessor - INFO - Argument --cores: 12
2020-11-19 12:36:17,404 - illumiprocessor - INFO - Argument --input: /home/tangled/tbc/compute/UCE/HS/genewiz/30-412675317-101820/data/raw-fastq
2020-11-19 12:36:17,405 - illumiprocessor - INFO - Argument --log_path: /home/tangled/tbc/compute/UCE/HS/genewiz/30-412675317-101820/data/log
2020-11-19 12:36:17,405 - illumiprocessor - INFO - Argument --min_len: 40
2020-11-19 12:36:17,405 - illumiprocessor - INFO - Argument --no_merge: False
2020-11-19 12:36:17,406 - illumiprocessor - INFO - Argument --output: /home/tangled/tbc/compute/UCE/HS/genewiz/30-412675317-101820/data/clean-fastq
2020-11-19 12:36:17,406 - illumiprocessor - INFO - Argument --phred: phred33
2020-11-19 12:36:17,406 - illumiprocessor - INFO - Argument --r1_pattern: None
2020-11-19 12:36:17,406 - illumiprocessor - INFO - Argument --r2_pattern: None
2020-11-19 12:36:17,407 - illumiprocessor - INFO - Argument --se: False
2020-11-19 12:36:17,407 - illumiprocessor - INFO - Argument --trimmomatic: /home/tangled/miniconda2/envs/phyluce/bin/trimmomatic
2020-11-19 12:36:17,407 - illumiprocessor - INFO - Argument --verbosity: INFO
Traceback (most recent call last):
  File "/home/tangled/miniconda2/envs/phyluce/bin/illumiprocessor", line 17, in <module>
    sys.exit(main())
  File "/home/tangled/miniconda2/envs/phyluce/lib/python2.7/site-packages/illumiprocessor/cli/main.py", line 121, in main
    main(args)
  File "/home/tangled/miniconda2/envs/phyluce/lib/python2.7/site-packages/illumiprocessor/main.py", line 34, in main
    reads.append(core.SequenceData(args, conf, start_name, end_name))
  File "/home/tangled/miniconda2/envs/phyluce/lib/python2.7/site-packages/illumiprocessor/core.py", line 86, in __init__
    self._get_read_data()
  File "/home/tangled/miniconda2/envs/phyluce/lib/python2.7/site-packages/illumiprocessor/core.py", line 104, in _get_read_data
    "errors in your conf file.".format(self.start_name))
IOError: There is a problem with the read names for HS001. Ensure you do not have spelling/capitalization errors in your conf file.
```

My files are named as such: 
HS001_R1_001.fastq.gz
HS001_R2_001.fastq.gz
etc.

The .conf file:
```
[adapters]
i7:GATCGGAAGAGCACACGTCTGAACTCCAGTCAC*ATCTCGTATGCCGTCTTCTGCTTG
i5:AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT*GTGTAGATCTCGGTGGTCGCCGTATCATT

[tag sequences]
i5-001_A:GTCAACAG
i5-001_B:GTCAACAG
i7-110_01:GCACAACT
i7-110_02:TTCTCTCG
...

[tag map]
HS001:i5-001_A,i7-110_01
HS002:i5-001_B,i7-110_02
...

[names]
HS001:HS001
HS002:HS002
...
```
I've tried modifying the "{}_(?:.*)_(R1|READ1|Read1|read1)_\d+.fastq(?:.gz)*" in #90  to the following based on the other posts (#90 , #96 , and #74 ).

```
illumiprocessor \
    --input raw-fastq/ \
    --r1-pattern _R1_001 \
    --r2-pattern _R2_001 \
    --output clean-fastq \
    --config illumiprocessor_HS.conf \
    --cores 12 \
    --log-path log

--r1-pattern _R1
--r2-pattern _R2
--r1-pattern _R1_001
--r2-pattern _R2_001
--r1-pattern "{}_R1_\d+.fastq(?:.gz)*"
--r2-pattern "{}_R2_\d+.fastq(?:.gz)*"
--r1-pattern "{}R1\d+.fastq(?:.gz)*"
--r2-pattern "{}R1\d+.fastq(?:.gz)*"
And also tried changing my file names to 'HS001_S1_L001_R1_001.fastq.gz' and 'HS001_S1_L001_R2_001.fastq.gz' to try and mimic a previous analysis that did work under the default settings.
```

Probably a simple fix, but I cant get it to work.

Thanks in advance,
Max

**Comment by brantfaircloth** [comment]
It's hard to say without knowing what ALL of your files look like, but if your files are named like:
```
HS001_R1_001.fastq.gz
HS001_R2_001.fastq.gz
```
You definitely are going to need something like :
```
illumiprocessor \
    --input raw-fastq/ \
    --output clean-fastq \
    --config illumiprocessor_HS.conf \
    --cores 12 \
    --r1-pattern "{}_R1_\d+.fastq.gz" \
    --r2-pattern "{}_R2_\d+.fastq.gz" \
    --log-path log
```

**Comment by MaxTBC** [comment]
Thanks for the quick reply Brant.

The code you set did not work resulting in the same error.

Here is the working directory:
```
clean-fastq
illumiprocessor_HS.conf
log
raw-data
```

Here are all the file names inside the 'raw-fastq' folder:
```
HS001_R1_001.fastq.gz	       HS023_R2_001.fastq.gz  HS054_R1_001.fastq.gz
HS001_R2_001.fastq.gz	       HS024_R1_001.fastq.gz  HS054_R2_001.fastq.gz
HS024_R2_001.fastq.gz  HS055_R1_001.fastq.gz
HS025_R1_001.fastq.gz  HS055_R2_001.fastq.gz
HS002_R1_001.fastq.gz	       HS025_R2_001.fastq.gz  HS056_R1_001.fastq.gz
HS002_R2_001.fastq.gz	       HS026_R1_001.fastq.gz  HS056_R2_001.fastq.gz
HS003_R1_001.fastq.gz	       HS026_R2_001.fastq.gz  HS058_R1_001.fastq.gz
HS003_R2_001.fastq.gz	       HS027_R1_001.fastq.gz  HS058_R2_001.fastq.gz
HS004_R1_001.fastq.gz	       HS027_R2_001.fastq.gz  HS059_R1_001.fastq.gz
HS004_R2_001.fastq.gz	       HS028_R1_001.fastq.gz  HS059_R2_001.fastq.gz
HS006_R1_001.fastq.gz	       HS028_R2_001.fastq.gz  HS060_R1_001.fastq.gz
HS006_R2_001.fastq.gz	       HS029_R1_001.fastq.gz  HS060_R2_001.fastq.gz
HS007_R1_001.fastq.gz	       HS029_R2_001.fastq.gz  HS061_R1_001.fastq.gz
HS007_R2_001.fastq.gz	       HS030_R1_001.fastq.gz  HS061_R2_001.fastq.gz
HS008_R1_001.fastq.gz	       HS030_R2_001.fastq.gz  HS075_R1_001.fastq.gz
HS008_R2_001.fastq.gz	       HS031_R1_001.fastq.gz  HS075_R2_001.fastq.gz
HS009_R1_001.fastq.gz	       HS031_R2_001.fastq.gz  HS076_R1_001.fastq.gz
HS009_R2_001.fastq.gz	       HS032_R1_001.fastq.gz  HS076_R2_001.fastq.gz
HS010_R1_001.fastq.gz	       HS032_R2_001.fastq.gz  HS077_R1_001.fastq.gz
HS010_R2_001.fastq.gz	       HS033_R1_001.fastq.gz  HS077_R2_001.fastq.gz
HS011_R1_001.fastq.gz	       HS033_R2_001.fastq.gz  HS078_R1_001.fastq.gz
HS011_R2_001.fastq.gz	       HS034_R1_001.fastq.gz  HS078_R2_001.fastq.gz
HS012_R1_001.fastq.gz	       HS034_R2_001.fastq.gz  HS080_R1_001.fastq.gz
HS012_R2_001.fastq.gz	       HS035_R1_001.fastq.gz  HS080_R2_001.fastq.gz
HS013_R1_001.fastq.gz	       HS035_R2_001.fastq.gz  HS081_R1_001.fastq.gz
HS013_R2_001.fastq.gz	       HS036_R1_001.fastq.gz  HS081_R2_001.fastq.gz
HS014_R1_001.fastq.gz	       HS036_R2_001.fastq.gz  HS090_R1_001.fastq.gz
HS014_R2_001.fastq.gz	       HS047_R1_001.fastq.gz  HS090_R2_001.fastq.gz
HS015_R1_001.fastq.gz	       HS047_R2_001.fastq.gz  HS093_R1_001.fastq.gz
HS015_R2_001.fastq.gz	       HS048_R1_001.fastq.gz  HS093_R2_001.fastq.gz
HS017_R1_001.fastq.gz	       HS048_R2_001.fastq.gz  HS097_R1_001.fastq.gz
HS017_R2_001.fastq.gz	       HS049_R1_001.fastq.gz  HS097_R2_001.fastq.gz
HS018_R1_001.fastq.gz	       HS049_R2_001.fastq.gz  HS100_R1_001.fastq.gz
HS018_R2_001.fastq.gz	       HS050_R1_001.fastq.gz  HS100_R2_001.fastq.gz
HS019_R1_001.fastq.gz	       HS050_R2_001.fastq.gz  HS101_R1_001.fastq.gz
HS019_R2_001.fastq.gz	       HS051_R1_001.fastq.gz  HS101_R2_001.fastq.gz
HS020_R1_001.fastq.gz	       HS051_R2_001.fastq.gz  HS102_R1_001.fastq.gz
HS020_R2_001.fastq.gz	       HS052_R1_001.fastq.gz  HS102_R2_001.fastq.gz
HS022_R1_001.fastq.gz	       HS052_R2_001.fastq.gz  HS103_R1_001.fastq.gz
HS022_R2_001.fastq.gz	       HS053_R1_001.fastq.gz  HS103_R2_001.fastq.gz
HS023_R1_001.fastq.gz	       HS053_R2_001.fastq.gz
```

**Comment by brantfaircloth** [comment]
If I reduce your config file to:
```
[adapters]
i7:GATCGGAAGAGCACACGTCTGAACTCCAGTCAC*ATCTCGTATGCCGTCTTCTGCTTG
i5:AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT*GTGTAGATCTCGGTGGTCGCCGTATCATT

[tag sequences]
i5-001_A:GTCAACAG
i5-001_B:GTCAACAG
i7-110_01:GCACAACT
i7-110_02:TTCTCTCG

[tag map]
HS001:i5-001_A,i7-110_01
HS002:i5-001_B,i7-110_02

[names]
HS001:HS001
HS002:HS002
```
And run illumiprocessor against 4 files in `raw-fastq` named (not your files - just some test data):
```
(phyluce) ~/T/illumiprocessor-test > ll raw-fastq
total 1792
-rw-r--r--  1 bcf  staff   221K Nov 19 13:49 HS001_R1_001.fastq.gz
-rw-r--r--  1 bcf  staff   220K Nov 19 13:49 HS001_R2_001.fastq.gz
-rw-r--r--  1 bcf  staff   221K Nov 19 13:50 HS002_R1_001.fastq.gz
-rw-r--r--  1 bcf  staff   220K Nov 19 13:50 HS002_R2_001.fastq.gz
```
With
```
illumiprocessor \
    --input raw-fastq \
    --output clean-fastq \
    --config test.conf \
    --cores 1 \
    --r1-pattern "{}_R1_\d+.fastq.gz" \
    --r2-pattern "{}_R2_\d+.fastq.gz" \
    --log-path log
```
The code runs as expected with no errors.  Maybe split things up into smaller batches and see if you can localize the problem by batch - I checked obvious stuff, but can't immediately find what might be wrong.

**Comment by MaxTBC** [comment]
Hmmm... I did exactly what you have above but still erroring that way:
Same result when trying it with just the last two samples HS102 and HS103.

Is it a naming error specifically, or could it also be an issue with the .fastq.gz files themselves?

```
(phyluce) tangled@tbc-comp1:~/tbc/compute/UCE/HS/genewiz/30-412675317-101820/data$ illumiprocessor \
>     --input raw-fastq/1st_2 \
>     --output clean-fastq \
>     --config illumiprocessor_HS_1st2.conf \
>     --cores 12 \
>     --r1-pattern "{}_R1_\d+.fastq.gz" \
>     --r2-pattern "{}_R2_\d+.fastq.gz" \
>     --log-path log
[WARNING] Output directory exists, REMOVE [Y/n]? Y
2020-11-19 15:19:06,892 - illumiprocessor - INFO - ==================== Starting illumiprocessor ===================
2020-11-19 15:19:06,892 - illumiprocessor - INFO - Version: 2.0.9
2020-11-19 15:19:06,893 - illumiprocessor - INFO - Argument --config: illumiprocessor_HS_1st2.conf
2020-11-19 15:19:06,893 - illumiprocessor - INFO - Argument --cores: 12
2020-11-19 15:19:06,893 - illumiprocessor - INFO - Argument --input: /home/tangled/tbc/compute/UCE/HS/genewiz/30-412675317-101820/data/raw-fastq/1st_2
2020-11-19 15:19:06,893 - illumiprocessor - INFO - Argument --log_path: /home/tangled/tbc/compute/UCE/HS/genewiz/30-412675317-101820/data/log
2020-11-19 15:19:06,894 - illumiprocessor - INFO - Argument --min_len: 40
2020-11-19 15:19:06,894 - illumiprocessor - INFO - Argument --no_merge: False
2020-11-19 15:19:06,894 - illumiprocessor - INFO - Argument --output: /home/tangled/tbc/compute/UCE/HS/genewiz/30-412675317-101820/data/clean-fastq
2020-11-19 15:19:06,894 - illumiprocessor - INFO - Argument --phred: phred33
2020-11-19 15:19:06,895 - illumiprocessor - INFO - Argument --r1_pattern: {}_R1_\d+.fastq.gz
2020-11-19 15:19:06,895 - illumiprocessor - INFO - Argument --r2_pattern: {}_R2_\d+.fastq.gz
2020-11-19 15:19:06,895 - illumiprocessor - INFO - Argument --se: False
2020-11-19 15:19:06,896 - illumiprocessor - INFO - Argument --trimmomatic: /home/tangled/miniconda2/envs/phyluce/bin/trimmomatic
2020-11-19 15:19:06,896 - illumiprocessor - INFO - Argument --verbosity: INFO
Traceback (most recent call last):
  File "/home/tangled/miniconda2/envs/phyluce/bin/illumiprocessor", line 17, in <module>
    sys.exit(main())
  File "/home/tangled/miniconda2/envs/phyluce/lib/python2.7/site-packages/illumiprocessor/cli/main.py", line 121, in main
    main(args)
  File "/home/tangled/miniconda2/envs/phyluce/lib/python2.7/site-packages/illumiprocessor/main.py", line 34, in main
    reads.append(core.SequenceData(args, conf, start_name, end_name))
  File "/home/tangled/miniconda2/envs/phyluce/lib/python2.7/site-packages/illumiprocessor/core.py", line 86, in __init__
    self._get_read_data()
  File "/home/tangled/miniconda2/envs/phyluce/lib/python2.7/site-packages/illumiprocessor/core.py", line 104, in _get_read_data
    "errors in your conf file.".format(self.start_name))
IOError: There is a problem with the read names for HS001. Ensure you do not have spelling/capitalization errors in your conf file.
```

**Comment by brantfaircloth** [comment]
It seems to be having problems finding one of your two read files (I can't tell why).  Basically, this error happens when it cannot find R1 and/or R2.  Then it fires of the error message you see.  Maybe check that all your filenames are absolutely correct between your config file and what's in the `1st_2` directory and that there are definitely both R1 and R2 files for the HS001 sample in the directory `1st_2`.

**Comment by MaxTBC** [comment]
Thats what I was thinking, it not being able to 'find' the files, but I've double checked. 

```
illumiprocessor \
    --input raw-fastq/1st_2 \
    --output clean-fastq \
    --config illumiprocessor_HS_1st2.conf \
    --cores 12 \
    --r1-pattern "{}_R1_\d+.fastq.gz" \
    --r2-pattern "{}_R2_\d+.fastq.gz" \
    --log-path log
```

```
(phyluce) tangled@tbc-comp1:~/tbc/compute/UCE/HS/genewiz/30-412675317-101820/data$ head -n20 illumiprocessor_HS_1st2.conf 
[adapters]
i7:GATCGGAAGAGCACACGTCTGAACTCCAGTCAC*ATCTCGTATGCCGTCTTCTGCTTG
i5:AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT*GTGTAGATCTCGGTGGTCGCCGTATCATT

[tag sequences]
i5-001_A:GTCAACAG
i5-001_B:GTCAACAG
i7-110_01:GCACAACT
i7-110_02:TTCTCTCG

[tag map]
HS001:i5-001_A,i7-110_01
HS002:i5-001_B,i7-110_02

[names]
HS001:HS001
HS002:HS002
```

```
(phyluce) tangled@tbc-comp1:~/tbc/compute/UCE/HS/genewiz/30-412675317-101820/data/raw-data/1st_2$ ls
HS001_R1_001.fastq.gz  HS002_R1_001.fastq.gz
HS001_R2_001.fastq.gz  HS002_R2_001.fastq.gz
```

**Comment by MAUlyssea** [comment]
MaxTBC, I'm having the same problem. How did you solve it? I appreciate any comments on that.




> Thats what I was thinking, it not being able to 'find' the files, but I've double checked.
> 
> ```
> illumiprocessor \
>     --input raw-fastq/1st_2 \
>     --output clean-fastq \
>     --config illumiprocessor_HS_1st2.conf \
>     --cores 12 \
>     --r1-pattern "{}_R1_\d+.fastq.gz" \
>     --r2-pattern "{}_R2_\d+.fastq.gz" \
>     --log-path log
> ```
> 
> ```
> (phyluce) tangled@tbc-comp1:~/tbc/compute/UCE/HS/genewiz/30-412675317-101820/data$ head -n20 illumiprocessor_HS_1st2.conf 
> [adapters]
> i7:GATCGGAAGAGCACACGTCTGAACTCCAGTCAC*ATCTCGTATGCCGTCTTCTGCTTG
> i5:AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT*GTGTAGATCTCGGTGGTCGCCGTATCATT
> 
> [tag sequences]
> i5-001_A:GTCAACAG
> i5-001_B:GTCAACAG
> i7-110_01:GCACAACT
> i7-110_02:TTCTCTCG
> 
> [tag map]
> HS001:i5-001_A,i7-110_01
> HS002:i5-001_B,i7-110_02
> 
> [names]
> HS001:HS001
> HS002:HS002
> ```
> 
> ```
> (phyluce) tangled@tbc-comp1:~/tbc/compute/UCE/HS/genewiz/30-412675317-101820/data/raw-data/1st_2$ ls
> HS001_R1_001.fastq.gz  HS002_R1_001.fastq.gz
> HS001_R2_001.fastq.gz  HS002_R2_001.fastq.gz
> ```

**Comment by brantfaircloth** [comment]
@MAUlyssea What does the config file that you are trying to use look like and what are the file names you are trying to process?

**Comment by MAUlyssea** [comment]
Hi! I'm trying to run illumiprocessor just with few fastq files first.
My config file is like:

[adapters]
i7:GATCGGAAGAGCACACGTCTGAACTCCAGTCAC*ATCTCGTATGCCGTCTTCTGCTTG
i5:AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT*GTGTAGATCTCGGTGGTCGCCGTATCATT

[tag sequences]
i7-iTru7_210_08:GCTGTAAG
i7-iTru7_210_09:CGAATACG
i7-iTru7_210_10:GCCAGAAT
i7-iTru7_210_11:TCCTGGTA
i5-iTru5_106_E:ACTCCTAC
i5-iTru5_106_F:GTCTGAGT
i5-iTru5_106_G:ACTGCACT
i5-iTru5_106_H:GGAATGTC

[tag map]
001_01_:i7-iTru7_210_08,i5-iTru5_106_E
002_01_:i7-iTru7_210_09,i5-iTru5_106_F
003_01_:i7-iTru7_210_10,i5-iTru5_106_G
004_01_:i7-iTru7_210_11,i5-iTru5_106_H

[names]
001_01_:Hylomyrma_balzani_001_01_
002_01_:Hylomyrma_balzani_002_01_
003_01_:Hylomyrma_balzani_003_01_
004_01_:Hylomyrma_balzani_004_01_

and the raw-fastq files I'm trying to process are these:
001_01_R1_001.fastq.gz
001_01_R2_001.fastq.gz
002_01_R1_001.fastq.gz
002_01_R2_001.fastq.gz
003_01_R1_001.fastq.gz
003_01_R2_001.fastq.gz
004_01_R1_001.fastq.gz
004_01_R2_001.fastq.gz

**Comment by brantfaircloth** [comment]
You will need to adjust the regular expression to match your read names.  That will look something like:
```
illumiprocessor \
    --input <path-to-files> \
    --output clean-fastq \
    --config <config file>\
    --cores 12 \
    --r1-pattern "{}R1_\d+.fastq.gz" \
    --r2-pattern "{}R2_\d+.fastq.gz" \
    --log-path log
```

**Comment by MAUlyssea** [comment]
For specifying the r1 & r2 patterns I've tried:
    --r1-pattern "{}_R1\d+.fastq.gz" \
    --r2-pattern "{}_R2\d+.fastq.gz" \ 

    --r1-pattern "{}_R1_\d+.fastq.gz" \
    --r2-pattern "{}_R2_\d+.fastq.gz" \ 

    --r1-pattern "{}_R1_001\d+.fastq.gz" \
    --r2-pattern "{}_R2_001\d+.fastq.gz" \ 

and all failed. I just tried the way you said and it worked!! But I didnt put the log specification.
I ran:
illumiprocessor \
    --input <path-to-files> \
    --output clean-fastq \
    --config <config file>\
    --cores 12 \
    --r1-pattern "{}R1_\d+.fastq.gz" \
    --r2-pattern "{}R2_\d+.fastq.gz"

Thanks!!

**Comment by brantfaircloth** [comment]
You needed to structure it like I suggested because you included the second `_` in your sample names (e.g. `001_01_`), and the sample name is what gets substituted into the squiggly brackets (`{}`) in the pattern option. Glad you got it working.

**Comment by tobihays** [comment]
Hello,

I have been dealing with a naming error that is similar to those above. The suggested solutions do not resolve this issue. 

I have 40*2 = 80 total fastq.gz files located in the directory "working" that follow this structure
`S703_L003_R1_001.fastq.gz`
`S703_L003_R2_001.fastq.gz`

My configuration file is structured as:
`[adapters]`
`i7:GATCGGAAGAGCACACGTCTGAACTCCAGTCAC*ATCTCGTATGCCGTCTTCTGCTTG`
`i5:AATGATACGGCGACCACCGAGATCTACAC*ACACTCTTTCCCTACACGACGCTCTTCCGATCT`

`[tag sequences]`
`i7-128:TTCGAAGC`
`i5-534:CGACGTTA`

`[tag map]`
`S703:i7-128,i5-534`

`[names]
`S703:BME101020_Atorridus_KernCo_Caliente`

My .sh file:
`illumiprocessor \`
`--input working \`
`--output clean-fastq \`
`--config illumiprocessor_rev.conf \`
`--cores 20 \`
`--r1-pattern "{}R1_\d+.fastq.gz" \`
`--r2-pattern "{}R2_\d+.fastq.gz"`

(I have tried with `{}_R1_\d+.fastq.gz` and without the r1/r2 pattern flags as well)

The exact error I get:
`File "/home/hays/miniconda3/envs/phyluce-1.7.1/lib/python3.6/site-packages/illumiprocessor/core.py", line 106, in _get_read_data
    "errors in your conf file.".format(self.start_name)
OSError: There is a problem with the read names for S703. Ensure you do not have spelling/capitalization errors in your conf file.`

Thank you for your help.
