### ISSUE TITLE
trimmomatic butchers too large files (more than 1,000,000 reads)

### ISSUE THREAD

**Issue by tobiashofmann88** [faircloth-lab/phyluce#21]
I have zipped fastq (.fastq.gz) files of in total 10 samples. The files vary in size between 500,000 and 5,600,000 reads. If I run them through trimmomatic with illumiprocessor:
<blockquote>
<p>
($ illumiprocessor --trimmomatic /usr/local/anaconda/jar/trimmomatic.jar --input demultiplexed/ --output uce-clean/ --config your-illumiprocessor.conf --cores 12 --verbosity INFO)
</p>
</blockquote>
 it seems to work fine (no errors or warnings what-so-ever) for all samples and the resulting files and folder structure is as described in the manual. Strangely, in the following step, the assembly with assemblo_abyss comes to an immediate stop for all the files, which original size was >1,000,000 reads (see below). It seems to not be a problem with assemblo_abyss, as it works for the other, smaller files. 
So, trimming seems to work but the big files get somehow manipulated by trimmomatic or illumiprocessor so that they can't be opened with any program (I can't even unzip them anymore). Any ideas what to do?

<blockquote>
<p>
$ python /usr/local/anaconda/bin/assemblo_abyss.py --config assembly.conf --output assembly --kmer 35 --subfolder split-adapter-quality-trimmed/ --cores 12 --clean --log-path log
2015-01-26 13:41:23,097 - assemblo_abyss - INFO - ==================== Starting assemblo_abyss ====================
2015-01-26 13:41:23,098 - assemblo_abyss - INFO - Version: 2.0.0
2015-01-26 13:41:23,098 - assemblo_abyss - INFO - Argument --clean: True
2015-01-26 13:41:23,098 - assemblo_abyss - INFO - Argument --config: /home/tobias/NGS_data/new/uce-clean/assembly.conf
2015-01-26 13:41:23,098 - assemblo_abyss - INFO - Argument --cores: 12
2015-01-26 13:41:23,098 - assemblo_abyss - INFO - Argument --dir: None
2015-01-26 13:41:23,099 - assemblo_abyss - INFO - Argument --kmer: 35
2015-01-26 13:41:23,099 - assemblo_abyss - INFO - Argument --log_path: /home/tobias/NGS_data/new/uce-clean/log
2015-01-26 13:41:23,099 - assemblo_abyss - INFO - Argument --output: /home/tobias/NGS_data/new/uce-clean/assembly
2015-01-26 13:41:23,099 - assemblo_abyss - INFO - Argument --subfolder: split-adapter-quality-trimmed/
2015-01-26 13:41:23,099 - assemblo_abyss - INFO - Argument --verbosity: INFO
2015-01-26 13:41:23,099 - assemblo_abyss - INFO - Getting input filenames and creating output directories
2015-01-26 13:41:23,127 - assemblo_abyss - INFO - -------------------------- Processing 2 -------------------------
2015-01-26 13:41:23,141 - assemblo_abyss - INFO - Finding fastq/fasta files
2015-01-26 13:41:23,148 - assemblo_abyss - INFO - File type is fastq
2015-01-26 13:41:23,149 - assemblo_abyss - INFO - Running abyss-pe against data
Traceback (most recent call last):
  File "/usr/local/anaconda/bin/assemblo_abyss.py", line 313, in <module>
    main()
  File "/usr/local/anaconda/bin/assemblo_abyss.py", line 301, in main
    contigs_file = get_contigs_file_from_output(output)
  File "/usr/local/anaconda/bin/assemblo_abyss.py", line 205, in get_contigs_file_from_output
    return glob.glob(os.path.join(output, "*-contigs.fa"))[0]
IndexError: list index out of range
</p>
</blockquote>

**Comment by tobiashofmann88** [comment]
this is what the error log-file from abyss reports:

<blockquote>
<p>
gzip: /home/tobias/NGS_data/data/uce-clean/2/split-adapter-quality-trimmed/2-READ1.fastq.gz: unexpected end of file
PID 8166 exited with status 1
condaflmake: *** [out_k35-1.fa] Error 1
</p>
</blockquote>

**Comment by brantfaircloth** [comment]
Strange - i have not seen this problem crop up before. It looks like illumiprocessor/trimmomatic may have produced corrupted gzip files.  I'm not sure why this would happen (perhaps a RAM issue that caused a problem during the trimming of the larger files - like an early abort or similar), but you could check the log output files for the illumiprocessor run.  You could also try to run one of the larger files that is causing you problems through trimmomatic on its own - then make sure the resulting gzip is valid (with something like gunzip -t).  if it's valid, you should be able to run things through assembly without problems.  it's possible that running such a high level of multiprocessing (particularly if you have insufficient RAM for the files you are running) is the root source of the issue - too many files were undergoing trimming at once, which might have caused a problem.  It's really hard to diagnose what the issue is in this case - so you might have to play around with it a bit.

**Comment by tobiashofmann88** [comment]
Okay it works when running the larger files separately through trimmomatic. As you explained, Brant, it probably had to do with the RAM being allocated to each core on our university server. For the big files it might not be enough to handle them if they are run with a bunch of other files through trimmomatic, so beware of invalid fastq.gz zip files!

**Comment by idanaughton** [comment]
I am receiving this error message also with 3 (out of 200) of my samples. 
After I run the files separately through trimmomatic (assuming this works) how should I modify my AbySS code to take the trimmomatic output?
