### ISSUE TITLE
error with phyluce_genetrees_run_raxml_genetrees

### ISSUE THREAD

**Issue by kkmills** [faircloth-lab/phyluce#212]
Hi Brant, 

I am trying to run phyluce_genetrees_run_raxml_genetrees so that I can generate gene trees for ASTRAL, but it is giving an error after it does uce-2012 each time

phyluce_genetrees_run_raxml_genetrees --input batch3-strict-phylip-90p/ --output batch3-90p/ --outgroup cynomyszzz --cores 8 --threads 1
[WARNING] Output directory exists, REMOVE [Y/n]? Y
2021-01-14 16:41:52,114 - phyluce_genetrees_run_raxml_genetrees - INFO - ========= Starting phyluce_genetrees_run_raxml_genetrees ========
2021-01-14 16:41:52,115 - phyluce_genetrees_run_raxml_genetrees - INFO - Version: git fatal: not a git repository: '/home/kendall/miniconda3/envs/phyluce/lib/python2.7/site-packages/.git'
2021-01-14 16:41:52,117 - phyluce_genetrees_run_raxml_genetrees - INFO - Argument --cores: 8
2021-01-14 16:41:52,117 - phyluce_genetrees_run_raxml_genetrees - INFO - Argument --input: /home/kendall/marmot-uces/10_astral/1_gene-trees/batch3-strict-phylip-90p
2021-01-14 16:41:52,118 - phyluce_genetrees_run_raxml_genetrees - INFO - Argument --log_path: None
2021-01-14 16:41:52,118 - phyluce_genetrees_run_raxml_genetrees - INFO - Argument --outgroup: cynomyszzz
2021-01-14 16:41:52,118 - phyluce_genetrees_run_raxml_genetrees - INFO - Argument --output: /home/kendall/marmot-uces/10_astral/1_gene-trees/batch3-90p
2021-01-14 16:41:52,119 - phyluce_genetrees_run_raxml_genetrees - INFO - Argument --quiet: False
2021-01-14 16:41:52,119 - phyluce_genetrees_run_raxml_genetrees - INFO - Argument --threads: 1
2021-01-14 16:41:52,119 - phyluce_genetrees_run_raxml_genetrees - INFO - Argument --tree_searches: 100
2021-01-14 16:41:52,119 - phyluce_genetrees_run_raxml_genetrees - INFO - Argument --verbosity: INFO
The total number of cores in use is 8. This will run
8 concurrent jobs of 1 thread(s). Is this correct [Y/n]? Y
2021-01-14 16:41:56,728 - phyluce_genetrees_run_raxml_genetrees - INFO - 1700 alignments read
name=uce-2209,seconds=115.526082,sites=104
name=uce-2010,seconds=120.841495,sites=109
name=uce-1867,seconds=132.624486,sites=119
name=uce-134,seconds=139.268848,sites=88
name=uce-1512,seconds=157.943661,sites=115
name=uce-1181,seconds=165.439187,sites=112
name=uce-1003,seconds=173.363159,sites=114
name=uce-172,seconds=186.176460,sites=113
name=uce-1868,seconds=151.644705,sites=100
name=uce-2012,seconds=174.120491,sites=126
Traceback (most recent call last):
  File "/home/kendall/miniconda3/envs/phyluce/bin/phyluce_genetrees_run_raxml_genetrees", line 186, in <module>
    main()
  File "/home/kendall/miniconda3/envs/phyluce/bin/phyluce_genetrees_run_raxml_genetrees", line 174, in main
    trees = pool.map(run_raxml, work)
  File "/home/kendall/miniconda3/envs/phyluce/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/kendall/miniconda3/envs/phyluce/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by brantfaircloth** [comment]
Have you checked to see if there is a problem with that specific locus (or moved it to another directory, then tried again on original data minus that file)?  Alternatively, can you get raxml to generate a gene tree from that alignment manually?

**Comment by kkmills** [comment]
So I made a new directory and deleted uce-2012.phylip file, and I noticed there was also a uce-2012.phylip.reduced file in there. There are about 20 loci (out of 1700) that had a .reduced file in the directory. I'm not sure what those are or if it is related to this error.

But I deleted both the .phylip and .phylip.reduced for uce-2012, and this time it got stuck on uce-2010, which is weird because it seemed to do uce-2010 fine the first time. So I deleted this locus also (it had a .reduced version too), and now it doesn't seem to be processing any loci before giving the error:

phyluce_genetrees_run_raxml_genetrees --input test-phylip/ --output test-output --outgroup cynomyszzz --cores 8 --threads 1
2021-01-15 15:19:11,230 - phyluce_genetrees_run_raxml_genetrees - INFO - ========= Starting phyluce_genetrees_run_raxml_genetrees ========
2021-01-15 15:19:11,231 - phyluce_genetrees_run_raxml_genetrees - INFO - Version: git fatal: not a git repository: '/home/kendall/miniconda3/envs/phyluce/lib/python2.7/site-packages/.git'
2021-01-15 15:19:11,231 - phyluce_genetrees_run_raxml_genetrees - INFO - Argument --cores: 8
2021-01-15 15:19:11,232 - phyluce_genetrees_run_raxml_genetrees - INFO - Argument --input: /home/kendall/marmot-uces/10_astral/1_gene-trees/test-phylip
2021-01-15 15:19:11,232 - phyluce_genetrees_run_raxml_genetrees - INFO - Argument --log_path: None
2021-01-15 15:19:11,232 - phyluce_genetrees_run_raxml_genetrees - INFO - Argument --outgroup: cynomyszzz
2021-01-15 15:19:11,233 - phyluce_genetrees_run_raxml_genetrees - INFO - Argument --output: /home/kendall/marmot-uces/10_astral/1_gene-trees/test-output
2021-01-15 15:19:11,234 - phyluce_genetrees_run_raxml_genetrees - INFO - Argument --quiet: False
2021-01-15 15:19:11,234 - phyluce_genetrees_run_raxml_genetrees - INFO - Argument --threads: 1
2021-01-15 15:19:11,234 - phyluce_genetrees_run_raxml_genetrees - INFO - Argument --tree_searches: 100
2021-01-15 15:19:11,234 - phyluce_genetrees_run_raxml_genetrees - INFO - Argument --verbosity: INFO
The total number of cores in use is 8. This will run
8 concurrent jobs of 1 thread(s). Is this correct [Y/n]? Y
2021-01-15 15:19:13,718 - phyluce_genetrees_run_raxml_genetrees - INFO - 1698 alignments read
Traceback (most recent call last):
  File "/home/kendall/miniconda3/envs/phyluce/bin/phyluce_genetrees_run_raxml_genetrees", line 186, in <module>
    main()
  File "/home/kendall/miniconda3/envs/phyluce/bin/phyluce_genetrees_run_raxml_genetrees", line 174, in main
    trees = pool.map(run_raxml, work)
  File "/home/kendall/miniconda3/envs/phyluce/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/kendall/miniconda3/envs/phyluce/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by brantfaircloth** [comment]
the reduced file is what you get when raxml removes unnecessary columns of data.  the log files for each locus output by raxml should tell you what is going on.  alternatively, you can run a single locus that didn't work manually and check the log produced from that.
