### ISSUE TITLE
Fix version header when not in git

### ISSUE THREAD

**Issue by brantfaircloth** [faircloth-lab/phyluce#218]
Version is supposed to pull git hash when running from git and a version number when it's not (which is most people).  However, currently displays:
```
 Version: 2.0_r_fatal: Not a git repository: '/home/bcf/conda/envs/phyluce-1.7/lib/python3.6/site-packages/.git'
```

**Comment by warthmann** [comment]
Hello,
 I am running a phyluce installed with conda. I am hence not in a git repo and I am getting a similar error: 


````code
uce-tutorial$ phyluce_assembly_assemblo_trinity \
>     --conf assembly.conf \
>     --output trinity-assemblies \
>     --clean \
>     --cores 24
2021-03-03 17:28:19,182 - phyluce_assembly_assemblo_trinity - INFO - =========== Starting phyluce_assembly_assemblo_trinity ==========
2021-03-03 17:28:19,182 - phyluce_assembly_assemblo_trinity - INFO - Version: git fatal: Not a git repository: '/home/norman/data/miniconda3/envs/phyluce/lib/python2.7/site-packages/.git'
2021-03-03 17:28:19,182 - phyluce_assembly_assemblo_trinity - INFO - Argument --clean: True
2021-03-03 17:28:19,182 - phyluce_assembly_assemblo_trinity - INFO - Argument --config: /data/norman/coffee/allele_assembly/uce-tutorial/assembly.conf
2021-03-03 17:28:19,182 - phyluce_assembly_assemblo_trinity - INFO - Argument --cores: 8
2021-03-03 17:28:19,183 - phyluce_assembly_assemblo_trinity - INFO - Argument --dir: None
2021-03-03 17:28:19,183 - phyluce_assembly_assemblo_trinity - INFO - Argument --log_path: None
2021-03-03 17:28:19,183 - phyluce_assembly_assemblo_trinity - INFO - Argument --min_kmer_coverage: 2
2021-03-03 17:28:19,183 - phyluce_assembly_assemblo_trinity - INFO - Argument --output: /data/norman/coffee/allele_assembly/uce-tutorial/trinity-assemblies
2021-03-03 17:28:19,183 - phyluce_assembly_assemblo_trinity - INFO - Argument --subfolder: 
2021-03-03 17:28:19,183 - phyluce_assembly_assemblo_trinity - INFO - Argument --verbosity: INFO
2021-03-03 17:28:19,183 - phyluce_assembly_assemblo_trinity - INFO - Getting input filenames and creating output directories
````

**Comment by brantfaircloth** [comment]
Hi.

These are actually two slightly separate errors (the one I was dealing with is in an upgraded version of phyluce that's not yet released).  It does not seem like your error is causing phyluce to stop working (if it is, a solution is to install git).  The overall error should be fixed in the updated version I hope to release in a few days.

**Comment by warthmann** [comment]
however, more significant is this IOError:
(seems some hard coded path somewhere)

````code
2021-03-03 17:28:19,183 - phyluce_assembly_assemblo_trinity - INFO - Getting input filenames and creating output directories
Traceback (most recent call last):
  File "/home/norman/data/miniconda3/envs/phyluce/bin/phyluce_assembly_assemblo_trinity", line 362, in <module>
    main()
  File "/home/norman/data/miniconda3/envs/phyluce/bin/phyluce_assembly_assemblo_trinity", line 307, in main
    input = get_input_data(args.config, args.dir)
  File "/home/norman/data/miniconda3/envs/phyluce/lib/python2.7/site-packages/phyluce/raw_reads.py", line 142, in get_input_data
    raise IOError("{} is not a directory".format(sample[1]))
IOError: /scratch/bfaircloth-uce-tutorial/clean-fastq/alligator_mississippiensis/split-adapter-quality-trimmed is not a directory
````

**Comment by brantfaircloth** [comment]
It seems like the config file you're using to assemble includes paths on my computer to the data when these need to be paths on your computer to the data (e.g. the path to where you downloaded the data).

**Comment by warthmann** [comment]
I am also noting a copy/paste/edit glitch in the tutorial, https://phyluce.readthedocs.io/en/latest/tutorial-one.html#
where I am supposed to substitute "phyluce_assembly_assemblo_trinity" for "phyluce_assembly_assemblo_trinity"

````code
Trinity is no longer supported on MacOS (generally, or in phyluce), so substitute phyluce_assembly_assemblo_trinity for phyluce_assembly_assemblo_trinity.
````

**Comment by brantfaircloth** [comment]
Yep, also fixed in the update.  ``phyluce_assembly_assemblo_spades`` will do what you need.

**Comment by warthmann** [comment]
indeed my bad, fixed now and running. Thanks for this speedy response!

**Comment by brantfaircloth** [comment]
you bet 👍.  thanks for noting these!
