### ISSUE TITLE
phyluce_snp_convert_vcf_to_structure invalid literal

### ISSUE THREAD

**Issue by heather340** [faircloth-lab/phyluce#223]
I'm running into an issue with:

> (phyluce) bash-4.2$ phyluce_snp_convert_vcf_to_structure --input filtered_unlinked.recode.vcf  --output filtered_unlinked_structure.str
> Working.Traceback (most recent call last):
>   File "/users/PAS1390/osu10232/miniconda3/envs/phyluce/bin/phyluce_snp_convert_vcf_to_structure", line 138, in <module>
>     main()
>   File "/users/PAS1390/osu10232/miniconda3/envs/phyluce/bin/phyluce_snp_convert_vcf_to_structure", line 100, in main
>     coded_gt = [int(i) for i in sample.data.GT.split("/")]
> ValueError: invalid literal for int() with base 10: '.'

Input was build with vcftools after running through the Erickson et al. SNP calling pipeline.

We think the issue is within my .vcf file, but I can't quite figure out the right combo of things to change within the FORMAT block: 

> ##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
> ##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads with MQ=255 or with bad mates are filtered)">
> ##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
> ##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
> ##FORMAT=<ID=MIN_DP,Number=1,Type=Integer,Description="Minimum DP observed within the GVCF block">
> ##FORMAT=<ID=PGT,Number=1,Type=String,Description="Physical phasing haplotype information, describing how the alternate alleles are phased in relation to one another">
> ##FORMAT=<ID=PID,Number=1,Type=String,Description="Physical phasing ID information, where each unique ID within a given sample (but not across samples) connects records within a phasing group">
> ##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
> ##FORMAT=<ID=RGQ,Number=1,Type=Integer,Description="Unconditional reference genotype confidence, encoded as a phred quality -10*log10 p(genotype call is wrong)">
> ##FORMAT=<ID=SB,Number=4,Type=Integer,Description="Per-sample component statistics which comprise the Fisher's Exact Test to detect strand bias.">

Any thoughts or a file to compare with would be very welcomed!!

**Comment by brantfaircloth** [comment]
Have you tried to make the conversion from vcf to structure using PLINK?  Something like:
```
plink --vcf [vcf filename] --recode structure
```

**Comment by heather340** [comment]
I had not, but I can keep testing it out to see if I can get it going. PGDSpider is always my fall back but a single line of code is always easier :)

I just heard back from someone who got phyluce_snp_convert_vcf_to_structure working by changing line 94 to: 

> if sample.data.GT == None or sample.data.GT == “./.“

I was able to reproduce it successfully, so we are good to go! Thanks for the quick response.

**Comment by brantfaircloth** [comment]
Nice - i'll integrate that fix to the code.

**Comment by brantfaircloth** [comment]
Leaving open for now as a reminder to fix.
