### ISSUE TITLE
phyluce_probe_get_multi_merge_table syntax error

### ISSUE THREAD

**Issue by RaulGoch** [faircloth-lab/phyluce#231]
I am running into the following error:

```
phyluce_probe_get_multi_merge_table - INFO - Creating database

Traceback (most recent call last):

  File "/miniconda3/envs/phyluce-1.7.1/bin/phyluce_probe_get_multi_merge_table", line 147, in <module>

    main()

  File "/miniconda3/envs/phyluce-1.7.1/bin/phyluce_probe_get_multi_merge_table", line 129, in main

    conn, c = create_match_database(args.output, organisms, args.base_taxon)

  File "/miniconda3/envs/phyluce-1.7.1/bin/phyluce_probe_get_multi_merge_table", line 85, in create_match_database

    c.execute(query)

sqlite3.OperationalError: near "-": syntax error
```

Any Idea of what might be the issue?

**Comment by brantfaircloth** [comment]
Are the dashes/hyphens on the taxon names?  If so, that is potentially the problem.  Try to replace those with underscores or use just letters [followed by numbers if you want] as the taxon name.  The tutorial taxon names are one way to do this (e.g. triCas1, agrPla2, etc.).

**Comment by RaulGoch** [comment]
Hi Brant,

yes! I think it was that. I changed the taxa name to only letters and numbers and all worked just fine. Thanks!

**Comment by brantfaircloth** [comment]
Excellent.
