### ISSUE TITLE
phyluce_align_add_missing_data_designators fails to run

### ISSUE THREAD

**Issue by shofmon88** [faircloth-lab/phyluce#237]
I'm working through the phyluce pipeline, and everything runs smoothly until this step. The process dies; I can't figure out why. Log attached.

```python
phyluce_align_add_missing_data_designators --alignments mafft-nexus-60p/ --output mafft-nexus-60p-with-missing/ --match-count-output all_taxa_incomplete.conf --incomplete-matrix all_taxa_incomplete.incomplete --log-path log --cores 24
2021-07-06 10:13:42,131 - phyluce_align_add_missing_data_designators - INFO - ====== Starting phyluce_align_add_missing_data_designators ======
2021-07-06 10:13:42,132 - phyluce_align_add_missing_data_designators - INFO - Version: 1.7.1
2021-07-06 10:13:42,132 - phyluce_align_add_missing_data_designators - INFO - Commit: None
2021-07-06 10:13:42,132 - phyluce_align_add_missing_data_designators - INFO - Argument --alignments: /home/ryan/Documents/uce-ant-mimic/First-analysis-complete-20210704/spades_all_taxa/mafft-nexus-60p
2021-07-06 10:13:42,132 - phyluce_align_add_missing_data_designators - INFO - Argument --check_missing: True
2021-07-06 10:13:42,132 - phyluce_align_add_missing_data_designators - INFO - Argument --cores: 24
2021-07-06 10:13:42,132 - phyluce_align_add_missing_data_designators - INFO - Argument --incomplete_matrix: /home/ryan/Documents/uce-ant-mimic/First-analysis-complete-20210704/spades_all_taxa/all_taxa_incomplete.incomplete
2021-07-06 10:13:42,132 - phyluce_align_add_missing_data_designators - INFO - Argument --input_format: nexus
2021-07-06 10:13:42,132 - phyluce_align_add_missing_data_designators - INFO - Argument --log_path: /home/ryan/Documents/uce-ant-mimic/First-analysis-complete-20210704/spades_all_taxa/log
2021-07-06 10:13:42,132 - phyluce_align_add_missing_data_designators - INFO - Argument --match_count_output: /home/ryan/Documents/uce-ant-mimic/First-analysis-complete-20210704/spades_all_taxa/all_taxa_incomplete.conf
2021-07-06 10:13:42,132 - phyluce_align_add_missing_data_designators - INFO - Argument --min_taxa: 3
2021-07-06 10:13:42,132 - phyluce_align_add_missing_data_designators - INFO - Argument --missing_character: ?
2021-07-06 10:13:42,132 - phyluce_align_add_missing_data_designators - INFO - Argument --output: /home/ryan/Documents/uce-ant-mimic/First-analysis-complete-20210704/spades_all_taxa/mafft-nexus-60p-with-missing
2021-07-06 10:13:42,132 - phyluce_align_add_missing_data_designators - INFO - Argument --output_format: nexus
2021-07-06 10:13:42,132 - phyluce_align_add_missing_data_designators - INFO - Argument --verbatim: False
2021-07-06 10:13:42,132 - phyluce_align_add_missing_data_designators - INFO - Argument --verbosity: INFO
2021-07-06 10:13:43,318 - phyluce_align_add_missing_data_designators - INFO - Getting taxon names from --match-count-output
2021-07-06 10:13:43,318 - phyluce_align_add_missing_data_designators - INFO - Getting alignment files
2021-07-06 10:13:43,320 - phyluce_align_add_missing_data_designators - INFO - Adding missing data designators using 24 cores
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ryan/miniconda3/envs/phyluce-1.7.1/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ryan/miniconda3/envs/phyluce-1.7.1/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/ryan/miniconda3/envs/phyluce-1.7.1/bin/phyluce_align_add_missing_data_designators", line 208, in add_designators
    missing_character,
  File "/home/ryan/miniconda3/envs/phyluce-1.7.1/bin/phyluce_align_add_missing_data_designators", line 163, in add_gaps_to_align
    local_organisms.remove(new_seq_name)
ValueError: list.remove(x): x not in list
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ryan/miniconda3/envs/phyluce-1.7.1/bin/phyluce_align_add_missing_data_designators", line 288, in <module>
    main()
  File "/home/ryan/miniconda3/envs/phyluce-1.7.1/bin/phyluce_align_add_missing_data_designators", line 271, in main
    results = pool.map(add_designators, work)
  File "/home/ryan/miniconda3/envs/phyluce-1.7.1/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/ryan/miniconda3/envs/phyluce-1.7.1/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ValueError: list.remove(x): x not in list```

**Comment by brantfaircloth** [comment]
you can just skip this step with no problems - it was needed for a while but is not needed any longer.

**Comment by shofmon88** [comment]
Great, good to know. I'll proceed without it.
