### ISSUE TITLE
I am new with Phyluce and I need your help, please

### ISSUE THREAD

**Issue by luishdez35** [faircloth-lab/phyluce#239]
**I try to run the tutorial and, in the assemble I obtain this:**

(phyluce-1.7.1) luiscarloshernandez@MacBook-Air-de-Luis uce-tutorial % phyluce_assembly_assemblo_spades \
    --conf assembly.conf \
    --output spades-assemblies \
    --cores 2
2021-07-19 18:55:20,842 - phyluce_assembly_assemblo_spades - INFO - =========== Starting phyluce_assembly_assemblo_spades ===========
2021-07-19 18:55:20,843 - phyluce_assembly_assemblo_spades - INFO - Version: 1.7.1
2021-07-19 18:55:20,843 - phyluce_assembly_assemblo_spades - INFO - Commit: None
2021-07-19 18:55:20,843 - phyluce_assembly_assemblo_spades - INFO - Argument --config: /Users/luiscarloshernandez/uce-tutorial/assembly.conf
2021-07-19 18:55:20,843 - phyluce_assembly_assemblo_spades - INFO - Argument --cores: 2
2021-07-19 18:55:20,844 - phyluce_assembly_assemblo_spades - INFO - Argument --dir: None
2021-07-19 18:55:20,844 - phyluce_assembly_assemblo_spades - INFO - Argument --log_path: None
2021-07-19 18:55:20,844 - phyluce_assembly_assemblo_spades - INFO - Argument --memory: 8
2021-07-19 18:55:20,844 - phyluce_assembly_assemblo_spades - INFO - Argument --no_clean: False
2021-07-19 18:55:20,844 - phyluce_assembly_assemblo_spades - INFO - Argument --output: /Users/luiscarloshernandez/uce-tutorial/spades-assemblies
2021-07-19 18:55:20,844 - phyluce_assembly_assemblo_spades - INFO - Argument --subfolder:
2021-07-19 18:55:20,844 - phyluce_assembly_assemblo_spades - INFO - Argument --verbosity: INFO
2021-07-19 18:55:20,845 - phyluce_assembly_assemblo_spades - INFO - Getting input filenames and creating output directories
Traceback (most recent call last):
  File "/Users/luiscarloshernandez/opt/anaconda3/envs/phyluce-1.7.1/lib/python3.6/site-packages/phyluce/raw_reads.py", line 173, in get_input_data
    os.path.abspath(os.path.expanduser(sample[1]))
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/luiscarloshernandez/opt/anaconda3/envs/phyluce-1.7.1/bin/phyluce_assembly_assemblo_spades", line 231, in <module>
    main()
  File "/Users/luiscarloshernandez/opt/anaconda3/envs/phyluce-1.7.1/bin/phyluce_assembly_assemblo_spades", line 184, in main
    input_data = get_input_data(args.config, args.dir)
  File "/Users/luiscarloshernandez/opt/anaconda3/envs/phyluce-1.7.1/lib/python3.6/site-packages/phyluce/raw_reads.py", line 176, in get_input_data
    raise IOError("{} is not a directory".format(sample[1]))
OSError: /Users/luiscarloshernandez/uce-tutorial/uce-tutorial/clean-fastq/anolis_carolinensis/split-adapter-quality-trimmed is not a directory

I hope you can help me please.

**Comment by brantfaircloth** [comment]
This error is telling you that the folder/directory at `/Users/luiscarloshernandez/uce-tutorial/uce-tutorial/clean-fastq/anolis_carolinensis/split-adapter-quality-trimmed` does not exist (but the program expects for it to exist and contain clean sequence reads).

**Comment by luishdez35** [comment]
**Thanks a lot for your help, I create de configuration file with this command:** 

```
cd clean-fastq
echo "[samples]" > ../assembly.conf
for i in *; \
   do echo $i":/Users/luiscarloshernandez/uce-tutorial/clean-fastq/"$i"/split-adapter-quality-trimmed/"; \
   done >> ../assembly.conf
```

**Then I update conda and all work again.** 

**I have another question Dr. Faircloth, What Macbook or iMac do you recommend for use Phyluce, with the minimum and maximum requirements. I am a PhD student and i'm learning bioinformatics, so i'm new to a lot of things.
Thanks a lot**

**Comment by brantfaircloth** [comment]
We usually use machines with at least 48 Gb RAM (these are mostly linux machines or HPC cluster machines).  You can get a macbook or imac to work, but you would probably want at least 24 Gb RAM on an imac (and ideally 8-12 compute cores).

**Comment by luishdez35** [comment]
Thanks a lot for your answer.

Cheers

**Comment by brantfaircloth** [comment]
Howdy,

Your config file looks ok, but what is the contents of each folder.  E.g., what does:
```
ls -l /home/tobyhays/uce-tutorial/clean-fastq/alligator_mississippiensis/split-adapter-quality-trimmed/
```
look like?  similarly, what does:
```
ls -l /home/tobyhays/uce-tutorial/clean-fastq/anolis_carolinensis/split-adapter-quality-trimmed/
```
look like?
