### ISSUE TITLE
phyluce_probe_run_multiple_lastzs_sqlite v1.7 issues

### ISSUE THREAD

**Issue by michaelforthman** [faircloth-lab/phyluce#244]
Hi Brant,

 

I've been having trouble getting the phyluce_probe_run_multiple_lastzs_sqlite utility to run on 1.7.0 and 1.7.1.

 

For 1.7.0, I specify an output directory to be created when running the job, but it never creates the folder and terminates because it cannot locate it. If I re-run the job after manually created it on UF's cloud-computer, it terminates because the output directory already exists.

 

For 1.7.1, there seems to be some issue with sqlite, but I'm not sure what is causing the problem (neither does our cloud-computing staff):

 

Traceback (most recent call last):

  File "/apps/phyluce/1.7.1/bin/phyluce_probe_run_multiple_lastzs_sqlite", line 297, in <module>

    main()

  File "/apps/phyluce/1.7.1/bin/phyluce_probe_run_multiple_lastzs_sqlite", line 286, in main

    align_against_scaffolds(log, cur, args, path)

  File "/apps/phyluce/1.7.1/bin/phyluce_probe_run_multiple_lastzs_sqlite", line 225, in align_against_scaffolds

    create_species_lastz_tables(cur, g)

  File "/apps/phyluce/1.7.1/bin/phyluce_probe_run_multiple_lastzs_sqlite", line 148, in create_species_lastz_tables

    cur.execute(query)

sqlite3.OperationalError: near "-": syntax error

 

Cheers, Michael

**Comment by brantfaircloth** [comment]
Looks like in 1.7.1 there may be a hyphen in your taxon names?

**Comment by michaelforthman** [comment]
Thanks, that was the issue!
