### ISSUE TITLE
unmix fasta reads errors

### ISSUE THREAD

**Issue by michaelforthman** [faircloth-lab/phyluce#247]
Hi Brant,

I'm getting some errors when attempting to unmix fasta reads, with error messages varying between different phyluce versions.

1.7.1 and 1.7.0 error:

> Traceback (most recent call last):
>   File "/apps/phyluce/1.7.1/bin/phyluce_utilities_unmix_fasta_reads", line 155, in <module>
>     main()
>   File "/apps/phyluce/1.7.1/bin/phyluce_utilities_unmix_fasta_reads", line 116, in main
>     temp_handle2, ">{}\n{}\n".format(record.description, record.seq)
> TypeError: a bytes-like object is required, not 'str'

Earlier versions error:

> Traceback (most recent call last):
>   File "/apps/phyluce/1.7.1/bin/phyluce_utilities_unmix_fasta_reads", line 155, in <module>
>     main()
>   File "/apps/phyluce/1.7.1/bin/phyluce_utilities_unmix_fasta_reads", line 116, in main
>     temp_handle2, ">{}\n{}\n".format(record.description, record.seq)
> TypeError: a bytes-like object is required, not 'str'

Below is an example of how my fasta files are formatted and my job code:

> >SRR2051471_67/1
> CGGCAATTTTTATTTTCGCCTGTTTAACAAAAACATGTCCTATAGATTTAATTTTAGGTTTAATCTGCTCAGTGATAATTTATAATTAAATAGCCGCAGTATTTTGACTGTGCAAAGGGAGCATAATCATTTGTCTTTTAATTTAAGGCT
> >SRR2051471_168/1
> TTCTCGTCTAACAAAAAAATTTTAGCATTTTAACTAAAAATTTAAATTCAAAATACTCAAGTAAAGAAAGTCTATTTTTCGTCCAATCATTCATACAAGCCTTCAATTAAAAGACAAATGATTATGCTACCTTTGCACAGTCACAATACT

`phyluce_utilities_unmix_fasta_reads --mixed-reads /blue/cwmiller/mforthman/coreoidea_phylogenomics_part2/genomic_transcriptomic_reads_for_mapping/quorum_output/Arocatus_melanocephalus_SRR2051471_mapped_reads_corrected.fasta --out-r1 /blue/cwmiller/mforthman/coreoidea_phylogenomics_part2/genomic_transcriptomic_reads_for_mapping/quorum_output/Arocatus_melanocephalus_SRR2051471_mapped_corrected_R1.fasta --out-r2 /blue/cwmiller/mforthman/coreoidea_phylogenomics_part2/genomic_transcriptomic_reads_for_mapping/quorum_output/Arocatus_melanocephalus_SRR2051471_mapped_corrected_R2.fasta --out-r-singleton /blue/cwmiller/mforthman/coreoidea_phylogenomics_part2/genomic_transcriptomic_reads_for_mapping/quorum_output/Arocatus_melanocephalus_SRR2051471_mapped_corrected_singles.fasta`

Is there an issue with my fasta file or code that I'm not seeing?

Thanks, Michael

**Comment by michaelforthman** [comment]
Also, I have ">" at the beginning of each fasta header. For some reason github keeps interpreting it as a quote and removes it.

**Comment by brantfaircloth** [comment]
Part of this is an issue with moving to python3.  That said, I would use another tool to split these reads - I'm likely to just remove this code in an updated version.  I'd look into seqtk (should come w/ phyluce), bbmap, or you could use something like galaxy (https://galaxyproject.org/support/ncbi-sra-fastq/#interleaved-forward-and-reverse-reads).

For example, in seqtk, you would do something like:
```
seqtk seq interleaved.fq -1 >  read_1.fq
seqtk seq interleaved.fq -2 >  read_2.fq
```
