### ISSUE TITLE
mapping workflow error

### ISSUE THREAD

**Issue by mprebus** [faircloth-lab/phyluce#248]
Hello Brant,
When attempting to run the mapping workflow with v1.7.1, I get the following error:

Traceback (most recent call last):
  File "/home/mprebus/.conda/envs/phyluce-1.7.1/bin/phyluce_workflow", line 19, in <module>
    from phyluce.helpers import FullPaths, CreateDir, is_dir, is_file
  File "/home/mprebus/.conda/envs/phyluce-1.7.1/lib/python3.6/site-packages/phyluce/helpers.py", line 20, in <module>
    from rich import prompt
  File "/home/mprebus/.conda/envs/phyluce-1.7.1/lib/python3.6/site-packages/rich/prompt.py", line 4, in <module>
    from .console import Console
  File "/home/mprebus/.conda/envs/phyluce-1.7.1/lib/python3.6/site-packages/rich/console.py", line 9, in <module>
    from dataclasses import dataclass, field, replace
ModuleNotFoundError: No module named 'dataclasses'

I noticed that 'dataclasses' is part of the Python 3.7 release, but v1.7.1 uses 3.6. Is this the issue?

**Comment by brantfaircloth** [comment]
Technically, this should not be an issue if installed as suggested.  But it’s possible something slipped through the cracks.  You could activate the conda environment for phyluce, and then try:

pip install dataclasses

and see if that works.
