### ISSUE TITLE
Phyluce_assembly_match_contigs_to_probes - 'NoneType' object has no attribute 'groups' error

### ISSUE THREAD

**Issue by hutumpyancha** [faircloth-lab/phyluce#256]
Dear Dr. Faircloth,

I am getting the mentioned error everytime I am trying to match the probes to my contigs. I saw that similar issues had been previously discussed on this page and on one such occassion, you had suggested making changes to the phyluce.config file. However, I am not sure I am understanding clearly what changes I should make and why. If you could assist me again with this error, it would be really helpful. 
The details are as follows - 

(phyluce-1.7.1) [upasanag@qb2 upasanag]$ phyluce_assembly_match_contigs_to_probes   --contigs /work/upasanag/spades-assemblies/contigs --probes /work/upasanag/190611-70B-OctoV2-Quattrini-baits.fas   --output uce-search-results
2021-10-28 17:19:30,606 - phyluce_assembly_match_contigs_to_probes - INFO - ======= Starting phyluce_assembly_match_contigs_to_probes =======
2021-10-28 17:19:30,607 - phyluce_assembly_match_contigs_to_probes - INFO - Version: 1.7.1
2021-10-28 17:19:30,607 - phyluce_assembly_match_contigs_to_probes - INFO - Commit: None
2021-10-28 17:19:30,607 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --contigs: /work/upasanag/spades-assemblies/contigs
2021-10-28 17:19:30,608 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --csv: None
2021-10-28 17:19:30,608 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --dupefile: None
2021-10-28 17:19:30,608 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --keep_duplicates: None
2021-10-28 17:19:30,608 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --log_path: None
2021-10-28 17:19:30,608 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --min_coverage: 80
2021-10-28 17:19:30,609 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --min_identity: 80
2021-10-28 17:19:30,609 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --output: /ddnA/qb2work/upasanag/uce-search-results
2021-10-28 17:19:30,609 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --probes: /work/upasanag/190611-70B-OctoV2-Quattrini-baits.fas
2021-10-28 17:19:30,609 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --regex: ^(uce-\d+)(?:_p\d+.*)
2021-10-28 17:19:30,610 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --verbosity: INFO
Traceback (most recent call last):
  File "/home/upasanag/.conda/envs/phyluce-1.7.1/bin/phyluce_assembly_match_contigs_to_probes", line 421, in <module>
    main()
  File "/home/upasanag/.conda/envs/phyluce-1.7.1/bin/phyluce_assembly_match_contigs_to_probes", line 293, in main
    for seq in SeqIO.parse(open(args.probes, "rU"), "fasta")
  File "/home/upasanag/.conda/envs/phyluce-1.7.1/bin/phyluce_assembly_match_contigs_to_probes", line 293, in <genexpr>
    for seq in SeqIO.parse(open(args.probes, "rU"), "fasta")
  File "/home/upasanag/.conda/envs/phyluce-1.7.1/bin/phyluce_assembly_match_contigs_to_probes", line 284, in new_get_probe_name
    return match.groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by hutumpyancha** [comment]
Thank you so much for your suggestion; I contacted her and now it seems to work with a different version of the probes fasta file.
