### ISSUE TITLE
Issue in Quality Control

### ISSUE THREAD

**Issue by luishdez35** [faircloth-lab/phyluce#260]
Hello, I have one issue running the quality control part for the tutorial.

`for i in *;
do
    phyluce_assembly_get_fastq_lengths --input $i/split-adapter-quality-trimmed/ --csv;
done`

**For every sample (species) i has the same error** 

Traceback (most recent call last):
  File "/Users/luiscarloshernandez/opt/anaconda3/envs/phyluce-2/bin/phyluce_assembly_get_fastq_lengths", line 106, in <module>
    main()
  File "/Users/luiscarloshernandez/opt/anaconda3/envs/phyluce-2/bin/phyluce_assembly_get_fastq_lengths", line 68, in main
    lengths = numpy.array(lengths)
UnboundLocalError: local variable 'lengths' referenced before assignment

**I read in other issue post that I need to modify the code for  phyluce_assembly_get_fastq_lengths, but I don't know how do that, I hope you can help me. Thanks a lot**

**Comment by brantfaircloth** [comment]
Yes, I am not sure I have fixed this issue... you can safely skip this step.

**Comment by luishdez35** [comment]
Thanks for the quick answer, yes I skip this step, buy actually I need the stats, do you think FastQC work? Or do you known other option, 

Thanks a lot!!
