### ISSUE TITLE
Issue in the assembly

### ISSUE THREAD

**Issue by luishdez35** [faircloth-lab/phyluce#263]
**Hi, I try to run Phyluce on my school cluster, and I get the next error file.**

Traceback (most recent call last):
  File "/LUSTRE/apps/Anaconda/2021/miniconda3/envs/phyluce-1.7.1/bin/phyluce_assembly_assemblo_spades", line 231, in <module>
    main()
  File "/LUSTRE/apps/Anaconda/2021/miniconda3/envs/phyluce-1.7.1/bin/phyluce_assembly_assemblo_spades", line 184, in main
    input_data = get_input_data(args.config, args.dir)
  File "/LUSTRE/apps/Anaconda/2021/miniconda3/envs/phyluce-1.7.1/lib/python3.6/site-packages/phyluce/raw_reads.py", line 164, in get_input_data
    conf.read(config)
  File "/LUSTRE/apps/Anaconda/2021/miniconda3/envs/phyluce-1.7.1/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/LUSTRE/apps/Anaconda/2021/miniconda3/envs/phyluce-1.7.1/lib/python3.6/configparser.py", line 1111, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/assembly.conf'
	[line  2]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Paraphidippus_aurantius_DGF0448/split-adapter-quality-trimmed/\n'
	[line  3]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_adonis_DGF0948/split-adapter-quality-trimmed/\n'
	[line  4]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_adumbratus_Ph076/split-adapter-quality-trimmed/\n'
	[line  5]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_albulatus_DGF0950/split-adapter-quality-trimmed/\n'
	[line  6]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_ardens_DGF1277/split-adapter-quality-trimmed/\n'
	[line  7]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_arizonensis_DGF1275/split-adapter-quality-trimmed/\n'
	[line  8]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_asotus_DGF1278/split-adapter-quality-trimmed/\n'
	[line  9]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_audax_WPM0017/split-adapter-quality-trimmed/\n'
	[line 10]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_aureus_DGF1280/split-adapter-quality-trimmed/\n'
	[line 11]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_bidentatus_1401/split-adapter-quality-trimmed/\n'
	[line 12]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_bidentatus_DGF0812/split-adapter-quality-trimmed/\n'
	[line 13]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_bidentatus_DGF0953/split-adapter-quality-trimmed/\n'
	[line 14]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_boei_Ph120/split-adapter-quality-trimmed/\n'
	[line 15]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_borealis_WPM0019/split-adapter-quality-trimmed/\n'
	[line 16]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_californicus_Ph106/split-adapter-quality-trimmed/\n'
	[line 17]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_carneus_1292/split-adapter-quality-trimmed/\n'
	[line 18]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_carneus_DGF0986/split-adapter-quality-trimmed/\n'
	[line 19]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_comatus_DGF1289/split-adapter-quality-trimmed/\n'
	[line 20]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_concinnus_DGF1287/split-adapter-quality-trimmed/\n'
	[line 21]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_cruentus_DGF0499/split-adapter-quality-trimmed/\n'
	[line 22]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_georgii_DGF0951/split-adapter-quality-trimmed/\n'
	[line 23]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_johnsoni_WPM0018/split-adapter-quality-trimmed/\n'
	[line 24]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_kastoni_DGF1283/split-adapter-quality-trimmed/\n'
	[line 25]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_purpuratus_WPM0020/split-adapter-quality-trimmed/\n'
	[line 26]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_sp5_Ph123/split-adapter-quality-trimmed/\n'
	[line 27]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_tigris_DGF1271/split-adapter-quality-trimmed/\n'
	[line 28]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_ursulus_DGF1270/split-adapter-quality-trimmed/\n'
	[line 29]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_texanus_DGF1273/split-adapter-quality-trimmed/\n'
	[line 30]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_ursulus_DGF1270/split-adapter-quality-trimmed/\n'
	[line 31]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_zethus_DGF0944/split-adapter-quality-trimmed/\n'
	[line 32]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_cardinalis_DGF1288/split-adapter-quality-trimmed/\n'
	[line 33]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_carneus_1290/split-adapter-quality-trimmed/\n'
	[line 34]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_cerberus_DGF0947/split-adapter-quality-trimmed/\n'
	[line 35]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_comatus_DGF0945/split-adapter-quality-trimmed/\n'
	[line 36]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_cruentus_DGF0555/split-adapter-quality-trimmed/\n'
	[line 37]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_felinus_DGF1285/split-adapter-quality-trimmed/\n'
	[line 38]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_maddisoni_DGF0946/split-adapter-quality-trimmed/\n'
	[line 39]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_mimicus_DGF0954/split-adapter-quality-trimmed/\n'
	[line 40]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_morpheus_DGF1281/split-adapter-quality-trimmed/\n'
	[line 41]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_nikites_Ph018/split-adapter-quality-trimmed/\n'
	[line 42]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_octopunctatus_DGF1269/split-adapter-quality-trimmed/\n'
	[line 43]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_nikites_DGF1279/split-adapter-quality-trimmed/\n'
	[line 44]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_octopunctatus_Ph138/split-adapter-quality-trimmed/\n'
	[line 45]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_phoenix_Ph033/split-adapter-quality-trimmed/\n'
	[line 46]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_pius_DGF1274/split-adapter-quality-trimmed/\n'
	[line 47]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_purpuratus_WPM0021/split-adapter-quality-trimmed/\n'
	[line 48]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_sp3_Ph089/split-adapter-quality-trimmed/\n'
	[line 49]: '/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_sp4_Ph094/split-adapter-quality-trimmed/\n'

**My conf file is like this** 

[samples]
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Paraphidippus_aurantius_DGF0448/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_adonis_DGF0948/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_adumbratus_Ph076/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_albulatus_DGF0950/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_ardens_DGF1277/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_arizonensis_DGF1275/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_asotus_DGF1278/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_audax_WPM0017/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_aureus_DGF1280/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_bidentatus_1401/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_bidentatus_DGF0812/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_bidentatus_DGF0953/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_boei_Ph120/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_borealis_WPM0019/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_californicus_Ph106/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_carneus_1292/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_carneus_DGF0986/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_comatus_DGF1289/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_concinnus_DGF1287/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_cruentus_DGF0499/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_georgii_DGF0951/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_johnsoni_WPM0018/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_kastoni_DGF1283/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_purpuratus_WPM0020/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_sp5_Ph123/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_tigris_DGF1271/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_ursulus_DGF1270/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_texanus_DGF1273/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_ursulus_DGF1270/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_zethus_DGF0944/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_cardinalis_DGF1288/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_carneus_1290/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_cerberus_DGF0947/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_comatus_DGF0945/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_cruentus_DGF0555/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_felinus_DGF1285/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_maddisoni_DGF0946/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_mimicus_DGF0954/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_morpheus_DGF1281/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_nikites_Ph018/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_octopunctatus_DGF1269/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_nikites_DGF1279/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_octopunctatus_Ph138/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_phoenix_Ph033/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_pius_DGF1274/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_purpuratus_WPM0021/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_sp3_Ph089/split-adapter-quality-trimmed/
/LUSTRE/bioinformatica_data/biogeografia/luiscarloshdez/phidippus/FirstPlate_UCEs/Data/clean-fastq/Phidippus_sp4_Ph094/split-adapter-quality-trimmed/

**Thanks a lot for your help**

**Comment by luishdez35** [comment]
I think I solve this issue, I'm gonna close it.
