### ISSUE TITLE
error in Final data matrices

### ISSUE THREAD

**Issue by luishdez35** [faircloth-lab/phyluce#265]
Hello, I get this error message when I try to run the final data matrices instruction, but the funny thing is that it extracts the nexus files in a folder, so I don't know why it gives me this error, if everything seems to do it right, can you please give me a north about this error, by the way, this happens with matrices at 50, 60, 70, 80 and 90 percent. 

Thanks a lot

`--- Logging error ---
Traceback (most recent call last):
  File "/LUSTRE/apps/Anaconda/2021/miniconda3/envs/phyluce-1.7.1/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2265' in position 132: ordinal not in range(128)
Call stack:
  File "/LUSTRE/apps/Anaconda/2021/miniconda3/envs/phyluce-1.7.1/bin/phyluce_align_get_only_loci_with_min_taxa", line 128, in <module>
    main()
  File "/LUSTRE/apps/Anaconda/2021/miniconda3/envs/phyluce-1.7.1/bin/phyluce_align_get_only_loci_with_min_taxa", line 119, in main
    sum(results), len(results), args.percent, min_count
Message: 'Copied 814 alignments of 1533 total containing \u2265 0.5 proportion of taxa (n = 22)'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/LUSTRE/apps/Anaconda/2021/miniconda3/envs/phyluce-1.7.1/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2265' in position 124: ordinal not in range(128)
Call stack:
  File "/LUSTRE/apps/Anaconda/2021/miniconda3/envs/phyluce-1.7.1/bin/phyluce_align_get_only_loci_with_min_taxa", line 128, in <module>
    main()
  File "/LUSTRE/apps/Anaconda/2021/miniconda3/envs/phyluce-1.7.1/bin/phyluce_align_get_only_loci_with_min_taxa", line 119, in main
    sum(results), len(results), args.percent, min_count
Message: 'Copied 814 alignments of 1533 total containing \u2265 0.5 proportion of taxa (n = 22)'
Arguments: ()`

**Comment by brantfaircloth** [comment]
This is an encoding error that is sometimes kicked off on certain platforms - for a variety of reasons.  Basically, it is saying that the "≥" character (which is unicode character `\u2265`) cannot be converted to "≥" appropriately on the platform where you are running it.

I've made some slight changes to the code that will make it to the next version, but you can safely ignore this error in the meantime.

**Comment by luishdez35** [comment]
Thanks a lot for the clarification.

**Comment by brantfaircloth** [comment]
You bet!
