### ISSUE TITLE
Issue in "phyluce_assembly_get_match_counts"

### ISSUE THREAD

**Issue by claudiavaga** [faircloth-lab/phyluce#274]
Hello!

I am getting an error running the program "phyluce_assembly_get_match_counts"

This is what I am getting:

phyluce_assembly_get_match_counts \
> --locus-db /home/geninfo/cvaga/assemblies/uce-search-todas/probe.matches.sqlite \
> --taxon-list-config /home/geninfo/cvaga/assemblies/taxon-set-todas.conf \
> --taxon-group 'all' \
> --incomplete-matrix \
> --output /home/geninfo/cvaga/assemblies/taxon-sets-todas/all/all-taxa-incomplete.conf \
> --log-path /home/geninfo/cvaga/assemblies/log_todas

2022-04-30 16:20:12,659 - phyluce_assembly_get_match_counts - INFO - =========== Starting phyluce_assembly_get_match_counts ==========
2022-04-30 16:20:12,660 - phyluce_assembly_get_match_counts - INFO - Version: git fatal: Not a git repository: '/home/geninfo/cvaga/.conda/envs/phyluce/lib/python2.7/site-packages/.git'
2022-04-30 16:20:12,660 - phyluce_assembly_get_match_counts - INFO - Argument --extend_locus_db: None
2022-04-30 16:20:12,660 - phyluce_assembly_get_match_counts - INFO - Argument --incomplete_matrix: True
2022-04-30 16:20:12,660 - phyluce_assembly_get_match_counts - INFO - Argument --keep_counts: False
2022-04-30 16:20:12,660 - phyluce_assembly_get_match_counts - INFO - Argument --locus_db: /home/geninfo/cvaga/assemblies/uce-search-todas/probe.matches.sqlite
2022-04-30 16:20:12,661 - phyluce_assembly_get_match_counts - INFO - Argument --log_path: /home/geninfo/cvaga/assemblies/log_todas
2022-04-30 16:20:12,661 - phyluce_assembly_get_match_counts - INFO - Argument --optimize: False
2022-04-30 16:20:12,661 - phyluce_assembly_get_match_counts - INFO - Argument --output: /home/geninfo/cvaga/assemblies/taxon-sets-todas/all/all-taxa-incomplete.conf
2022-04-30 16:20:12,661 - phyluce_assembly_get_match_counts - INFO - Argument --random: False
2022-04-30 16:20:12,661 - phyluce_assembly_get_match_counts - INFO - Argument --sample_size: 10
2022-04-30 16:20:12,662 - phyluce_assembly_get_match_counts - INFO - Argument --samples: 10
2022-04-30 16:20:12,662 - phyluce_assembly_get_match_counts - INFO - Argument --silent: False
2022-04-30 16:20:12,662 - phyluce_assembly_get_match_counts - INFO - Argument --taxon_group: all
2022-04-30 16:20:12,662 - phyluce_assembly_get_match_counts - INFO - Argument --taxon_list_config: /home/geninfo/cvaga/assemblies/taxon-set-todas.conf
2022-04-30 16:20:12,662 - phyluce_assembly_get_match_counts - INFO - Argument --verbosity: INFO
2022-04-30 16:20:12,666 - phyluce_assembly_get_match_counts - INFO - There are 243 taxa in the taxon-group '[all]' in the config file taxon-set-todas.conf
2022-04-30 16:20:12,667 - phyluce_assembly_get_match_counts - INFO - Getting UCE names from database
2022-04-30 16:20:12,671 - phyluce_assembly_get_match_counts - INFO - There are 2490 total UCE loci in the database
Traceback (most recent call last):
  File "/home/geninfo/cvaga/.conda/envs/phyluce/bin/phyluce_assembly_get_match_counts", line 351, in <module>
    main()
  File "/home/geninfo/cvaga/.conda/envs/phyluce/bin/phyluce_assembly_get_match_counts", line 339, in main
    shared_uces = dont_sample_match_groups(log, args, c, organisms, uces)
  File "/home/geninfo/cvaga/.conda/envs/phyluce/bin/phyluce_assembly_get_match_counts", line 286, in dont_sample_match_groups
    organismal_matches = get_all_matches_by_organism(c, organisms)
  File "/home/geninfo/cvaga/.conda/envs/phyluce/bin/phyluce_assembly_get_match_counts", line 161, in get_all_matches_by_organism
    c.execute("SELECT uce FROM matches WHERE {0} = 1".format(organism))
sqlite3.OperationalError: near "=": syntax error

Do you know what it might be happening?
I am attaching also the conf file and the probe.matches.sqlite file!

Thank you in advance for your help!

[probe.matches.sqlite-text.txt](https://github.com/faircloth-lab/phyluce/files/8600498/probe.matches.sqlite-text.txt)
[taxon-set-toda.txt](https://github.com/faircloth-lab/phyluce/files/8600486/taxon-set-toda.txt)

**Comment by claudiavaga** [comment]
Found the error! Headers problem:)
