### ISSUE TITLE
ValueError: Invalid alphabet, 'DNA'

### ISSUE THREAD

**Issue by a-cabrero** [faircloth-lab/phyluce#283]
Hello, 
Following the tutorial, I've ran into an issue when trying to build the concatenated data set using `phyluce_align_concatenate_alignments`.  I keep getting an error that says `ValueError: Invalid alphabet, 'DNA'`, I think it has to do with biopython, I've tried updated it, uninstalling phyluce, reinstalling, etc but I am not sure what to do to fix it. I should also mention I've also gotten a similar error when trying to use the `phyluce_align_convert_one_align_to_another` command.

Thank you, Appreciate the help!

My code and error:

>(phyluce-1.7.1) 
>phyluce_align_concatenate_alignments \
>     --alignments /lv1/acabrero/UCEworking/01.RawData/clean_fastq/fastp_clean/metaspades-fastp-clean/taxon-sets/mafft-nexus-edge-no-trimmed/fasta_trimmed/fasta_clean/mafft-nexus-internal-trimmed-clean-75p \
>     --input-format fasta \
>     --output 75p-concat \
>     --phylip 
2022-10-26 04:13:05,378 - phyluce_align_concatenate_alignments - INFO - ========= Starting phyluce_align_concatenate_alignments =========
2022-10-26 04:13:05,379 - phyluce_align_concatenate_alignments - INFO - Version: 1.7.1
2022-10-26 04:13:05,379 - phyluce_align_concatenate_alignments - INFO - Commit: None
2022-10-26 04:13:05,379 - phyluce_align_concatenate_alignments - INFO - Argument --alignments: /lv1/acabrero/UCEworking/01.RawData/clean_fastq/fastp_clean/metaspades-fastp-clean/taxon-sets/mafft-nexus-edge-no-trimmed/fasta_trimmed/fasta_clean/mafft-nexus-internal-trimmed-clean-75p
2022-10-26 04:13:05,379 - phyluce_align_concatenate_alignments - INFO - Argument --input_format: fasta
2022-10-26 04:13:05,379 - phyluce_align_concatenate_alignments - INFO - Argument --log_path: None
2022-10-26 04:13:05,379 - phyluce_align_concatenate_alignments - INFO - Argument --nexus: False
2022-10-26 04:13:05,380 - phyluce_align_concatenate_alignments - INFO - Argument --output: /lv1/acabrero/UCEworking/01.RawData/clean_fastq/fastp_clean/metaspades-fastp-clean/taxon-sets/mafft-nexus-edge-no-trimmed/fasta_trimmed/fasta_trimmed_phycom/75p-concat
2022-10-26 04:13:05,380 - phyluce_align_concatenate_alignments - INFO - Argument --phylip: True
2022-10-26 04:13:05,380 - phyluce_align_concatenate_alignments - INFO - Argument --verbosity: INFO
2022-10-26 04:13:05,380 - phyluce_align_concatenate_alignments - INFO - Reading input alignments in NEXUS format
2022-10-26 04:13:05,380 - phyluce_align_concatenate_alignments - INFO - Getting alignment files
Traceback (most recent call last):
  File "/home/acabrero/miniconda3/envs/phyluce-1.7.1/bin/phyluce_align_concatenate_alignments", line 147, in <module>
    main()
  File "/home/acabrero/miniconda3/envs/phyluce-1.7.1/bin/phyluce_align_concatenate_alignments", line 105, in main
    fname, args.input_format, temp_name, "nexus", "DNA"
  File "/usr/lib/python2.7/site-packages/biopython-1.68-py2.7-linux-x86_64.egg/Bio/AlignIO/__init__.py", line 462, in convert
    count = write(alignments, out_handle, out_format)
  File "/usr/lib/python2.7/site-packages/biopython-1.68-py2.7-linux-x86_64.egg/Bio/AlignIO/__init__.py", line 214, in write
    count = writer_class(fp).write_file(alignments)
  File "/usr/lib/python2.7/site-packages/biopython-1.68-py2.7-linux-x86_64.egg/Bio/AlignIO/NexusIO.py", line 82, in write_file
    first_alignment = next(align_iter)
  File "/usr/lib/python2.7/site-packages/biopython-1.68-py2.7-linux-x86_64.egg/Bio/AlignIO/__init__.py", line 343, in parse
    raise ValueError("Invalid alphabet, %s" % repr(alphabet))
ValueError: Invalid alphabet, 'DNA'

**Comment by brantfaircloth** [comment]
The way that you have phyluce and biopython installed may be causing the issues that you are seeing - phyluce 1.7.1 is meant to run w/ Python 3.6 but it seems the biopython you have installed is for Python 2.7 (from the path to your biopython installation).  Additionally, the version of biopython you have installed is 1.68 while the version of biopython needed by the current phyluce (phyluce 1.7.1) is 1.78.

I suspect if you install phyluce as recommended, you will see these issues go away.

**Comment by a-cabrero** [comment]
Hi Brant,

Thank you, I did update biopython and python, and even uninstalled phyluce and installed it exactly as your tutorial recommends. 

I am still getting the same error, it seems like Phyluce is defaulting to Python 2.7 and biopython 1.68, I'm not really sure what to do next to fix that.

**Comment by brantfaircloth** [comment]
Something must be incorrect in the way that python is setup on the machine you are using - if installed correctly (using miniconda) Python should not be able to default to 2.7.  What happens when you run “which python” on the command line?

**Comment by a-cabrero** [comment]
Doing that gives me:
~/miniconda3/bin/python

**Comment by brantfaircloth** [comment]
ok - and when you run “conda activate phyluce” or whatever you called the phyluce environment can you run the same thing again and send me the output?  after activating that environment, can you also send me the output of “echo $PYTHONPATH”?

**Comment by a-cabrero** [comment]
In that /bin directory I do see python and python3 installed

When I type which python in the phyluce environment I get:
(phyluce-1.7.1) which python
~/miniconda3/envs/phyluce-1.7.1/bin/python

Echo command gives: 
(phyluce-1.7.1) echo $PYTHONPATH
:/usr/lib/python2.7/site-packages/biopython-1.68-py2.7-linux-x86_64.egg

**Comment by brantfaircloth** [comment]
ok - you need to find out where that value of PYTHONPATH is getting set (maybe in your .profile, .bash_profile, or .bashrc) and remove or comment out that setting.

**Comment by a-cabrero** [comment]
Thank you! That seems to have worked!

**Comment by brantfaircloth** [comment]
excellent 👍
