### ISSUE TITLE
KeyError with phyluce_probe_slice_sequence_from_genomes

### ISSUE THREAD

**Issue by sunandan-dasgupta** [faircloth-lab/phyluce#289]
Hello all, 
    I am using phyluce_probe_slice_sequence_from_genomes function to extract UCE loci from some scaffolds assembled (using a GATB-minia and Redundans pipeline) from low coverage whole genome sequences. The lastz database preparation stage went fine but when I moved on to the next stage, that is _phyluce_probe_slice_sequence_from_genomes_, I started to get this error: 

phyluce_probe_slice_sequence_from_genomes --lastz /Users/sunandan/Desktop/Fish_taxonomy/fish-genome-lastz --conf /Users/sunandan/Desktop/Fish_taxonomy/genomes.conf --flank 40 --name-pattern "Acanthomorphs-UCE-1Kv1.fasta_v_{}.lastz.clean" --output /Users/sunandan/Desktop/Fish_taxonomy/UCE_genome_fast
2023-01-24 04:18:34,197 - phyluce_probe_slice_sequence_from_genomes - INFO - ======= Starting phyluce_probe_slice_sequence_from_genomes ======
2023-01-24 04:18:34,197 - phyluce_probe_slice_sequence_from_genomes - INFO - Version: 1.7.1
2023-01-24 04:18:34,197 - phyluce_probe_slice_sequence_from_genomes - INFO - Commit: None
2023-01-24 04:18:34,198 - phyluce_probe_slice_sequence_from_genomes - INFO - Argument --conf: /Users/sunandan/Desktop/Fish_taxonomy/genomes.conf
2023-01-24 04:18:34,198 - phyluce_probe_slice_sequence_from_genomes - INFO - Argument --contig_orient: False
2023-01-24 04:18:34,198 - phyluce_probe_slice_sequence_from_genomes - INFO - Argument --exclude: None
2023-01-24 04:18:34,198 - phyluce_probe_slice_sequence_from_genomes - INFO - Argument --flank: 40
2023-01-24 04:18:34,198 - phyluce_probe_slice_sequence_from_genomes - INFO - Argument --lastz: /Users/sunandan/Desktop/Fish_taxonomy/fish-genome-lastz
2023-01-24 04:18:34,198 - phyluce_probe_slice_sequence_from_genomes - INFO - Argument --log_path: None
2023-01-24 04:18:34,198 - phyluce_probe_slice_sequence_from_genomes - INFO - Argument --output: /Users/sunandan/Desktop/Fish_taxonomy/UCE_genome_fast
2023-01-24 04:18:34,198 - phyluce_probe_slice_sequence_from_genomes - INFO - Argument --pattern: Acanthomorphs-UCE-1Kv1.fasta_v_{}.lastz.clean
2023-01-24 04:18:34,198 - phyluce_probe_slice_sequence_from_genomes - INFO - Argument --probe_prefix: uce-
2023-01-24 04:18:34,198 - phyluce_probe_slice_sequence_from_genomes - INFO - Argument --probe_regex: ^({}\d+)(?:_p\d+.*)
2023-01-24 04:18:34,198 - phyluce_probe_slice_sequence_from_genomes - INFO - Argument --probes: None
2023-01-24 04:18:34,198 - phyluce_probe_slice_sequence_from_genomes - INFO - Argument --verbosity: INFO
2023-01-24 04:18:34,198 - phyluce_probe_slice_sequence_from_genomes - INFO - =================== Starting Phyluce: Slice Sequence ===================
2023-01-24 04:18:34,199 - phyluce_probe_slice_sequence_from_genomes - INFO - ------------- Working on FIN_UKO_38_scaffolds genome ------------
2023-01-24 04:18:34,199 - phyluce_probe_slice_sequence_from_genomes - INFO - Reading FIN_UKO_38_scaffolds genome
Traceback (most recent call last):
  File "/Users/sunandan/.conda/envs/phyluce-1.7.1/bin/phyluce_probe_slice_sequence_from_genomes", line 400, in <module>
    main()
  File "/Users/sunandan/.conda/envs/phyluce-1.7.1/bin/phyluce_probe_slice_sequence_from_genomes", line 364, in main
    args.probes,
  File "/Users/sunandan/.conda/envs/phyluce-1.7.1/bin/phyluce_probe_slice_sequence_from_genomes", line 153, in slice_and_return_fasta
    if max + flank < len(tb[name.encode()]):
  File "/Users/sunandan/.conda/envs/phyluce-1.7.1/lib/python3.6/site-packages/bx/seq/twobit.py", line 83, in __getitem__
    seq = self.index[name]
KeyError: b'scaffold45'

I tried a dataset without the particular sample it is complaining about but it gave the same result. Now, it would be surprising if all my samples have some kind issue with their scaffolds! They are prepared following Phyluce site guidelines (that is, faToTwoBits etc) and also previous Phyluce steps went smoothly. In fact, I am not even completely new to Phyluce (I have used Phyluce in my past papers) and I also looked into any specific scaffold it is complaining about in the fasta file but found everything is fine there, at least as far as visually checking the format is concerned. If you kindly advise me what is going wrong, I shall remain grateful.
Many thanks in advance,
Sunandan

**Comment by sunandan-dasgupta** [comment]
Dear Prof. Faircloth,
    Thank you so much for the prompt response. I have tried the command you suggested on both a Linux (Ubuntu) and a Mac workstation but I got this error message,
    (phyluce-1.7.1) sunandan@sunandanpc:~$ conda update bx-python=0.9.0

CondaError: Invalid spec for 'conda update': bx-python=0.9.0
Use 'conda install' instead.
 
and hence, I could still not resolve the issue of that key error complaining about some scaffold. I am sorry to bother you again but could you please suggest any workaround?
Thannks

**Comment by brantfaircloth** [comment]
Try:

conda update bx-python

**Comment by sunandan-dasgupta** [comment]
This time the update apparently worked (it basically said everything is already up to date!). But the problem persists, I am still getting the error:
'Traceback (most recent call last):
  File "/home/sunandan/anaconda3/envs/phyluce-1.7.1/bin/phyluce_probe_slice_sequence_from_genomes", line 400, in <module>
    main()
  File "/home/sunandan/anaconda3/envs/phyluce-1.7.1/bin/phyluce_probe_slice_sequence_from_genomes", line 364, in main
    args.probes,
  File "/home/sunandan/anaconda3/envs/phyluce-1.7.1/bin/phyluce_probe_slice_sequence_from_genomes", line 153, in slice_and_return_fasta
    if max + flank < len(tb[name.encode()]):
  File "/home/sunandan/anaconda3/envs/phyluce-1.7.1/lib/python3.6/site-packages/bx/seq/twobit.py", line 83, in __getitem__
    seq = self.index[name]
KeyError: b'scaffold189'

    I would like to attach one of the 2bit (and the corresponding fasta) scaffolds so that you could take a look if your time permits but that cannot be done on github as it does not permit attaching that kind of files. But I don't really see a problem with these file formats. In fact, it is weird how everytime phyluce complains with any one scaffold but not all from a particular assembly (which differs in different analyses depending on which assembly I put first in the config file) and quits. I understand I am really bothering with you with this problem at this point but I will really appreciate if you kindly bear with this a bit more!

**Comment by brantfaircloth** [comment]
That process did not update the code (everything is actually not up-to-date).  Try:
```
conda install bx-python=0.9.0
```
and see if that gets it.  You need to get the new version of bx-python to fix the error.

**Comment by sunandan-dasgupta** [comment]
Prof. Faircloth,
    Thanks! I tried what you suggested here:
"(phyluce-1.7.1) lm9-576-002:~ sunandan$ conda install bx-python=0.9.0
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed."
    And as you can see, it again says it is 'already installed'! And the problem (KeyError with 'scaffoldXYZ' persists as I anticipated. Also does not seem to be an issue with my system as I tried on two different OS in two computers. Well, it unfortunately seems like there is no way out for the time being 😔.

**Comment by brantfaircloth** [comment]
can you post a link to this assembly or a couple of scaffolds (including scaffold189 that’s throwing the error)?  i’ll see if I can reproduce and then send you a fix.

**Comment by sunandan-dasgupta** [comment]
Sure Prof. Faircloth, here it is https://helsinkifi-my.sharepoint.com/:f:/g/personal/sunandan_ad_helsinki_fi/EjV56pAatt1MsE5hWwEmR9oBv-XQzXDbisNJXAErKEaOdw?e=YlSgIC . Let me know if it does not work (university IT systems are a bit overprotective!). I have included four scaffolds in fasta format in it. This includes a latest one that threw this scaffold189 error. But actually all are causing the error. It just depends on which one phyluce processes first! And what is even more surprising is that that 189 is a scaffold (basically a big contig) number within a big, single scaffold which, to my noob understanding, practically means phyluce worked fine with all till it reached 189 (or 7 in another or 20 in even another, like that)! In order to reproduce you will need to know what bait set I am using - I am using the acanthomorph 1kV1.

**Comment by brantfaircloth** [comment]
The issue is the names of your scaffolds.  These look something like `>scaffold1|size51725` but they need to look like `>scaffold1` (removing the pipe and everything to the right of it).  Once I fixed that, everything ran as expected.

**Comment by sunandan-dasgupta** [comment]
Thank you so much Prof. Faircloth for your kind help with troubleshooting this problem. I prepped a python script to get rid of the pipe and the size information as you advised and then everything went fine. Definitely going to acknowledge you in my paper!

**Comment by brantfaircloth** [comment]
You are welcome!  And, not necessary to add me to the Ack. section (but certainly appreciated if you do)!

**Comment by sunandan-dasgupta** [comment]
Thanks!

**Comment by brantfaircloth** [comment]
Just noting - not a bug - source genome file issues.
