### ISSUE TITLE
phyluce_assembly_match_contigs_to_probes stopped working

### ISSUE THREAD

**Issue by marianamateos** [faircloth-lab/phyluce#295]
I had run successfully phyluce_assembly_match_contigs_to_probes on similar datasets a few days ago. I now get the error message below concerning 3 lines in the "phyluce_assembly_match_contigs_to_probes" (complete paths have been remove). The only thing I might have done between the time when it was working and when it stopped, was install sqlite3 (again).

/miniconda/envs/phyluce-1.7.2/bin/phyluce_assembly_match_contigs_to_probes \
    --contigs trinity-assemblies  \
    --probes hymenoptera-v2-PRINCIPAL-bait-set.fasta.txt \
    --output uce-search-results
2023-03-04 19:56:31,021 - phyluce_assembly_match_contigs_to_probes - INFO - ======= Starting phyluce_assembly_match_contigs_to_probes =======
2023-03-04 19:56:31,021 - phyluce_assembly_match_contigs_to_probes - INFO - Version: 1.7.2
2023-03-04 19:56:31,021 - phyluce_assembly_match_contigs_to_probes - INFO - Commit: None
2023-03-04 19:56:31,021 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --contigs: /trinity-assemblies
2023-03-04 19:56:31,021 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --csv: None
2023-03-04 19:56:31,021 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --dupefile: None
2023-03-04 19:56:31,021 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --keep_duplicates: None
2023-03-04 19:56:31,021 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --log_path: None
2023-03-04 19:56:31,022 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --min_coverage: 80
2023-03-04 19:56:31,022 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --min_identity: 80
2023-03-04 19:56:31,022 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --output: /uce-search-results
2023-03-04 19:56:31,022 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --probes: /hymenoptera-v2-PRINCIPAL-bait-set.fasta.txt
2023-03-04 19:56:31,022 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --regex: ^(uce-\d+)(?:_p\d+.*)
2023-03-04 19:56:31,022 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --verbosity: INFO
2023-03-04 19:56:31,258 - phyluce_assembly_match_contigs_to_probes - INFO - Creating the UCE-match database
Traceback (most recent call last):
  File "/miniconda/envs/phyluce-1.7.2/bin/phyluce_assembly_match_contigs_to_probes", line 421, in <module>
    main()
  File "miniconda/envs/phyluce-1.7.2/bin/phyluce_assembly_match_contigs_to_probes", line 305, in main
    log, os.path.join(args.output, "probe.matches.sqlite"), organisms, uces
  File "miniconda/envs/phyluce-1.7.2/bin/phyluce_assembly_match_contigs_to_probes", line 129, in create_probe_database
    c.execute(query)
sqlite3.OperationalError: near ")": syntax error

**Comment by spilornis-ng** [comment]
Hi were you able to resolve this??
I am still trying to figure this out!
