### ISSUE TITLE
error with "phyluce_align_get_only_loci_with_min_taxa"

### ISSUE THREAD

**Issue by Gefsy** [faircloth-lab/phyluce#310]
Hi all,
when i run"phyluce_align_get_align_summary_data ", I got summary as
2023-08-24 23:30:53,548 - phyluce_align_get_align_summary_data - INFO - [Matrix 50%]		1466 alignments
2023-08-24 23:30:53,548 - phyluce_align_get_align_summary_data - INFO - [Matrix 55%]		1036 alignments
2023-08-24 23:30:53,549 - phyluce_align_get_align_summary_data - INFO - [Matrix 60%]		782 alignments
2023-08-24 23:30:53,549 - phyluce_align_get_align_summary_data - INFO - [Matrix 65%]		570 alignments
2023-08-24 23:30:53,549 - phyluce_align_get_align_summary_data - INFO - [Matrix 70%]		309 alignments
2023-08-24 23:30:53,549 - phyluce_align_get_align_summary_data - INFO - [Matrix 75%]		188 alignments
2023-08-24 23:30:53,549 - phyluce_align_get_align_summary_data - INFO - [Matrix 80%]		115 alignments
2023-08-24 23:30:53,549 - phyluce_align_get_align_summary_data - INFO - [Matrix 85%]		45 alignments
2023-08-24 23:30:53,549 - phyluce_align_get_align_summary_data - INFO - [Matrix 90%]		23 alignments
2023-08-24 23:30:53,549 - phyluce_align_get_align_summary_data - INFO - [Matrix 95%]		8 alignments

But when I went to get the 50p alignment, I just got "423 alignments" and some error as
2023-08-24 23:28:46,256 - phyluce_align_get_only_loci_with_min_taxa - INFO - ======= Starting phyluce_align_get_only_loci_with_min_taxa ======
2023-08-24 23:28:46,256 - phyluce_align_get_only_loci_with_min_taxa - INFO - Version: 1.7.1
2023-08-24 23:28:46,256 - phyluce_align_get_only_loci_with_min_taxa - INFO - Commit: None
2023-08-24 23:28:46,256 - phyluce_align_get_only_loci_with_min_taxa - INFO - Argument --alignments: /home/dell/data/Gerridae/UCE/taxon-sets/all/mafft-nexus-internal-trimmed-gblocks-clean
2023-08-24 23:28:46,256 - phyluce_align_get_only_loci_with_min_taxa - INFO - Argument --cores: 12
2023-08-24 23:28:46,256 - phyluce_align_get_only_loci_with_min_taxa - INFO - Argument --input_format: nexus
2023-08-24 23:28:46,256 - phyluce_align_get_only_loci_with_min_taxa - INFO - Argument --log_path: /home/dell/data/Gerridae/UCE/taxon-sets/all/log
2023-08-24 23:28:46,256 - phyluce_align_get_only_loci_with_min_taxa - INFO - Argument --output: /home/dell/data/Gerridae/UCE/taxon-sets/all/mafft-nexus-internal-trimmed-gblocks-clean-50p
2023-08-24 23:28:46,256 - phyluce_align_get_only_loci_with_min_taxa - INFO - Argument --percent: 0.5
2023-08-24 23:28:46,256 - phyluce_align_get_only_loci_with_min_taxa - INFO - Argument --taxa: 91
2023-08-24 23:28:46,256 - phyluce_align_get_only_loci_with_min_taxa - INFO - Argument --verbosity: INFO
2023-08-24 23:28:46,257 - phyluce_align_get_only_loci_with_min_taxa - INFO - Getting alignment files
--- Logging error ---
Traceback (most recent call last):
  File "/home/dell/miniconda3/envs/phyluce-1.7.1/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2265' in position 132: ordinal not in range(128)
Call stack:
  File "/home/dell/miniconda3/envs/phyluce-1.7.1/bin/phyluce_align_get_only_loci_with_min_taxa", line 128, in <module>
    main()
  File "/home/dell/miniconda3/envs/phyluce-1.7.1/bin/phyluce_align_get_only_loci_with_min_taxa", line 119, in main
    sum(results), len(results), args.percent, min_count
Message: 'Copied 423 alignments of 2681 total containing \u2265 0.5 proportion of taxa (n = 45)'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/home/dell/miniconda3/envs/phyluce-1.7.1/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2265' in position 124: ordinal not in range(128)
Call stack:
  File "/home/dell/miniconda3/envs/phyluce-1.7.1/bin/Hi all,
when i run"phyluce_align_get_align_summary_data ", I got summary as
2023-08-24 23:30:53,548 - phyluce_align_get_align_summary_data - INFO - [Matrix 50%]		1466 alignments
2023-08-24 23:30:53,548 - phyluce_align_get_align_summary_data - INFO - [Matrix 55%]		1036 alignments
2023-08-24 23:30:53,549 - phyluce_align_get_align_summary_data - INFO - [Matrix 60%]		782 alignments
2023-08-24 23:30:53,549 - phyluce_align_get_align_summary_data - INFO - [Matrix 65%]		570 alignments
2023-08-24 23:30:53,549 - phyluce_align_get_align_summary_data - INFO - [Matrix 70%]		309 alignments
2023-08-24 23:30:53,549 - phyluce_align_get_align_summary_data - INFO - [Matrix 75%]		188 alignments
2023-08-24 23:30:53,549 - phyluce_align_get_align_summary_data - INFO - [Matrix 80%]		115 alignments
2023-08-24 23:30:53,549 - phyluce_align_get_align_summary_data - INFO - [Matrix 85%]		45 alignments
2023-08-24 23:30:53,549 - phyluce_align_get_align_summary_data - INFO - [Matrix 90%]		23 alignments
2023-08-24 23:30:53,549 - phyluce_align_get_align_summary_data - INFO - [Matrix 95%]		8 alignments

But when I went to get the 50p alignment, I just got "423 alignments" and some error as
2023-08-24 23:28:46,256 - phyluce_align_get_only_loci_with_min_taxa - INFO - ======= Starting phyluce_align_get_only_loci_with_min_taxa ======
2023-08-24 23:28:46,256 - phyluce_align_get_only_loci_with_min_taxa - INFO - Version: 1.7.1
2023-08-24 23:28:46,256 - phyluce_align_get_only_loci_with_min_taxa - INFO - Commit: None
2023-08-24 23:28:46,256 - phyluce_align_get_only_loci_with_min_taxa - INFO - Argument --alignments: /home/dell/data/Gerridae/UCE/taxon-sets/all/mafft-nexus-internal-trimmed-gblocks-clean
2023-08-24 23:28:46,256 - phyluce_align_get_only_loci_with_min_taxa - INFO - Argument --cores: 12
2023-08-24 23:28:46,256 - phyluce_align_get_only_loci_with_min_taxa - INFO - Argument --input_format: nexus
2023-08-24 23:28:46,256 - phyluce_align_get_only_loci_with_min_taxa - INFO - Argument --log_path: /home/dell/data/Gerridae/UCE/taxon-sets/all/log
2023-08-24 23:28:46,256 - phyluce_align_get_only_loci_with_min_taxa - INFO - Argument --output: /home/dell/data/Gerridae/UCE/taxon-sets/all/mafft-nexus-internal-trimmed-gblocks-clean-50p
2023-08-24 23:28:46,256 - phyluce_align_get_only_loci_with_min_taxa - INFO - Argument --percent: 0.5
2023-08-24 23:28:46,256 - phyluce_align_get_only_loci_with_min_taxa - INFO - Argument --taxa: 91
2023-08-24 23:28:46,256 - phyluce_align_get_only_loci_with_min_taxa - INFO - Argument --verbosity: INFO
2023-08-24 23:28:46,257 - phyluce_align_get_only_loci_with_min_taxa - INFO - Getting alignment files
--- Logging error ---
Traceback (most recent call last):
  File "/home/dell/miniconda3/envs/phyluce-1.7.1/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2265' in position 132: ordinal not in range(128)
Call stack:
  File "/home/dell/miniconda3/envs/phyluce-1.7.1/bin/phyluce_align_get_only_loci_with_min_taxa", line 128, in <module>
    main()
  File "/home/dell/miniconda3/envs/phyluce-1.7.1/bin/phyluce_align_get_only_loci_with_min_taxa", line 119, in main
    sum(results), len(results), args.percent, min_count
Message: 'Copied 423 alignments of 2681 total containing \u2265 0.5 proportion of taxa (n = 45)'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/home/dell/miniconda3/envs/phyluce-1.7.1/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2265' in position 124: ordinal not in range(128)
Call stack:
  File "/home/dell/miniconda3/envs/phyluce-1.7.1/bin/phyluce_align_get_only_loci_with_min_taxa", line 128, in <module>
    main()
  File "/home/dell/miniconda3/envs/phyluce-1.7.1/bin/phyluce_align_get_only_loci_with_min_taxa", line 119, in main
    sum(results), len(results), args.percent, min_count
Message: 'Copied 423 alignments of 2681 total containing \u2265 0.5 proportion of taxa (n = 45)'
Arguments: ()
2023-08-24 23:28:46,679 - phyluce_align_get_only_loci_with_min_taxa - INFO - ====== Completed phyluce_align_get_only_loci_with_min_taxa ======

I want to know why the numbers of alignments can't mach the summary, and how i fix the error.
I'd greatly appreciate any help anyone can offer!
    main()
  File "/home/dell/miniconda3/envs/phyluce-1.7.1/bin/phyluce_align_get_only_loci_with_min_taxa", line 119, in main
    sum(results), len(results), args.percent, min_count
Message: 'Copied 423 alignments of 2681 total containing \u2265 0.5 proportion of taxa (n = 45)'
Arguments: ()
2023-08-24 23:28:46,679 - phyluce_align_get_only_loci_with_min_taxa - INFO - ====== Completed phyluce_align_get_only_loci_with_min_taxa ======

I want to know why the numbers of alignments can't mach the summary, and how i fix the error.
I'd greatly appreciate any help anyone can offer!

**Comment by brantfaircloth** [comment]
There is probably some mismatch in the number of taxa you are inputting (91) versus the number of taxa that are really in the alignments.  It is hard to say without additional information (e.g. the total output from the summary command).
