### ISSUE TITLE
sqlite error in "Determining locus presence in multiple genomes" step of Tutorial IV

### ISSUE THREAD

**Issue by kautumn** [faircloth-lab/phyluce#329]
I'm using my own genomes and following Tutorial IV on a Linux server. I have MAPPING.bam.sort.merge.strip.bed files for each genome and have made bed-files.conf.

When I run the 

`> phyluce_probe_get_multi_merge_table \
    --conf bed-files.conf \
    --base-taxon triCas1 \
    --output coleoptera-to-triCas1.sqlite`

code (replacing the base taxon and output with identifiers relevant to my data), I get this error:

`2024-02-22 15:42:27,856 - phyluce_probe_get_multi_merge_table - INFO - Creating database
Traceback (most recent call last):
  File "/home/kautumn/mambaforge/envs/phyluce-1.7.3/bin/phyluce_probe_get_multi_merge_table", line 147, in <module>
    main()
  File "/home/kautumn/mambaforge/envs/phyluce-1.7.3/bin/phyluce_probe_get_multi_merge_table", line 129, in main
    conn, c = create_match_database(args.output, organisms, args.base_taxon)
  File "/home/kautumn/mambaforge/envs/phyluce-1.7.3/bin/phyluce_probe_get_multi_merge_table", line 85, in create_match_database
    c.execute(query)
sqlite3.OperationalError: near "-": syntax error`

I can call sqlite3 successfully from the command line. 

Here's what the first few lines of one of my MAPPING.bam.sort.merge.strip.bed files looks like:

`NODE_10017_length_1217_cov_2.867890     0       1217
NODE_1002_length_13248_cov_2.814572     6       342
NODE_1002_length_13248_cov_2.814572     485     13234
NODE_10040_length_1215_cov_2.829963     0       1215
NODE_10041_length_1215_cov_2.795956     0       1215`

Thank you, I really appreciate any help I can get!

**Comment by Artifice120** [comment]
You were right it was the dash in the sample name
