### ISSUE TITLE
ConfigParser.NoSectionError: No section: 'names'

### ISSUE THREAD

**Issue by Jami5on** [faircloth-lab/phyluce#332]
Hello Dr. Faircloth,

I am getting the following errors when attempting to clean my raw-data reads (see below). I have double checked the formatting of my file and wonder if the dash in the raw read files that I want to rename are what is mucking things up, or maybe another issue my tired eyes cannot see. I have attached my config file and pasted my SH below the error message. Additionally, I should mention I get the same error when working through the tutorial. I am using phyluce v 1.7.3 and accessing the university hpcc via Windows Powershell. My config and shell script are in my "scratch" with a folder for the raw reads. 

[illumiprocessor3.txt](https://github.com/faircloth-lab/phyluce/files/14626509/illumiprocessor3.txt)
 

Thank you in advance,
Jamison

**parallel file with error code:**

2024-03-16 23:01:33,467 - illumiprocessor - INFO - ==================== Starting illumiprocessor ===================
2024-03-16 23:01:33,469 - illumiprocessor - INFO - Version: 2.10
2024-03-16 23:01:33,469 - illumiprocessor - INFO - Argument --config: illumiprocessor3.conf
2024-03-16 23:01:33,469 - illumiprocessor - INFO - Argument --cores: 4
2024-03-16 23:01:33,469 - illumiprocessor - INFO - Argument --input: /scratch/jr4253/raw_fastq/raw_fastq
2024-03-16 23:01:33,470 - illumiprocessor - INFO - Argument --log_path: None
2024-03-16 23:01:33,470 - illumiprocessor - INFO - Argument --min_len: 40
2024-03-16 23:01:33,470 - illumiprocessor - INFO - Argument --no_merge: False
2024-03-16 23:01:33,470 - illumiprocessor - INFO - Argument --output: /scratch/jr4253/raw_fastq/clean_fastq
2024-03-16 23:01:33,470 - illumiprocessor - INFO - Argument --phred: phred33
2024-03-16 23:01:33,470 - illumiprocessor - INFO - Argument --r1_pattern: None
2024-03-16 23:01:33,471 - illumiprocessor - INFO - Argument --r2_pattern: None
2024-03-16 23:01:33,471 - illumiprocessor - INFO - Argument --se: False
2024-03-16 23:01:33,471 - illumiprocessor - INFO - Argument --trimmomatic: /home/jr4253/.conda/envs/phyluce-1.7.3/bin/trimmomatic
2024-03-16 23:01:33,471 - illumiprocessor - INFO - Argument --verbosity: INFO
Traceback (most recent call last):
  File "/home/jr4253/.conda/envs/phyluce-1.7.3/lib/python3.6/configparser.py", line 846, in items
    d.update(self._sections[section])
KeyError: 'names'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jr4253/.conda/envs/phyluce-1.7.3/bin/illumiprocessor", line 17, in <module>
    sys.exit(main())
  File "/home/jr4253/.conda/envs/phyluce-1.7.3/lib/python3.6/site-packages/illumiprocessor/cli/main.py", line 114, in main
    main(args)
  File "/home/jr4253/.conda/envs/phyluce-1.7.3/lib/python3.6/site-packages/illumiprocessor/main.py", line 33, in main
    for start_name, end_name in conf.items("names"):
  File "/home/jr4253/.conda/envs/phyluce-1.7.3/lib/python3.6/configparser.py", line 849, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'names'

**SH**
#!/bin/bash
#SBATCH --job-name=UCE_clean      # Job name
#SBATCH --mail-type=BEGIN,END,FAIL         # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=jr4253@nau.edu     # Where to send mail
#SBATCH --nodes=1-1                   # Run a single task
#SBATCH --ntasks-per-node=16            # Number of CPU cores per task
#SBATCH --mem=80gb            # Job memory request
#SBATCH --time=06-00:00:00              # Time limit days-hrs:min:sec
#SBATCH --output=parallel_%j.log     # Standard output and error log
#SBATCH --chdir=/scratch/jr4253

module load anaconda3

conda activate phyluce-1.7.3

cd /scratch/jr4253/raw_fastq

illumiprocessor \
    --input raw_fastq/ \
    --output clean_fastq \
    --config illumiprocessor3.conf \
    --cores 4

**Comment by brantfaircloth** [comment]
It looks like your script might be putting you into the wrong directory - the `cd` command is placing you in `/scratch/jr4253/raw_fastq` - do you have  `raw_fastq` folder nested inside of that (so like `/scratch/jr4253/raw_fastq/raw_fastq`?

**Comment by Jami5on** [comment]
Good morning Dr. Faircloth,

Currently, I have my SH and config in my scratch  (/scratch/jr4253) and my raw reads are in the raw reads folder inside of that directory (/scratch/jr4253/raw_fatsq) but I do not have another folder within raw_fastq. So perhaps that is the error (fingers crossed!) and changing my cd to /scratch/jr4253 will help? I'll try this shortly and get back to you. 

Thank you for your quick reply and help,
Jami5on

**Comment by Jami5on** [comment]
Hello Dr.,

I have since updated my SH file and noticed I had some raw reads not accounted for in my config file. Omitting those (they're not needed now) and updating my SH worked!

Thank you so much for your help!
Jami5on
