### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by bistbs** [faircloth-lab/phyluce#350]
Note: It matched the contigs for all the samples except "Callosciurus_prevostii_FMNH235489"
I am running given command and I would get the error as given below. 

# match contigs to probes
phyluce_assembly_match_contigs_to_probes \
    --contigs /shared/jezkovt_bistbs_shared/Data/uce-tutorial/Contigs \
    --probes uce-5k-probes.fasta \
    --output /shared/jezkovt_bistbs_shared/Data/uce-tutorial/uce-search-results 

2024-09-24 19:14:45,424 - phyluce_assembly_match_contigs_to_probes - INFO - Callosciurus_finlaysonii_trotteri_USNM221585: 28 (0.30%) uniques of 9325 contigs, 0 dupe probe matches, 2 UCE loci removed for matching multiple contigs, 1 contigs removed for matching multiple UCE loci
2024-09-24 19:15:03,019 - phyluce_assembly_match_contigs_to_probes - INFO - Callosciurus_finlaysonii_williamsoni_USNM240512: 4075 (7.78%) uniques of 52388 contigs, 0 dupe probe matches, 212 UCE loci removed for matching multiple contigs, 25 contigs removed for matching multiple UCE loci
2024-09-24 19:15:26,194 - phyluce_assembly_match_contigs_to_probes - INFO - Callosciurus_prevostii_FMNH235489: 4040 (6.22%) uniques of 64983 contigs, 0 dupe probe matches, 167 UCE loci removed for matching multiple contigs, 58 contigs removed for matching multiple UCE loci
Traceback (most recent call last):
  File "/home/bistbs/miniconda2/envs/phyluce-1.7.3/bin/phyluce_assembly_match_contigs_to_probes", line 421, in <module>
    main()
  File "/home/bistbs/miniconda2/envs/phyluce-1.7.3/bin/phyluce_assembly_match_contigs_to_probes", line 354, in main
    contig_name = get_contig_name(lz.name1)
  File "/home/bistbs/miniconda2/envs/phyluce-1.7.3/bin/phyluce_assembly_match_contigs_to_probes", line 279, in get_contig_name
    return match.groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
(phyluce-1.7.3) [bistbs@mualhpcp26  PRD  /shared/jezkovt_bistbs_shared/Data/uce-tutorial/Contigs]$

**Comment by brantfaircloth** [comment]
Where did this file of contigs come from?  Seems like they have different names than expected.

**Comment by bistbs** [comment]
This file is an outgroup and took it from another study for my purpose.

**Comment by brantfaircloth** [comment]
That's very likely the cause of the error you are seeing.  Phyluce expects a certain contig naming pattern, so contigs you include need to follow that pattern. Alternatively, you can edit the config file to match the pattern.

**Comment by derowang** [comment]
> That's very likely the cause of the error you are seeing. Phyluce expects a certain contig naming pattern, so contigs you include need to follow that pattern. Alternatively, you can edit the config file to match the pattern.

@brantfaircloth Would you mind if I ask about the required pattern for the name of the contigs? I have separated my large files and run independently as suggested in this post: https://github.com/faircloth-lab/phyluce/issues/272, and then I combined the exploded-fasta files of separate runs into one fasta file per sample, and then start from the UCE identification process again (from phyluce_assembly_match_contigs_to_probes). This 'NoneType' object has no attribute 'groups' popped up. I think I can operate the name of the contigs in the combined fasta file to let it work?

Thank you
