### ISSUE TITLE
"Cannot find the a fasta file" error

### ISSUE THREAD

**Issue by franztastic** [faircloth-lab/phyluce#357]
Hi everyone, 
I've been using phyluce for a while now and this morning I've had this error I don't know how to solve.

I've many assemblies and I need to get the uce's fasta from all of them. It worked fine for all previous assemblies but not for this MG1026_asm, as far as I know there's nothing different I've done. I've checked if in any of the configs files I've written MG1026-asm instead of MG1026_asm but I cannot find it, I've even modified the file to MG1026-asm.

```
Traceback (most recent call last):
  File "/home/laura_bioinfo/.conda/envs/phyluce-1.7.3/bin/phyluce_assembly_get_fastas_from_match_counts", line 306, in <module>
    main()
  File "/home/laura_bioinfo/.conda/envs/phyluce-1.7.3/bin/phyluce_assembly_get_fastas_from_match_counts", line 229, in main
    reads = find_file(args.contigs, name)
  File "/home/laura_bioinfo/.conda/envs/phyluce-1.7.3/bin/phyluce_assembly_get_fastas_from_match_counts", line 160, in find_file
    name, ", ".join(extensions)
ValueError: Cannot find the a fasta file for MG1026-asm with any of the extensions (.fa, .fasta, .contigs.fasta, .contigs.fa, .gz, .fasta.gz, .fa.gz) 
  
[4]   Exit 1                  phyluce_assembly_get_fastas_from_match_counts --contigs ../assemblies/ --locus-db uce_december.sqlite --match-count-output datasets1.conf --incomplete-matrix dataset1.incomplete --output dataset1.fasta
```
It seems like the script cannot find the FASTA file for MG1026-asm with any of the following extensions: .fa, .fasta, .contigs.fasta, .contigs.fa, .gz, .fasta.gz, or .fa.gz.

Here are the steps I’ve already taken:

-     Double-checked that the file for MG1026_asm exists in the correct directory.
-     Verified that there are no discrepancies in the file naming or configuration files.
-     Tried modifying the config file to use MG1026-asm, but the issue remains.

I would greatly appreciate any advice on how to resolve this issue. Thank you!

**Comment by brantfaircloth** [comment]
Howdy,

It's a little hard for me to say without the config file, filenames, etc. but my guess is that the issue has to do with the dash in the filename.  As far as I can remember, SQLite does not like dashes in *column* names, so phyluce will replace a dash `-` with an underscore `_` when building the database it uses.

Anyway, without additional information, the best way to fix the problem is to look in the actual sqlite database you created and determine how phyluce named this individual (see [here](https://phyluce.readthedocs.io/en/latest/daily-use/daily-use-3-uce-processing.html#database) for more info on the structure of this database). 

Once you determine how phyluce expects the file to be named, you'll need to change the name of the actual assembly file **AND** you'll need to put the same taxon name in the config file.  So, let's say that phyluce converted `MG1026-asm` to `MG1026_asm`.  Then, you'll need your file to be named `MG1026_asm.fasta` and the config file entry to read `MG1026_asm`.

Hopefully that helps explain a bit.
