### ISSUE TITLE
UCE names do not match error in uce-tutorial when using abyss assembler

### ISSUE THREAD

**Issue by mlosada323** [faircloth-lab/phyluce#359]
Hi there,

I'm running the uce-tutorial but using abyss instead of spades and noticed the following error when running  phyluce_assembly_get_fastas_from_match_counts: UCE names do not match. I've used the same config files in the tutorial for both spades and velvet assemblers and both worked well. Please advise

Best

Marcos

(phyluce-1.7.3) [mlosada@gpu013 all]$ phyluce_assembly_get_fastas_from_match_counts \
>     --contigs ../../abyss-assemblies/contigs \
>     --locus-db ../../uce-search-results-a/probe.matches.sqlite \
>     --match-count-output all-taxa-incomplete.conf \
>     --output all-taxa-incomplete.fasta \
>     --incomplete-matrix all-taxa-incomplete.incomplete \
>     --log-path log
2024-12-15 09:36:49,754 - phyluce_assembly_get_fastas_from_match_counts - INFO - ===== Starting phyluce_assembly_get_fastas_from_match_counts ====
2024-12-15 09:36:49,798 - phyluce_assembly_get_fastas_from_match_counts - INFO - Version: 1.7.3
2024-12-15 09:36:49,913 - phyluce_assembly_get_fastas_from_match_counts - INFO - Commit: None
2024-12-15 09:36:50,037 - phyluce_assembly_get_fastas_from_match_counts - INFO - Argument --contigs: /GWSPH/home/mlosada/uce-tutorial/abyss-assemblies/contigs
2024-12-15 09:36:50,130 - phyluce_assembly_get_fastas_from_match_counts - INFO - Argument --extend_locus_contigs: None
2024-12-15 09:36:50,200 - phyluce_assembly_get_fastas_from_match_counts - INFO - Argument --extend_locus_db: None
2024-12-15 09:36:50,399 - phyluce_assembly_get_fastas_from_match_counts - INFO - Argument --incomplete_matrix: /GWSPH/home/mlosada/uce-tutorial/taxon-sets-a/all/all-taxa-incomplete.incomplete
2024-12-15 09:36:50,547 - phyluce_assembly_get_fastas_from_match_counts - INFO - Argument --locus_db: /GWSPH/home/mlosada/uce-tutorial/uce-search-results-a/probe.matches.sqlite
2024-12-15 09:36:50,676 - phyluce_assembly_get_fastas_from_match_counts - INFO - Argument --log_path: /GWSPH/home/mlosada/uce-tutorial/taxon-sets-a/all/log
2024-12-15 09:36:50,903 - phyluce_assembly_get_fastas_from_match_counts - INFO - Argument --match_count_output: /GWSPH/home/mlosada/uce-tutorial/taxon-sets-a/all/all-taxa-incomplete.conf
2024-12-15 09:36:51,058 - phyluce_assembly_get_fastas_from_match_counts - INFO - Argument --output: /GWSPH/home/mlosada/uce-tutorial/taxon-sets-a/all/all-taxa-incomplete.fasta
2024-12-15 09:36:51,092 - phyluce_assembly_get_fastas_from_match_counts - INFO - Argument --verbosity: INFO
2024-12-15 09:36:51,428 - phyluce_assembly_get_fastas_from_match_counts - INFO - There are 4 taxa in the match-count-config file named all-taxa-incomplete.conf
2024-12-15 09:36:51,615 - phyluce_assembly_get_fastas_from_match_counts - INFO - There are 3546 UCE loci in an INCOMPLETE matrix
2024-12-15 09:36:52,041 - phyluce_assembly_get_fastas_from_match_counts - INFO - ---------Getting UCE loci for alligator_mississippiensis---------
2024-12-15 09:36:52,456 - phyluce_assembly_get_fastas_from_match_counts - INFO - There are 650 UCE loci for alligator_mississippiensis
2024-12-15 09:36:52,561 - phyluce_assembly_get_fastas_from_match_counts - INFO - Parsing and renaming contigs for alligator_mississippiensis
2024-12-15 09:36:52,817 - phyluce_assembly_get_fastas_from_match_counts - INFO - Writing missing locus information to /GWSPH/home/mlosada/uce-tutorial/taxon-sets-a/all/all-taxa-incomplete.incomplete
Traceback (most recent call last):
  File "/GWSPH/home/mlosada/.conda/envs/phyluce-1.7.3/bin/phyluce_assembly_get_fastas_from_match_counts", line 306, in <module>
    main()
  File "/GWSPH/home/mlosada/.conda/envs/phyluce-1.7.3/bin/phyluce_assembly_get_fastas_from_match_counts", line 300, in main
    assert set(written) == set(uces), "UCE names do not match"
AssertionError: UCE names do not match

**Comment by brantfaircloth** [comment]
This sounds like there is a mismatch between the set of UCEs that you want (what is in the config file) and the set of UCEs that you have (what is in the database/contigs directory).  This could happen if you are using a config file generated for one set of assemblies (e.g. from spades) but running that against another set of assemblies (e.g. from abyss).

**Comment by mlosada323** [comment]
It may be, I'm using the data and config files you included in the tutorial. The config files assembly.conf and taxon-set.conf worked ok for spades and velvet but not for abyss. Thanks
