### ISSUE TITLE
"_trinity" problem for _get_trinity_coverage_for_uce_loci

### ISSUE THREAD

**Issue by michael-branstetter** [faircloth-lab/phyluce#41]
Version 1.5 of phyluce_assembly_assemblo_trinity creates species-specific folders that end with "_trinity". The program phyluce_assembly_get_trinity_coverage_for_uce_loci has not been updated to deal with this and will not run. I fixed the problem by adding ".replace('trinity','')" at the end of line 104.

**Comment by brantfaircloth** [comment]
On 7 Aug 2015, at 12:01, michael-branstetter wrote:

> Version 1.5 of phyluce_assembly_assemblo_trinity creates 
> species-specific folders that end with "_trinity". The program 
> phyluce_assembly_get_trinity_coverage_for_uce_loci has not been 
> updated to deal with this and will not run. I fixed the problem by 
> adding ".replace('trinity','')" at the end of line 104.

michael,

cool - thanks.  you may want to set the conf file you are using to use 
the older version of trinity rather than the newer version that comes 
with “conda install”.  the reasons are varied, but the older version 
is both faster and assembled more contigs than the newer version.  I am 
likely to revert the version you get with phyluce to the older trinity.

-b

**Comment by michael-branstetter** [comment]
Yes, I already switched back to old version of trinity. New version was
slow and found fewer contigs.

I am still having some trouble with get_coverage_for_uce_loci. For some
reason the program fails to work on 30% of may samples. I get an error
saying that it cannot find the reads-on-target file. You fixed this issue
once before, but I am not sure what you did. I am guessing it has something
to do with the fact that I am now running old trinity with new Phyluce.
Perhaps something with the file names?

Michael

~~~~~~~~~~~~~~~~~~~~~~~
Michael G. Branstetter
Postdoctoral Fellow

Department of Biology
University of Utah
257 South 1400 East
Salt Lake City, UT 84112
Office: (801) 581-6609


On Fri, Aug 7, 2015 at 2:07 PM, Brant Faircloth <notifications@github.com>
wrote:

> On 7 Aug 2015, at 12:01, michael-branstetter wrote:
>
> > Version 1.5 of phyluce_assembly_assemblo_trinity creates
> > species-specific folders that end with "_trinity". The program
> > phyluce_assembly_get_trinity_coverage_for_uce_loci has not been
> > updated to deal with this and will not run. I fixed the problem by
> > adding ".replace('trinity','')" at the end of line 104.
>
> michael,
>
> cool - thanks. you may want to set the conf file you are using to use
> the older version of trinity rather than the newer version that comes
> with “conda install”. the reasons are varied, but the older version
> is both faster and assembled more contigs than the newer version. I am
> likely to revert the version you get with phyluce to the older trinity.
>
> -b
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/faircloth-lab/phyluce/issues/41#issuecomment-128821534>
> .
>

**Comment by TiagoSousaNeves** [comment]
Hi

I think that I have the same problem running phyluce_assembly_assemblo_trinity!!

IOError("Neither Trinity.fasta nor trinity.log were found in output.") 

How can I fix it?
How can I downgrade the  phyluce_assembly_assemblo_trinity?

Thanks

TSN

**Comment by JETitus** [comment]
I get the same thing. Cannot figure out what the solution may be... Below is the command and the error from the output.

:uce-Tutorial USER$ phyluce_assembly_assemblo_trinity \
> --conf assembly.conf \
> --output trinity_assemblies \
> --clean \
> --cores 8
2015-12-15 14:38:53,236 - phyluce_assembly_assemblo_trinity - INFO - =========== Starting phyluce_assembly_assemblo_trinity ==========
2015-12-15 14:38:53,236 - phyluce_assembly_assemblo_trinity - INFO - Version: 1.5.0
2015-12-15 14:38:53,236 - phyluce_assembly_assemblo_trinity - INFO - Argument --clean: True
2015-12-15 14:38:53,236 - phyluce_assembly_assemblo_trinity - INFO - Argument --config: /Users/jamestmcquillan/Desktop/uce-Tutorial/assembly.conf
2015-12-15 14:38:53,236 - phyluce_assembly_assemblo_trinity - INFO - Argument --cores: 8
2015-12-15 14:38:53,236 - phyluce_assembly_assemblo_trinity - INFO - Argument --dir: None
2015-12-15 14:38:53,236 - phyluce_assembly_assemblo_trinity - INFO - Argument --log_path: None
2015-12-15 14:38:53,236 - phyluce_assembly_assemblo_trinity - INFO - Argument --min_kmer_coverage: 2
2015-12-15 14:38:53,236 - phyluce_assembly_assemblo_trinity - INFO - Argument --output: /Users/jamestmcquillan/Desktop/uce-Tutorial/trinity_assemblies
2015-12-15 14:38:53,236 - phyluce_assembly_assemblo_trinity - INFO - Argument --subfolder: 
2015-12-15 14:38:53,237 - phyluce_assembly_assemblo_trinity - INFO - Argument --verbosity: INFO
2015-12-15 14:38:53,237 - phyluce_assembly_assemblo_trinity - INFO - Getting input filenames and creating output directories
2015-12-15 14:38:53,238 - phyluce_assembly_assemblo_trinity - INFO - ------------- Processing alligator_mississippiensis -------------
2015-12-15 14:38:53,239 - phyluce_assembly_assemblo_trinity - INFO - Finding fastq/fasta files
2015-12-15 14:38:53,240 - phyluce_assembly_assemblo_trinity - INFO - File type is fastq
2015-12-15 14:38:53,241 - phyluce_assembly_assemblo_trinity - INFO - Copying raw read data to /Users/jamestmcquillan/Desktop/uce-Tutorial/trinity_assemblies/alligator_mississippiensis_trinity
2015-12-15 14:38:53,717 - phyluce_assembly_assemblo_trinity - INFO - Combining singleton reads with R1 data
2015-12-15 14:38:53,750 - phyluce_assembly_assemblo_trinity - INFO - Running Trinity.pl for PE data
2015-12-15 14:38:57,446 - phyluce_assembly_assemblo_trinity - INFO - Removing extraneous Trinity files
Traceback (most recent call last):
  File "/Users/jamestmcquillan/anaconda/bin/phyluce_assembly_assemblo_trinity", line 347, in <module>
    main()
  File "/Users/jamestmcquillan/anaconda/bin/phyluce_assembly_assemblo_trinity", line 326, in main
    cleanup_trinity_assembly_folder(output, log)
  File "/Users/jamestmcquillan/anaconda/bin/phyluce_assembly_assemblo_trinity", line 276, in cleanup_trinity_assembly_folder
    raise IOError("Neither Trinity.fasta nor trinity.log were found in output.")
IOError: Neither Trinity.fasta nor trinity.log were found in output.

**Comment by brantfaircloth** [comment]
These appear to be two separate issues - one is with the coverage computations over the trinity assemblies (@michael-branstetter issue) and the other is with the assembly script (@TiagoSousaNeves and @JETitus issues).  I'll take a look and see if I can figure out what is going on with the cleanup code.  Could either of @TiagoSousaNeves and @JETitus send me the output of ```ls -alh``` on your ```--output``` directories?

**Comment by brantfaircloth** [comment]
For further discussion of the Trinity assembly issue (the problem that @TiagoSousaNeves and @JETitus are having), see #45.

**Comment by mcfaddenlab** [comment]
hi, 

i am having the same problem as michael mentioned above with the reads-on-target file in phyluce_assembly_get_trinity_coverage_for_uce_loci. I got this error for 4 out of 100 of my samples (so 96 worked just fine). Any idea why?

2018-05-04 09:31:47,975 - phyluce_assembly_get_trinity_coverage_for_uce_loci - INFO - == Starting phyluce_assembly_get_trinity_coverage_for_uce_loci ==
2018-05-04 09:31:47,975 - phyluce_assembly_get_trinity_coverage_for_uce_loci - INFO - Version: 1.5.0
2018-05-04 09:31:47,976 - phyluce_assembly_get_trinity_coverage_for_uce_loci - INFO - Argument --assemblies: /data/mcfadden/aquattrini/DATA/UCESeqs/Peterun/spades-test
2018-05-04 09:31:47,976 - phyluce_assembly_get_trinity_coverage_for_uce_loci - INFO - Argument --exclude: None
2018-05-04 09:31:47,976 - phyluce_assembly_get_trinity_coverage_for_uce_loci - INFO - Argument --locus_db: /data/mcfadden/aquattrini/DATA/UCESeqs/Peterun/uce-search-results-spades8080/probe.matches.sqlite
2018-05-04 09:31:47,976 - phyluce_assembly_get_trinity_coverage_for_uce_loci - INFO - Argument --log_path: None
2018-05-04 09:31:47,976 - phyluce_assembly_get_trinity_coverage_for_uce_loci - INFO - Argument --match_count_output: /data/mcfadden/aquattrini/DATA/UCESeqs/Peterun/taxonsets/all-spades/uce-taxa-incomplete.conf
2018-05-04 09:31:47,976 - phyluce_assembly_get_trinity_coverage_for_uce_loci - INFO - Argument --output: /data/mcfadden/aquattrini/DATA/UCESeqs/Peterun/test
2018-05-04 09:31:47,977 - phyluce_assembly_get_trinity_coverage_for_uce_loci - INFO - Argument --resume: None
2018-05-04 09:31:47,977 - phyluce_assembly_get_trinity_coverage_for_uce_loci - INFO - Argument --type: untrimmed
2018-05-04 09:31:47,977 - phyluce_assembly_get_trinity_coverage_for_uce_loci - INFO - Argument --verbosity: INFO
2018-05-04 09:31:47,977 - phyluce_assembly_get_trinity_coverage_for_uce_loci - INFO - Creating the output directory
2018-05-04 09:31:47,977 - phyluce_assembly_get_trinity_coverage_for_uce_loci - INFO - Fetching input filenames
2018-05-04 09:31:47,978 - phyluce_assembly_get_trinity_coverage_for_uce_loci - INFO - Fetching loci from uce-taxa-incomplete.conf
2018-05-04 09:31:48,003 - phyluce_assembly_get_trinity_coverage_for_uce_loci - INFO - ----------------------- Processing Coral85 ----------------------
2018-05-04 09:31:48,003 - phyluce_assembly_get_trinity_coverage_for_uce_loci - INFO - Fetching contig names from from probe.matches.sqlite
2018-05-04 09:31:48,018 - phyluce_assembly_get_trinity_coverage_for_uce_loci - INFO - Generating (untrimmed) per-base coverage file for UCE loci.
2018-05-04 09:32:33,504 - phyluce_assembly_get_trinity_coverage_for_uce_loci - INFO - Generating per-contig coverage file and interval list for UCE loci.
2018-05-04 09:32:33,551 - phyluce_assembly_get_trinity_coverage_for_uce_loci - INFO - Calculating coverage metrics for Coral85
Traceback (most recent call last):
  File "/data/mcfadden/aquattrini/PROGRAMS/anaconda2/bin/phyluce_assembly_get_trinity_coverage_for_uce_loci", line 311, in <module>
    main()
  File "/data/mcfadden/aquattrini/PROGRAMS/anaconda2/bin/phyluce_assembly_get_trinity_coverage_for_uce_loci", line 298, in main
    on_target_dict = picard.get_percent_reads_on_target(log, hs_metrics_file, organism)
  File "/data/mcfadden/aquattrini/PROGRAMS/anaconda2/lib/python2.7/site-packages/phyluce/picard.py", line 193, in get_percent_reads_on_target
    with open(hs_metrics_file, "rU") as metrics:
IOError: [Errno 2] No such file or directory: '/data/mcfadden/aquattrini/DATA/UCESeqs/Peterun/test/Coral85.reads-on-target.txt'

**Comment by brantfaircloth** [comment]
You'll need to check the log files (looks like those from picard) for these individuals to get a sense of what might be going on.  If you are getting things to work for some/most samples and a couple are failing, there is something, specifically, about those samples that is causing problems.

**Comment by mcfaddenlab** [comment]
thanks i will try chasing it down. it may have something to do with this error-which all 4 of these samples seem to have in the pe.picard-RG-out.log files


gnoring SAM validation error: ERROR: Record 3410053, Read name 7001309F:364:CBTWCANXX:6:1113:14749:7556, Mate Alignment start should != 0 because reference name != *.
Ignoring SAM validation error: ERROR: Record 3410053, Read name 7001309F:364:CBTWCANXX:6:1113:14749:7556, Alignment start should != 0 because reference name != *.
Ignoring SAM validation error: ERROR: Record 3410054, Read name 7001309F:364:CBTWCANXX:6:1113:14749:7556, Mate Alignment start should != 0 because reference name != *.
Ignoring SAM validation error: ERROR: Record 3410054, Read name 7001309F:364:CBTWCANXX:6:1113:14749:7556, Alignment start should != 0 because reference name != *.
INFO    2018-05-04 13:24:39     AddOrReplaceReadGroups  Processed     4,000,000 records.  Elapsed time: 00:01:02s.  Time for last 1,000,000:   16s.  Last read position: NODE_207_length_1601_cov_48.0129:365
[Fri May 04 13:26:19 PDT 2018] net.sf.picard.sam.AddOrReplaceReadGroups done. Elapsed time: 2.72 minutes.
Runtime.totalMemory()=3445424128

**Comment by GabiCamacho** [comment]
@mcfaddenlab and @brantfaircloth, I'm having the same problem and the same error message that @mcfaddenlab described above. Were you able to find what was causing your problems?

**Comment by KNx5** [comment]
Same problem here, @GabiCamacho did you end up solving this for yourself?

**Comment by GabiCamacho** [comment]
I was able to run using the scripts from Mike Lloyd, here
https://github.com/MikeWLloyd/Sequencing-Coverage-Scripts


*Gabriela P Camacho, Ph.D.*
Postdoctoral Fellow
North Carolina State University / California Academy of Sciences
gpcamach@ncsu.edu

Blaimer lab
Department of Entomology & Plant Pathology
North Carolina State University
3115 Gardner Hall, Campus Box 7613
Raleigh, NC 27695
https://blaimerlab.weebly.com/




Em sex, 7 de set de 2018 às 22:27, KNx5 <notifications@github.com> escreveu:

**Comment by brantfaircloth** [comment]
This script is getting removed from phyluce. For computing coverage, see https://github.com/faircloth-lab/phyluce-workflows.
