### ISSUE TITLE
using filtered reads from other softwares

### ISSUE THREAD

**Issue by SusanaFreitas** [faircloth-lab/phyluce#46]
Dear all,
I have been trying to use PHYLUCE with reads filtered outside this platform. I have now the script with no bugs apart from:
Traceback (most recent call last):
  File "/usr/local/packages6/apps/binapps/conda/phyluce/bin/phyluce_assembly_assemblo_velvet", line 259, in <module>
    main()
  File "/usr/local/packages6/apps/binapps/conda/phyluce/bin/phyluce_assembly_assemblo_velvet", line 240, in main
    reads = get_input_files(dir, args.subfolder, log)
  File "/usr/local/packages6/apps/binapps/conda/phyluce/lib/python2.7/site-packages/phyluce/raw_reads.py", line 92, in get_input_files
    raise IOError("There are not appropriate files in {}".format(dir))
IOError: There are not appropriate files in /fastdata/bo1sdf/NOV15/CAPTURE/phyluce_WD/uce-clean/genus_sps/split-adapter-quality-trimmed/

The filtering was done with cutadapt and I ended up with two files from PE reads, one with reads1 and the other with reads2. I don't have file with singletons... Could this be the error?

Thanks in advance
Susana

**Comment by brantfaircloth** [comment]
that may be the issue.  the other issue may be he directory structure which is laid out in the documentation (check the tutorial).

-b

**Comment by SusanaFreitas** [comment]
Thanks!
I am almost sure it is not the dir structure (I had some errors due to that, that I managed to solve). I am repeating the filtering within phyluce. I will let you know if that works.

cheers
Susana
