### ISSUE TITLE
Trimmomatic does not appear to be installed

### ISSUE THREAD

**Issue by mtntsuchiya** [faircloth-lab/phyluce#49]
Hi,
I'm starting to use phyluce and I'm having issues to run illumiprocessor. I followed the installation instructions from here https://media.readthedocs.org/pdf/phyluce/latest/phyluce.pdf and everything seems to be ok. The error I get is the following:

Traceback (most recent call last):
  File "/Users/mirian/anaconda2/bin/illumiprocessor", line 17, in <module>
    sys.exit(main())
  File "/Users/mirian/anaconda2/lib/python2.7/site-packages/illumiprocessor/cli/main.py", line 131, in main
    main(args)
  File "/Users/mirian/anaconda2/lib/python2.7/site-packages/illumiprocessor/main.py", line 22, in main
    core.check_dependencies(args)
  File "/Users/mirian/anaconda2/lib/python2.7/site-packages/illumiprocessor/core.py", line 259, in check_dependencies
    java.test_trimmomatic(args.trimmomatic)
  File "/Users/mirian/anaconda2/lib/python2.7/site-packages/illumiprocessor/core.py", line 252, in test_trimmomatic
    "Trimmomatic does not appear to be installed"
AssertionError: Trimmomatic does not appear to be installed

This same error happened before with my data, so I decided to use the tutorial dataset, in case there was something wrong with my files. I would appreciate any suggestion on how to fix this issue.

Thank you very much.
Best,
Mirian

**Comment by brantfaircloth** [comment]
Is trimmomatic installed?  It is typically located at `~/anaconda/jar/trimmomatic.jar`. Try to run `conda install trimmomatic` if it's not installed.  If it is installed, but at some other path than `~/anaconda/jar/trimmomatic.jar`, then you can pass that path to illumiprocessor using the `--trimmomatic` flag.

**Comment by mtntsuchiya** [comment]
It worked when I added the path using --trimmomatic. Thank you very much!
