### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by wbsimey** [faircloth-lab/phyluce#69]
I have been assembling UCE data using velvet. Trinity and ABySS for comparison. Velvet and Trinity assemblies run to completetion, but ABySS throws an error.
my ABySS scripts is:
phyluce_assembly_assemblo_abyss \
    --config /home/ubuntu/assembly_taxa_all.conf \
    --output /home/ubuntu/phylogenomics/abyss-assemblies \
    --kmer 35 \
    --subfolder split-adapter-quality-trimmed \
    --cores 36 \
    --clean \
    --log-path /home/ubuntu/phylogenomics/log

It seems to be running fine until it hits a specific taxon then throws an error. I have looked at the fastq files for this taxon and I cannot find any offending data:

ubuntu@ip-172-31-11-98:~/phylogenomics$ sh 1_assemble_abyss.sh
2017-05-26 17:39:43,101 - phyluce_assembly_assemblo_abyss - INFO - ============ Starting phyluce_assembly_assemblo_abyss ===========
2017-05-26 17:39:43,101 - phyluce_assembly_assemblo_abyss - INFO - Version: 1.5.0
2017-05-26 17:39:43,102 - phyluce_assembly_assemblo_abyss - INFO - Argument --clean: True
2017-05-26 17:39:43,102 - phyluce_assembly_assemblo_abyss - INFO - Argument --config: /home/ubuntu/assembly_taxa_all.conf
2017-05-26 17:39:43,102 - phyluce_assembly_assemblo_abyss - INFO - Argument --cores: 36
2017-05-26 17:39:43,102 - phyluce_assembly_assemblo_abyss - INFO - Argument --dir: None
2017-05-26 17:39:43,102 - phyluce_assembly_assemblo_abyss - INFO - Argument --kmer: 35
2017-05-26 17:39:43,102 - phyluce_assembly_assemblo_abyss - INFO - Argument --log_path: /home/ubuntu/phylogenomics/log
2017-05-26 17:39:43,102 - phyluce_assembly_assemblo_abyss - INFO - Argument --output: /home/ubuntu/phylogenomics/abyss-assemblies
2017-05-26 17:39:43,103 - phyluce_assembly_assemblo_abyss - INFO - Argument --subfolder: split-adapter-quality-trimmed
2017-05-26 17:39:43,103 - phyluce_assembly_assemblo_abyss - INFO - Argument --verbosity: INFO
2017-05-26 17:39:43,103 - phyluce_assembly_assemblo_abyss - INFO - Getting input filenames and creating output directories
2017-05-26 17:39:43,134 - phyluce_assembly_assemblo_abyss - INFO - ------------- Processing H_procerus_HH1781 ------------
2017-05-26 17:39:43,134 - phyluce_assembly_assemblo_abyss - INFO - Finding fastq/fasta files
2017-05-26 17:39:43,138 - phyluce_assembly_assemblo_abyss - INFO - File type is fastq
2017-05-26 17:39:43,139 - phyluce_assembly_assemblo_abyss - INFO - Running abyss-pe against data
2017-05-26 17:44:12,397 - phyluce_assembly_assemblo_abyss - INFO - Symlinking assembled contigs into /home/ubuntu/phylogenomics/abyss-assemblies/contigs
2017-05-26 17:44:12,397 - phyluce_assembly_assemblo_abyss - INFO - ---------------- Processing H_procerus ----------------
2017-05-26 17:44:12,397 - phyluce_assembly_assemblo_abyss - INFO - Finding fastq/fasta files
2017-05-26 17:44:12,397 - phyluce_assembly_assemblo_abyss - INFO - File type is fastq
2017-05-26 17:44:12,398 - phyluce_assembly_assemblo_abyss - INFO - Running abyss-pe against data
2017-05-26 17:56:17,306 - phyluce_assembly_assemblo_abyss - INFO - Symlinking assembled contigs into /home/ubuntu/phylogenomics/abyss-assemblies/contigs
2017-05-26 17:56:17,307 - phyluce_assembly_assemblo_abyss - INFO - ----------------- Processing H-hist ----------------
2017-05-26 17:56:17,307 - phyluce_assembly_assemblo_abyss - INFO - Finding fastq/fasta files
2017-05-26 17:56:17,307 - phyluce_assembly_assemblo_abyss - INFO - File type is fastq
2017-05-26 17:56:17,307 - phyluce_assembly_assemblo_abyss - INFO - Running abyss-pe against data
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/bin/phyluce_assembly_assemblo_abyss", line 307, in <module>
    main()
  File "/home/ubuntu/anaconda2/bin/phyluce_assembly_assemblo_abyss", line 295, in main
    contigs_file = get_contigs_file_from_output(output)
  File "/home/ubuntu/anaconda2/bin/phyluce_assembly_assemblo_abyss", line 199, in get_contigs_file_from_output
    return glob.glob(os.path.join(output, "*-contigs.fa"))[0]
IndexError: list index out of range

Any thoughts on what might be error?
thank you,
Brian

**Comment by brantfaircloth** [comment]
hmm.  hard to say.  definitely `abyss`-related, since the others ran fine.  did phyluce produce an output log file **from ```abyss```** that you can take a look at (should be prepended with the `H-hist` name)?  Basically,  the log file above is telling you that `phyluce` can't find the `contigs.fa` file (because it has not been made).  So, ```abyss``` likely choked on something while it was running.

Another option, if the log file does not make things clear, is just to run ABYSS on it's own against the data for the ```H-hist``` sample with something like:

```abyss-pe k=31 j=<cores> name=test_assembly in=/path/to/r1.fastq.gz /path/to/r2.fastq.gz```

and see where `abyss` is having a problem on that file.

**Comment by wbsimey** [comment]
Thank you Brant. The ABySS log file generated in  the H-hist dir indicated a problem with the .gz format. Turns out that another dumb script I made added .gz to the end of a few of the fastq files. I simply fixed the extension and it is working. I have no idea how velvet ran to completion with out throwing an error. I better check the output data.
thanks again.
