### ISSUE TITLE
UnboundLocalError: local variable 'cnt' referenced before assignment

### ISSUE THREAD

**Issue by bastianheimburger** [faircloth-lab/phyluce#84]
Dear Mr Faircloth,

I have an issue concerning 'phyluce_probe_get_genome_sequences_from_bed'. Once I start the python script, I get following error message:

gwdu102:90 12:52:50 /scratch/bheimbu/bin/UCE/bed > /scratch/bheimbu/bin/anaconda2/envs/phyluce/bin/phyluce_probe_get_genome_sequences_from_bed         --bed BlattellaGenome+5.bed          --twobit /scratch/bheimbu/bin/UCE/genomes/BlattellaGenome/BlattellaGenome.2bit         --buffer-to 160         --output BlattellaGenome+5.fasta
Traceback (most recent call last):
  File "/scratch/bheimbu/bin/anaconda2/envs/phyluce/bin/phyluce_probe_get_genome_sequences_from_bed", line 121, in <module>
    main()
  File "/scratch/bheimbu/bin/anaconda2/envs/phyluce/bin/phyluce_probe_get_genome_sequences_from_bed", line 112, in main
    cnt + 1,
UnboundLocalError: local variable 'cnt' referenced before assignment

Do you have any idea how to fix it? Any help is highly appreciated.

Cheers Bastian

**Comment by bastianheimburger** [comment]
Hey,

I fixed it myself. There was a problem concerning scoping rules in line 112. I've changed the script (find attached).

Cheers Bastian

[phyluce_probe_get_genome_sequences_from_bed-1-fix.txt](https://github.com/faircloth-lab/phyluce/files/1404202/phyluce_probe_get_genome_sequences_from_bed-1-fix.txt)
