### ISSUE TITLE
Error in phyluce PATH

### ISSUE THREAD

**Issue by patrick-douglas** [faircloth-lab/phyluce#88]
My command line bellow:
`phyluce_assembly_assemblo_trinity --config /media/me/BACK_UP_4/Project_Leilton_PhD/2_clean-reads/config --output  /media/me/BACK_UP_4/Project_Leilton_PhD/Assembly --subfolder split-adapter-quality-trimmed --clean --cores 12 --log-path /media/me/BACK_UP_4/Project_Leilton_PhD/log`

I'm getting the following error:
```
2017-11-22 15:27:19,778 - phyluce_assembly_assemblo_trinity - INFO - =========== Starting phyluce_assembly_assemblo_trinity ==========
2017-11-22 15:27:19,779 - phyluce_assembly_assemblo_trinity - INFO - Version: 1.5.0
2017-11-22 15:27:19,779 - phyluce_assembly_assemblo_trinity - INFO - Argument --clean: True
2017-11-22 15:27:19,779 - phyluce_assembly_assemblo_trinity - INFO - Argument --config: /media/me/BACK_UP_4/Project_Leilton_PhD/2_clean-reads/config
2017-11-22 15:27:19,779 - phyluce_assembly_assemblo_trinity - INFO - Argument --cores: 12
2017-11-22 15:27:19,779 - phyluce_assembly_assemblo_trinity - INFO - Argument --dir: None
2017-11-22 15:27:19,779 - phyluce_assembly_assemblo_trinity - INFO - Argument --log_path: /media/me/BACK_UP_4/Project_Leilton_PhD/log
2017-11-22 15:27:19,780 - phyluce_assembly_assemblo_trinity - INFO - Argument --min_kmer_coverage: 2
2017-11-22 15:27:19,780 - phyluce_assembly_assemblo_trinity - INFO - Argument --output: /media/me/BACK_UP_4/Project_Leilton_PhD/Assembly
2017-11-22 15:27:19,780 - phyluce_assembly_assemblo_trinity - INFO - Argument --subfolder: split-adapter-quality-trimmed
2017-11-22 15:27:19,780 - phyluce_assembly_assemblo_trinity - INFO - Argument --verbosity: INFO
2017-11-22 15:27:19,780 - phyluce_assembly_assemblo_trinity - INFO - Getting input filenames and creating output directories
Traceback (most recent call last):
  File "/home/me/anaconda2/bin/phyluce_assembly_assemblo_trinity", line 356, in <module>
    main()
  File "/home/me/anaconda2/bin/phyluce_assembly_assemblo_trinity", line 316, in main
    raise EnvironmentError("Cannot find Trinity.  Ensure the $PATH is correctly entered in your phyluce.conf file.")
EnvironmentError: Cannot find Trinity.  Ensure the $PATH is correctly entered in your phyluce.conf file.
```
See bellow my `phyluce.conf`
```
[trinity]
trinity:$CONDA/bin/Trinity
max_memory:8G
kmer_coverage:2
```

**Comment by brantfaircloth** [comment]
Is this still an issue?  Closing for now but will re-open if needed.
