### ISSUE TITLE
phyluce_assembly_assemblo_trinity dont work in cluster.

### ISSUE THREAD

**Issue by SergioB1983** [faircloth-lab/phyluce#93]
Hi everyone,

I am running some scripts of phyluce in a linux cluster (64 CPUs, 132 GB RAM). Running the phyluce_assembly_assemblo_trinity, the script shows this error:

```
2018-01-25 12:48:51,468 - phyluce_assembly_assemblo_trinity - INFO - Running Trinity.pl for PE data
2018-01-25 12:58:31,500 - phyluce_assembly_assemblo_trinity - INFO - Removing extraneous Trinity files
Traceback (most recent call last):
  File "/home/sergio/.conda/envs/phyluce/bin/phyluce_assembly_assemblo_trinity", line 347, in <module>
    main()
  File "/home/sergio/.conda/envs/phyluce/bin/phyluce_assembly_assemblo_trinity", line 326, in main
    cleanup_trinity_assembly_folder(output, log)
  File "/home/sergio/.conda/envs/phyluce/bin/phyluce_assembly_assemblo_trinity", line 276, in cleanup_trinity_assembly_folder
    raise IOError("Neither Trinity.fasta nor trinity.log were found in output.")
IOError: Neither Trinity.fasta nor trinity.log were found in output.
```
I think that is not a problem of RAM, number of CPUs, or the phyluce installation. Also, the $PATHs of the config file are correct. Also, the trinity.log of the first sample shows this output:

```
Trinity version: v2.0.6
-ERROR: couldn''t run the network check to confirm latest Trinity software version.

Wednesday, January 24, 2018: 14:01:32	CMD: java -Xmx64m -jar /home/sergio/.conda/envs/phyluce/bin/trinity-2.0.6/util/support_scripts/ExitTester.jar 0
Wednesday, January 24, 2018: 14:01:32	CMD: java -Xmx64m -jar /home/sergio/.conda/envs/phyluce/bin/trinity-2.0.6/util/support_scripts/ExitTester.jar 1
Wednesday, January 24, 2018: 14:01:32	CMD: mkdir -p /home/sergio/sergio_UCE/test_mentalis/02_assembly/O080_Dys_men_MZ_91201_BR_SC_trinity/chrysalis
.
.
.
----------------------------------------------
--------------- Inchworm ---------------------
-- (Linear contig construction from k-mers) --
----------------------------------------------

Wednesday, January 24, 2018: 14:03:22	CMD: /home/sergio/.conda/envs/phyluce/bin/trinity-2.0.6/Inchworm/bin//inchworm --kmers jellyfish.kmers.fa --run_inchworm -K 25 -L 25 --monitor 1   --DS  --keep_tmp_files  --num_threads 6  --PARALLEL_IWORM  > /home/sergio/sergio_UCE/test_mentalis/02_assembly/O080_Dys_men_MZ_91201_BR_SC_trinity/inchworm.K25.L25.DS.fa.tmp 2>/dev/null
Wednesday, January 24, 2018: 14:05:08	CMD: touch /home/sergio/sergio_UCE/test_mentalis/02_assembly/O080_Dys_men_MZ_91201_BR_SC_trinity/inchworm.K25.L25.DS.fa.finished
Running cmd: /home/sergio/.conda/envs/phyluce/bin/trinity-2.0.6/util/misc/fasta_filter_by_min_length.pl /home/sergio/sergio_UCE/test_mentalis/02_assembly/O080_Dys_men_MZ_91201_BR_SC_trinity/inchworm.K25.L25.DS.fa 100 > /home/sergio/sergio_UCE/test_mentalis/02_assembly/O080_Dys_men_MZ_91201_BR_SC_trinity/chrysalis/inchworm.K25.L25.DS.fa.min100
Running cmd: bowtie-build -q /home/sergio/sergio_UCE/test_mentalis/02_assembly/O080_Dys_men_MZ_91201_BR_SC_trinity/chrysalis/inchworm.K25.L25.DS.fa.min100 /home/sergio/sergio_UCE/test_mentalis/02_assembly/O080_Dys_men_MZ_91201_BR_SC_trinity/chrysalis/inchworm.K25.L25.DS.fa.min100 2>/dev/null
Running cmd: bash -c " set -o pipefail; bowtie -a -m 20 --best --strata --threads 24  --chunkmbs 512 -q -S -f /home/sergio/sergio_UCE/test_mentalis/02_assembly/O080_Dys_men_MZ_91201_BR_SC_trinity/chrysalis/inchworm.K25.L25.DS.fa.min100 both.fa  | samtools view -@ 24 -F4 -Sb - | samtools sort -@ 24 -no - - > /home/sergio/sergio_UCE/test_mentalis/02_assembly/O080_Dys_men_MZ_91201_BR_SC_trinity/chrysalis/iworm.bowtie.nameSorted.bam"  2>/dev/null
Trinity run failed. Must investigate error above.
```
So, it is a problem of the version of trinity (2.0.6)?, or some problem in the configuration of packages in the cluster? In addition, it is necessary updated to lastest version of trinity (2.5.1)? 

Thanks in advance for the help.

**Comment by brantfaircloth** [comment]
It looks like the installation of trinity is failing, but I am not sure why.  Usually, this is due to RAM and there is not enough for the data you are trying to assemble.

**Comment by SergioB1983** [comment]
Hi, yes, the problem was the installation, now is working!

Thanks!
