### ISSUE TITLE
Issues with phyluce_align_convert_one_align_to_another

### ISSUE THREAD

**Issue by jpicathartes** [faircloth-lab/phyluce#94]
Hi --

I've been having issues converting uce nexus alignments to phylip format. My intention is to feed these phylip alignments to RaXML to get genetrees. Unfortunately, I've been running into two issues, when using phyluce_align_convert_one_align_to_another.

**Firstly, when attempting to run the following (with the --shorten names flag)**:  

phyluce_align_convert_one_align_to_another --alignments incomplete_min_36_taxa_test --output incomplete_min_36_taxa_phylip --input-format nexus --output-format phylip --cores 4 --shorten-names --log-path logs
 
**I get the following error message**:   

File "/home/hruska/anaconda2/bin/phyluce_align_convert_one_align_to_another", line 194, in <module>
    main()
  File "/home/hruska/anaconda2/bin/phyluce_align_convert_one_align_to_another", line 181, in main
    pool.map(convert_files_worker, params)
  File "/home/hruska/anaconda2/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/hruska/anaconda2/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
KeyError: 'egretta_rufescens_B6449'

Egretta rufescens is not the first taxa on my alignments, so for the script to stop at this point seems arbitrary. 

**Secondly, when attempting to run the following (without the --shorten-names flag)**:

phyluce_align_onvert_one_align_to_another --alignments incomplete_min_36_taxa_test --output incomplete_min_36_taxa_phylip --input-format nexus --output-format phylip --cores 4 --log-path logs

**I get the following error message**: 

 File "/home/hruska/anaconda2/bin/phyluce_align_convert_one_align_to_another", line 194, in <module>
    main()
  File "/home/hruska/anaconda2/bin/phyluce_align_convert_one_align_to_another", line 181, in main
    pool.map(convert_files_worker, params)
  File "/home/hruska/anaconda2/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/hruska/anaconda2/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ValueError: Repeated name 'gorsachius' (originally 'gorsachius_melanolophus_10441'), possibly due to truncation

Again, this appears to be arbitrary, given that gorsachius is not the first genus to appear as a duplicate in the alignments. 

Any help on this matter would be greatly appreciated. 

Best
Jack

**Comment by brantfaircloth** [comment]
Hi Jack,

why don't you try the output format as `--phylip-relaxed` - then you don't need to worry about shortened names (raxml can easily ingest phylip relaxed format)?  The problem that you are seeing is likely due to *how* the names are being shortened (and the fact that they become non-unique when shortened).

-b

**Comment by jpicathartes** [comment]
Hi Brant--

Thanks, that seemed to fix it. 

Jack

**Comment by KNx5** [comment]
I have the same error (#1), but I would like to have strict phylip files. 
The taxon this has flagged on is not something should be non-unique at 10 chars. Any ideas? 
KeyError: 'Bittacidae_B3'

2018-09-14 12:06:04,723 - phyluce_align_convert_one_align_to_another - INFO - ====== Starting phyluce_align_convert_one_align_to_another ======
2018-09-14 12:06:04,723 - phyluce_align_convert_one_align_to_another - INFO - Version: git fatal: Not a git repository: '/home/feenerlab/miniconda2/lib/python2.7/site-packages/.git'
2018-09-14 12:06:04,724 - phyluce_align_convert_one_align_to_another - INFO - Argument --alignments: /home/feenerlab/katinkaX/DipteraUCEs/Diptera_wide/silico_vitro/datasets/mafft-nexus_clean/gblocks2_70
2018-09-14 12:06:04,724 - phyluce_align_convert_one_align_to_another - INFO - Argument --cores: 8
2018-09-14 12:06:04,724 - phyluce_align_convert_one_align_to_another - INFO - Argument --input_format: nexus
2018-09-14 12:06:04,724 - phyluce_align_convert_one_align_to_another - INFO - Argument --log_path: /home/feenerlab/katinkaX/DipteraUCEs/Diptera_wide/silico_vitro/datasets/filter_missing/log
2018-09-14 12:06:04,724 - phyluce_align_convert_one_align_to_another - INFO - Argument --name_conf: None
2018-09-14 12:06:04,724 - phyluce_align_convert_one_align_to_another - INFO - Argument --output: /home/feenerlab/katinkaX/DipteraUCEs/Diptera_wide/silico_vitro/datasets/mafft-nexus_clean/gblocks2_70/shortnames
2018-09-14 12:06:04,724 - phyluce_align_convert_one_align_to_another - INFO - Argument --output_format: phylip
2018-09-14 12:06:04,724 - phyluce_align_convert_one_align_to_another - INFO - Argument --shorten_name: True
2018-09-14 12:06:04,725 - phyluce_align_convert_one_align_to_another - INFO - Argument --verbosity: INFO
ConvertingTraceback (most recent call last):
  File "/home/feenerlab/miniconda2/bin/phyluce_align_convert_one_align_to_another", line 197, in <module>
    main()
  File "/home/feenerlab/miniconda2/bin/phyluce_align_convert_one_align_to_another", line 184, in main
    pool.map(convert_files_worker, params)
  File "/home/feenerlab/miniconda2/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/feenerlab/miniconda2/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
KeyError: 'Bittacidae_B3'

**Comment by KNx5** [comment]
Well, solved this. phyluce_align_convert_one_align_to_another has an option for a conf file which isn't discussed in the tutorial. making this file solved my naming issues. I guess other people get around this by not going over 10 chars for the initial taxon name .conf file.
